### ISSUE TITLE
Assertion failed `(access(app_path, F_OK) == 0`

### ISSUE THREAD

**Issue by sandstrom** [phonegap/ios-deploy#106]
Getting the following error when running ios-deploy 1.4.0 with iOS Cordova platform 3.8.0.

> Running command: /Users/my-user/cordova/platforms/ios/cordova/run --device --nobuild
> [....] Waiting up to 5 seconds for iOS device to be connected
> [....] Found iPhone 4S 'my-user's iPhone' (62a2719564784b38c951238f1ac84433679b4eaa) connected through USB.
> **Assertion failed: (access(app_path, F_OK) == 0), function main, file ios-deploy.c, line 1766.**
> ** RUN SUCCEEDED **
 
*Full paste error:*
http://pastie.org/private/nkeikzhsmdkr8ktc2tcfa

**Comment by shazron** [comment]
F_OK means its testing for existence of the file at app_path. The path does not exist

**Comment by sandstrom** [comment]
For anyone tripping on this, the reason was simply that nothing existed in the path (as shazron points out). This, in turn, was caused by `cordova compile ios` not compiling for devices by default with ios platform 3.8.0. However, this is easily fixed by using `cordova compile ios --device` instead.
