### ISSUE TITLE
is it possible to download contents from a specified directory?

### ISSUE THREAD

**Issue by mikelupo** [phonegap/ios-deploy#108]
The download_tree option works great. Thank you for this clever innovation. 
However, I only want to pull of screenshots that are written to the device by our automated test tool (KIF). The files are written to the app sandbox in the ~/Documents directory. Any chance for an enhancement so that we can specify just that directory? Else, I'm pulling down (potentially gigabytes) of mp4s from the /Library folder as our app is a media player.

Thanks!!

**Comment by mikelupo** [comment]
Answer to my own question after studying the code: 
Yes! You can specify it on the command line.

For example:
ios-deploy <b>--download=/Documents</b> -bundle_id my.app.id --to ./FOO

Result: Will download the contents of the /Documents directory into ./FOO and will ignore the /Library and /tmp directories. 

Could someone please update the documentation in the readme.md file to reflect this?

Wondering out loud if this would even support regex for pulling files that matched a pattern???
Thanks

**Comment by shazron** [comment]
Thanks @mikelupo - did you successfully do this on an iOS 8 system or was it an earlier iOS version?

**Comment by mikelupo** [comment]
iOS 8.
I did a nice write up on the KIF-Framework site. 
https://groups.google.com/forum/#!topic/kif-framework/sLls_MlJAsE








-----Original Message-----

**Comment by mikelupo** [comment]
iOS 8 I think. Do you still need an answer?

**Comment by shazron** [comment]
No, you already replied Mar 12 :) I updated docs in the referenced commit.

**Comment by mikelupo** [comment]
Ok thanks.
