### ISSUE TITLE
Assertion failed: (access(app_path, F_OK) == 0)

### ISSUE THREAD

**Issue by nodesocket** [phonegap/ios-deploy#110]
Running:

     cordova run --device ios

Getting:

````
[....] Waiting up to 5 seconds for iOS device to be connected
[....] Found iPhone 6 (GSM) 'Justin's iPhone' (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx) connected through USB.
Assertion failed: (access(app_path, F_OK) == 0), function main, file ios-deploy.c, line 1766.
** RUN SUCCEEDED **
````

![screen shot 2015-03-30 at 10 58 45 pm](https://cloud.githubusercontent.com/assets/523312/6913118/589295aa-d730-11e4-88b7-6032f266f2cc.png)

**Comment by shazron** [comment]
Check that app_path exists, that's what this error is.

**Comment by shazron** [comment]
Re-open if this is still an issue.

**Comment by nodesocket** [comment]
Fix, it was caused by having spaces in `config.xml` in the name field.
