### ISSUE TITLE
How to install without npm?

### ISSUE THREAD

**Issue by mikelupo** [phonegap/ios-deploy#118]
Hi,
The NPM package is not updated with the latest merged pull requests. For example, the -R <--rm> is not in the npm package distribution. 
For those of us wishing to take it into use before it's pushed up to npm, is there a published way to do this?

Thanks in advance

**Comment by mikelupo** [comment]
I answered my own question. It's in the documentation but it's not clear that you're installing ios-deploy when you run make and then make install. 
Instead it leads me to believe that I'm installing the Demo only.

Attempting to install directly from github "npm install git@github.com:phonegap/ios-deploy.git" fails.
Pulling the repo and running, make then run make install creates the ios-deploy executable.
It must then be placed on your path. npm installs it at "/usr/local/bin/ios-deploy" for me. so I just replaced that exe and I'm in business.

Maybe you can go ahead and close this issue, but I'll leave it open in the case that you want to use it as an issue to modify the documentation.

Regards,
Mike

**Comment by shazron** [comment]
Thanks Mike, I'll update the docs for the non-npm case.
