### ISSUE TITLE
Proper syntax for uninstall

### ISSUE THREAD

**Issue by mikelupo** [phonegap/ios-deploy#120]
Hi,
I'm trying to merely uninstall an app from an iOS 8.3 device. I do not want to reinstall it. xcodebuild will do that for me in the next step of my build job.
Could use some help.
Version is 1.0.5 built directly from the repo. SHA1: 1db084594ee24e72115323544671340684678eb8

I've tried a few permutations: 
ios-deploy --uninstall --bundle my.bundle.id
Fails with: Assertion failed: (access(app_path, F_OK) == 0), function main, file ios-deploy.c, line 1851.

ios-deploy --uninstall
which prints the help screen (of course since it has no idea what to uninstall)

ios-deploy --uninstall --bundle_id my.bundle.id
which also prints help.

Can't seem to figure out how to get uninstall to work.

**Comment by shazron** [comment]
I think this is a misunderstanding on what uninstall does: "uninstall the app before install". I'll close this since you sent a pull request #35  for the functionality you want.
