### ISSUE TITLE
Using the -c option for listing device UUIDs instead the system_profiler

### ISSUE THREAD

**Issue by gpetrov** [phonegap/ios-deploy#122]
In the README there is way described for listing device Ids with system_profiler.

Why not just use the -c option?

Also do allow the timeout to be 0 so that the -c option just directly list the connected devices and do not add a timeout of 5 seconds.

Maybe also a new options such as -j will be handy to output the list in JSON format, so that the Cordova CLI can pick the real device names and their ids much easier!

Currently with the system_profiler way there is no way to get the real device names, just their UUIDs

**Comment by shazron** [comment]
Filed #125 for the -j option.
