### ISSUE TITLE
--download option work incorrect 

### ISSUE THREAD

**Issue by Incont** [phonegap/ios-deploy#126]
Use iOS-deploy 1.6.0
<code>$ios-deploy --bundle_id com.test.test1 --list</code>
...
<code>/Library/Caches/log.txt</code>
...

1. <code>$ios-deploy --bundle_id com.test.test1 --download=/Library --to /test</code> - work correct
2. <code>$ios-deploy --bundle_id com.test.test1 --download=/Library/Caches/ --to /test</code> - not work
3. <code>$ios-deploy --bundle_id com.test.test1 --download=/Library/Caches/log.txt --to /test</code> - not work
4. <code>$ios-deploy --bundle_id com.test.test1 --download=/Library/Caches/folder/ --to /test</code> - not work

**Comment by shazron** [comment]
Some clues. 
For 2, if /test/Library already exists, it works.
For 3,  if /test/Library/Caches already exists, it works.

**Comment by Incont** [comment]
Yes I agree
I expect as a user I do not need to manually create the path

**Comment by shazron** [comment]
The fix is:
if ```--download=/X/Y --to R```

you must ```mkdir -p```

   // parent of (/X/Y)
    R/X/

**Comment by ChrisMash** [comment]
@shazron In 1.9.2, trying to download the caches folder from an AppleTV doesn't work. I can't get any of the options Incont tried to work. It all works fine on an iPad though...
