### ISSUE TITLE
ios-deploy -c not listing devices with unicode characters

### ISSUE THREAD

**Issue by GOBIM** [phonegap/ios-deploy#132]
$ ios-deploy -c
[....] Waiting up to 5 seconds for iOS device to be connected
[....] Found (null) connected through USB.
For any version of ios-deploy(tried 1.2,1.3,1.5,1.6,1.6.1) i am not able to list ios 8 devices in my machine.
iOS 7 it is working fine!!!
Could you please help me to fix this?

**Comment by Incont** [comment]
Hi, Gobim
Does iTunes detect device?

**Comment by GOBIM** [comment]
yes, i am able to launch app through xcode also.

**Comment by shazron** [comment]
I'm on an iPhone 6 Plus iOS 8 device and it listed fine. Not sure what's going on there.

**Comment by shazron** [comment]
Ok, I repro'ed this on an iPad Mini (1st Gen) that I have with iOS 7.1.1

**Comment by shazron** [comment]
Repro'ed on an iPad 2 running iOS 8.3 as well.

**Comment by shazron** [comment]
Can you run it with the verbose flag, what do you see?
```
ios-deploy -c --verbose
```

**Comment by shazron** [comment]
Found the problem. It's a unicode string printing problem.
