### ISSUE TITLE
Minor bug: incorrect log

### ISSUE THREAD

**Issue by Incont** [phonegap/ios-deploy#138]
[....] Using iPhone 5 (Global/CDMA) 'test8' (xxxxxx96eb3dc093c6a4ed732fb9bf790f78a865) (xxxxxx96eb3dc093c6a4ed732fb9bf790f78a865).

device_full_name includes udid

**Comment by shazron** [comment]
Fixed in 84aeaad03b37420aa69b9ea233a4526d7d43eaf4
