### ISSUE TITLE
Bug: stderr incorrect

### ISSUE THREAD

**Issue by Incont** [phonegap/ios-deploy#139]
my test.py
#!/usr/bin/python
import os
import subprocess
print os.popen("ios-deploy --version").read()
command = "ios-deploy --id xxxxxx96eb3dc093c6a4ed732fb9bf790f78a865 --bundle_id com.test.test --exists --timeout 2"

stdout, stderr = subprocess.Popen([command], shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
print "stdout: "
print stdout
print "stderr: "
print stderr
print "end!"

$ python test.py
1.7.0

stdout: 
[....] Waiting up to 2 seconds for iOS device to be connected
true

stderr: 
Skipping iPhone 4S 'test3' (xxxxxxxacf469ae26a7739536abf4758ad179a3b4).
[....] Using iPhone 5 (Global/CDMA) 'test' (xxxxxx96eb3dc093c6a4ed732fb9bf790f78a865) (b9cdc896eb3dc093c6a4ed732fb9bf790f78a865).

end!
If I understand [....] - stdout, [ ERROR ] -stderr?

**Comment by shazron** [comment]
As I mentioned in #140, a change to NSLog would be better here.
Change:
```
CFShow([NSString stringWithFormat:formatString, myString]);
```
to:
```
NSLog(formatString, myString)
```

**Comment by shazron** [comment]
Ok, I'm mistaken I thought NSLog went to stdout, it still goes to stderr.

**Comment by shazron** [comment]
```
void writeStdout(CFStringRef myString) {
       [myString writeToFile:@"/dev/stdout" atomically:NO encoding:NSUTF8StringEncoding error:nil];
}
```

**Comment by Incont** [comment]
I do not know much c, objective-c.  Please solve this problem

**Comment by shazron** [comment]
Alright, I'll fix it.
