### ISSUE TITLE
Application not updated

### ISSUE THREAD

**Issue by krstns** [phonegap/ios-deploy#14]
Hello,

I'm using ios-deploy to deploy my app, but it will never update my existing app. I have to remove the app prior running ios-deploy.
I haven't seen any option to update the app, this is how I'm using it:

```
ios-deploy -d `system_profiler SPUSBDataType | sed -n -e '/iPad/,/Serial/p' -e '/iPhone/,/Serial/p' | grep "Serial Number:" | awk -F ": " '{print $2}' | head -n 1` -b `ls -t builds/App*ipa | head -n 1` -v
```

I made sure that the file is correct, I can see console logs from the device, but there are no errors there. The same line fired when I remove the app manually from the device will update it fine.

iOS 6.1.4

**Comment by shazron** [comment]
Download option is already there.
