### ISSUE TITLE
Cannot deploy iOS app - Error 0x800801c: AMDeviceSecureInstallApplication

### ISSUE THREAD

**Issue by andry-tino** [phonegap/ios-deploy#148]
I am trying to deploy an iOS app on iOS 7.1.1 but it fails.

    ...
    [48%] Copying /.../MyApp.app/...
    [52%] CreatingStartingDirectory
    [57%] ExtractingPackage
    [60%] InspectingPackage
    [60%] TakingInstallLock
    [65%] PreflightingApplication
    [70%] VerifyingApplication
    2015-06-03 19:16:14.325 ios-deploy[95588:507] [ ! ! ] Error 0x800801c: AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

What can I do?

**Comment by shazron** [comment]
What flags if any are you using?
Are you certain that the .app was code-signed properly?

**Comment by andry-tino** [comment]
I can deploy the app using XCode so I think that code signing is perfectly fine. I use a device with the correct provisioning profile also. I am running ios-deploy as follows:

    ios-deploy --bundle MyApp.app

Also tried specifying debug or the bundle id. Same result.

**Comment by shazron** [comment]
From what I've seen when this happens, it is usually a code-signing error.

**After** you've successfully deployed to your device through Xcode:
1. Go to your Xcode Project Navigator
2. Expand the "Products" group
3. Find your .app
4. Right-click on your .app
5. Choose "Show in Finder"

Try to deploy that using ios-deploy.

**Comment by savishy** [comment]
Just to chime in, I received a similar error with 1.7.0 and mine was fixed by the suggestion by @shazron 
`2015-07-17 16:27:19.347 ios-deploy[8716:163596] [ !! ] Error 0xe8000087: zyˇ AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
`

**Comment by jhuska** [comment]
I am receiving the error described above:
``2015-07-17 04:15:37.300 ios-deploy[460:7199] [ !! ] Error 0xe8008015: gSvˇ AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)``

I am installing the application from the proposed location:
``~/Library/Developer/Xcode/DerivedData/appName-somehash/Build/Products/Debug-iphoneos/my.app``

The thing is that I am able to install it with the same command on my other two devices: iPhone 5 & 5S. The error occurs when using the command for installing for another different 5S.

**Comment by tracy-e** [comment]
I have the some problem. I install app with `ios-deploy -i [udid] -b path/to/myapp.app` with the some build of app package, but the result is random, some time it's successful installed, but the other time I get `iso-deploy[15061:920515] [ !! ] Error 0xe8008018: @伏}... AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)`

> My devices is iPhone 4S (iOS 7.0)

**Comment by Smilediver** [comment]
@tracy-e: probably your signing certificate has expired.

**Comment by pyavcom** [comment]
got same error with ionic 2.1.7 cordova 6.4.0 platform 4.1.1
After run project via Xcode 8.2, ionic run ios --device at load app to device give this bug. This second time when i getting it at different environments.

**Comment by talsurizon** [comment]
hi,
when i try ti run the app using ios-deploy i get the massage:

2016-11-27 10:19:44.068 ios-deploy[1493:25125] [ !! ] One of -[b|c|o|l|w|D|R|e|9] is required to proceed!

what does it mean and how can i move on?

**Comment by UtopiaHXM** [comment]
cannot install on 10.3.3,and got the same error
 [ !! ] Error 0xe8008017: A signed resource has been added, modified, or deleted. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
