### ISSUE TITLE
Trouble with 'cordova run' without installing ios-deploy globally

### ISSUE THREAD

**Issue by micky2be** [phonegap/ios-deploy#149]
I don't wanna have all my team installing cordova and ios-deplay globally.
Specially since we work on different projects with potentially different versions.
My package.json inclue cordova (5.0.0) and ios-deploy (1.7.0) but `cordova run` seems to try running `ios-deploy` as a cli but of course can't find it.
```bash
> node node_modules/.bin/cordova run --device ios
Running command: /Users/me/Sources/myproject/platforms/ios/cordova/run --device
ios-deploy was not found. Please download, build and install version 1.2.0 or greater from https://github.com/phonegap/ios-deploy into your path. Or 'npm install -g ios-deploy' using node.js: http://nodejs.org
ERROR running one or more of the platforms: Error: /Users/me/Sources/myproject/platforms/ios/cordova/run: Command failed with exit code 2
You may not have the required environment or OS to run this project
```

The only solution I found so far is by having a Makefile running my command which also add to my PATH my bin folder (`./node_modules/.bin`).

In my opinion as an npm module cordova shouldn't require to have ios-deploy (or ios-sim) to be globally installed. It's just a peer dependency.

**Comment by shazron** [comment]
I agree, see the roadmap here: https://shazronatadobe.wordpress.com/2015/05/18/ios-deploy-and-ios-sim-roadmaps/

https://github.com/phonegap/ios-deploy/milestones

**Comment by shazron** [comment]
Perhaps an interim solution in 1.8.0 is to export a function that can use the right ios-deploy path if  you installed it locally.

Pseudocode:
```
var ios_deploy = require('ios-deploy');
var args = ['-d', '-b' 'my.app.id'];

ios_deploy(args);
```

**Comment by micky2be** [comment]
Looking forward

**Comment by shazron** [comment]
I'm going to close this since I added the cordova issue: https://issues.apache.org/jira/browse/CB-9757
Please continue the discussion there since this is most likely cordova-specific.
