### ISSUE TITLE
Getting an error on uninstall when bundle id is not found

### ISSUE THREAD

**Issue by micky2be** [phonegap/ios-deploy#152]
When running `ios-deploy --uninstall_only --bundle_id my.bundle.id` I do not expect getting the following error if the bundle ID is not found.
```bash
[ !! ] [ ERROR ] Could not uninstall package with bundle id my.bundle.id
```
At worse it should show a more informative message.
At best IMO it should consider it successful since the app is not on the device.

> Using ios-deploy v1.7.0

**Comment by hoihoi8** [comment]
+1. I'd like my ios-deploy to uninstall if the app is there, but if it's not, I'd like it to continue without error.

**Comment by shazron** [comment]
This makes sense, but not from a CLI point of view -- the command actually fails. If the app doesn't exist, then the uninstallation failed. I suppose one could pair this with a --exists before hand.

In any case, I agree with this proposed change as long as the intent was clear in the docs.

**Comment by hoihoi8** [comment]
A flag like "ifexists uninstall" sounds like a reasonable solution. I've worked around this behavior for now by installing the app manually the first time, that way there is an app to uninstall.

**Comment by shazron** [comment]
Without adding more flags, I think the best compromise is if you pair --uninstall_only with --exists, it will report success if it's not already installed.

**Comment by shazron** [comment]
With El Cap and Xcode 7, I don't see this problem anymore. If you try to uninstall a non-existent bundle id, it will report a success. Apple may have changed the implementation of AMDeviceSecureUninstallApplication for privacy reasons, not sure.

**Comment by black-square** [comment]
@shazron I have this problem on iPad 4 (A1458), iOS 8.2. AMDeviceSecureUninstallApplication returns 0xe8000067 if application doesn't exist.  At the same time iPhone 6s,  iOS 9.3.3 works fine (function always returns 0).
XCode 7.3.1, Mac OS 10.11.6
