### ISSUE TITLE
ios-deploy not work after changing CFBundleDisplayName with PListBuddy

### ISSUE THREAD

**Issue by Nos2015** [phonegap/ios-deploy#158]
Hi,

I built my XCode project with release and device configuration.
I changed the CFBundleDisplayName of the Info.pList file in the configuration build directory.
Then i tried ios-deploy --bundle /path/to/myapp.app and i received this :
...
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
2015-07-22 15:28:55.105 ios-deploy[53907:397326] [ !! ] Error 0xe8008019: @∑B}ˇ AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

**Comment by shazron** [comment]
Did you change it after you already built and code signed it? Yeah that will result in an invalid deploy of course.

**Comment by Nos2015** [comment]
I built my project like this : 
xcodebuild -configuration Release -sdk "$typedevice" ONLY_ACTIVE_ARCH=NO -target GMI -project "$project" build CONFIGURATION_BUILD_DIR="$builddir"> /dev/null || exit 1

Then i want to change the CFBundleDisplayName in the Info.plist. I don't want to change the original project. How can i perform this to use after ios-deploy ?

**Comment by Nos2015** [comment]
I built, i changed informations in Info.plist and then i resigned the app. Finally i tried to use iOS-deploy and it failed.
the command lines i used:
xcodebuild -configuration Release -sdk "$typedevice" ONLY_ACTIVE_ARCH=NO -target GMI -project "$project" build CONFIGURATION_BUILD_DIR="$builddir"> /dev/null || exit 1
rm -rf MyApp.app/_CodeSignature/
/usr/libexec/PlistBuddy MyApp.app/Info.plist
Set :CFBundleDisplayName MyNewApp
save
quit
cp <path_to_provisioing_profile>/Distribution.mobileprovision MyApp.app/embedded.mobileprovision 
/usr/bin/codesign -f -s "iPhone Distribution: MyCertificate" "MyApp.app"
ios-deploy --bundle MyApp.app

Result :
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
2015-07-23 14:46:04.396 ios-deploy[37669:166577] [ !! ] Error 0xe800003a: ~ˇ AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

**Comment by Nos2015** [comment]
I found how to do it.
You need to create an Entitlements plist file first :

defaults write /tmp/Entitlements application-identifier yourteamemberidentifier.bundleidentifier
/usr/libexec/PlistBuddy -c "Add :get-task-allow bool" /tmp/Entitlements.plist

then you remove the old signature :

rm -rf ../path/to/your/app/yourapp.app/_CodeSignature/

then you change what you want in your Info.plist ( for example CFBundleDisplayName) :

$(/usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName yournewname" "path/to/your/app/yourapp.app/Info.plist")

copy your provisioning profile :

cp /path/to/your/new/provisioning/yourprovisioning.mobileprovision /path/to/your/app/yourapp.app/embedded.mobileprovision

finally resign your app and deploy it with the entitlements file :

 /usr/bin/codesign -f -s "iPhone Distribution: name of your certificate" --entitlements /tmp/Entitlements.plist /path/to/your/app/yourapp.app

ios-deploy --bundle /path/to/your/app/yourapp.app
