### ISSUE TITLE
launch already installed application

### ISSUE THREAD

**Issue by mikehouse** [phonegap/ios-deploy#160]
Could not find how to do that. I'm using the appbuilder for that.

**Comment by shazron** [comment]
I have no idea how repro this, since I don't use (nor am interested in using) appbuilder. More info needed.  What have you tried from the docs?

**Comment by mikehouse** [comment]
Hi. I've found in the docs the "--noinstall" command, maybe you mean this?... Yes it does work. Thank you! But it doesn't work with an ipa file, an app only ("Segmentation fault: 11" will be thrown when using the ipa file). 
I'd like to use a bundle id string only instead the app file to launch that, something like this

```
ios-deploy -i b1495776bd90c10cf95dc045175b1dd25f799569 -b my.bundle.string --noinstall --justlaunch 
```
:)
or I've something overlooked again?(

**Comment by shazron** [comment]
I'm afraid you'll have to unpack the .ipa yourself, it's just a .zip file (so add a pre-process step). Currently we have #145 that will help a bit
