### ISSUE TITLE
Error when launch application in multi-user context

### ISSUE THREAD

**Issue by louisatome** [phonegap/ios-deploy#164]
I use the ios-deploy script with two different users. When i launch the script with the first user, it creates some files in the /tmp directory (fruitstrap-lldb-prep-cmds-${device_id} and fruitstrap_${device_id}.py). Then, when i try to launch the script with my second user, i get a SegFault error when it tries to create/write the already created temporary files.
The command i use : 
```
./ios-deploy --justlaunch -b myApp.app
```

**Comment by shazron** [comment]
I see where the error is, we could add a uid to the filename, but beyond that I think it might still conflict trying to deploy to the same device (not sure yet).

**Comment by louisatome** [comment]
And isn't that possible to remove these files at the end of the process?
At least catch the error and print an understandable error message would be better :)
