### ISSUE TITLE
Launch an app signed with a distribution certificate

### ISSUE THREAD

**Issue by Nos2015** [phonegap/ios-deploy#165]
Hi,

You can't launch an app with "iOS-deploy --juslaunch --debug --bundle nameapp.app" which is signed with a distribution certificate because you can't tell to device to approve the distribution certificate.
Is it possible to tell device to approve it automatically ? I don't know if it is possible.

Best regards,

Nos

**Comment by shazron** [comment]
Is this a user-interactive prompt on the device? If so, then no, it's not possible.

**Comment by shazron** [comment]
Not possible.
