### ISSUE TITLE
ios-deploy installing over both USB and WiFi

### ISSUE THREAD

**Issue by paulshapiro** [phonegap/ios-deploy#170]
Even though the device is detected over USB and installation is initiated and completed over USB, after installation and entry into the debug phase, ios-deploy will detect the device over WIFI subsequently install the app over the air, even though it had just done so over USB. This also seems to step on any attempt to engage the debugger over USB. This only happens when WiFi is turned on, on the device. Seems like a bug that a duplicate install would happen. Specifying the device identifier with -i doesn't change the outcome. ios-deploy -c only lists one device, connected via USB.

**Comment by adbl** [comment]
+1

**Comment by dhayab** [comment]
:+1:

**Comment by shazron** [comment]
Thanks for the report. Not sure how to debug this, I haven't seen this yet in my testing. Any particular command line flags?

Do you mean during one deploy, it tries to deploy twice when two interfaces are detected for a device?

**Comment by dhayab** [comment]
Hi @shazron, here is a log for a simple `ios-deploy -d -b package.app`: https://gist.github.com/dhayab/ed6eec9d47c4e1c71325. I can confirm that when WiFi is off on the device, the command works as expected.

**Comment by shazron** [comment]
Thank you! That helps a lot.

**Comment by shazron** [comment]
Thinking out loud...
On this line: https://gist.github.com/dhayab/ed6eec9d47c4e1c71325#file-gistfile1-txt-L29
There should be lines starting with the prefix "(lldb)" as the debugger is started, but it's starting a new Install Phase again.

I think the "Waiting for iOS device to be connected" phase was not terminated properly leading to this situation. Here we subscribe: https://github.com/phonegap/ios-deploy/blob/adc8a5b9c298d901d4388bb5cba20f9049b2dc83/ios-deploy.c#L1971 but there is no unsubscribe once a device connection was found.

**Comment by ptarjan** [comment]
+1 I'm hitting this as well.

Simply plugging in a device, turning on the WIFI and running 

```
ios-deploy -d -b ./platforms/ios/build/device/Trimian.app
```

It deploys once over USB then again over WIFI. If I turn off WIFI then do it again, it didn't work, then I waited a minute and did it again and magically it worked. Is there some registry of devices it hears over WIFI that takes a bit of time to purge? Similarly, if I just quickly turn on my WIFI I don't hit this bug, but if my WIFI was on for a while then I hit it.

**Comment by shazron** [comment]
Pushed a fix, will be out in v1.8.0. It's ugly but it'll do for now until a re-factor in v2.0

**Comment by shazron** [comment]
1.8.0 is out, please test and report if this is still a problem, thanks.

**Comment by paulshapiro** [comment]
@shazron hey there. I'm unfortunately still getting this problem with 1.8.0. Please help! Would it be possible to add a flag to simply completely turn off WiFi in ios-deploy as well? It would be a workaround while the bug itself is being diagnosed.

**Comment by paulshapiro** [comment]
When I turn off WiFi on the device, ios-deploy also apparently still thinks that the device is connected over WiFi, and tries to do the upload, but fails at AMDeviceValidatePairing(device) with a "This device is no longer connected." This causes ios-deploy to exit, and not launch the app that it has already installed over USB. Help appreciated.

**Comment by shazron** [comment]
Good idea for the flag. The trouble is I can't repro this to fix this properly, and will have to rely on you to test. I'll put it in a branch for you to test, and report back.

I'll add the flag `--no-wifi`

**Comment by shazron** [comment]
I just pushed 1.8.1 with more verbose logging. Add `--verbose` and post a log when this issue happens.

**Comment by paulshapiro** [comment]
@shazron I couldn't repro the issue after testing 1.8.1. I'm using --verbose though so if I see it again I'll have some logs for you.

Re: --no-wifi - I couldn't find that branch. Am I too early?
I'd really love to be able to disable wifi, as, when I disconnect USB, ios-deploy does still try to upload over Wifi, which can be an issue for bigger apps, and iosdeploy can't debug over wifi, etc.

**Comment by paulshapiro** [comment]
By the way, I think the 'installs over both usb and wifi' issue may be happening when I disconnect the device via USB, try to install w/o a USB connection (ios-deploy goes over wifi), and then reconnect and try installing again - it seems to install over both vectors. I'll have a log for you in a minute.

**Comment by paulshapiro** [comment]
Yes, it seems to install over USB first, and then install over wifi, but then fail to start to debug the app, as it is trying to do so over WiFi.

**Comment by paulshapiro** [comment]
Here's the log of me installing the app after having disconnected USB, tried to install (at which point it installs over wifi), and then reconnecting USB, and installing again. Note that it installs twice.


$ …/ios-deploy -t 10 -b …[app name].app/ -1 [bundle id] --verbose -L
 ios-deploy [INFO]: '[....] Waiting up to 10 seconds for iOS device to be connected'
 ios-deploy [INFO]: 'Handling device type: 1'
 ios-deploy [INFO]: 'Already found device? 0'
 ios-deploy [INFO]: 'Device Name: Paul's iPhone 5'
 ios-deploy [INFO]: 'Model Name: iPhone 6 Plus'
 ios-deploy [INFO]: '[....] Using iPhone 6 Plus 'Paul's iPhone 5' ([device udid]).
------ Install phase ------
[  0%] Found iPhone 6 Plus 'Paul's iPhone 5' ([device udid]) connected through USB, beginning install'
 ios-deploy [INFO]: '[  5%] Copying .../[app name].app/META-INF/ to device'
 ios-deploy [INFO]: '[  5%] Copying .../[app name].app/META-INF/com.apple.ZipMetadata.plist to device'
 ios-deploy [INFO]: '[  5%] Copying .../[app name].app/_CodeSignature/ to device'
 ios-deploy [INFO]: '[  5%] Copying .../[app name].app/_CodeSignature/CodeResources to device'
....... [copying some stuff] ....
[  7%] Copying .../[app name].app/embedded.mobileprovision to device
[  8%] Copying .../[app name].app/en.lproj/ to device
[  8%] Copying .../[app name].app/en.lproj/InfoPlist.strings to device
[  8%] Copying .../[app name].app/Fonts.bundle/ to device
..... [copying stuff] ......
[  9%] Copying .../[app name].app/Frameworks/ to device

..... [copying stuff] ......

 ios-deploy [INFO]: '[ 13%] Copying .../[app name].app/Images.bundle/ to device'

..... (copying a bunch of stuff)......

[ 48%] Copying .../[app name].app/Info.plist to device'
 ios-deploy [INFO]: '[ 49%] Copying .../[app name].app/[app name] to device'
 ios-deploy [INFO]: '[ 49%] Copying .../[app name].app/LaunchImage-700-568h@2x.png to device'
 ios-deploy [INFO]: '[ 49%] Copying .../[app name].app/PkgInfo to device'
 ios-deploy [INFO]: '[ 52%] CreatingStagingDirectory'
 ios-deploy [INFO]: '[ 57%] ExtractingPackage
[ 60%] InspectingPackage'
 ios-deploy [INFO]: '[ 60%] TakingInstallLock'
 ios-deploy [INFO]: '[ 65%] PreflightingApplication'
 ios-deploy [INFO]: '[ 65%] InstallingEmbeddedProfile'
 ios-deploy [INFO]: '[ 70%] VerifyingApplication'
 ios-deploy [INFO]: '[ 75%] CreatingContainer'
 ios-deploy [INFO]: '[ 80%] InstallingApplication'
 ios-deploy [INFO]: '[ 85%] PostflightingApplication'
 ios-deploy [INFO]: '[ 90%] SandboxingApplication'
 ios-deploy [INFO]: '[ 95%] GeneratingApplicationMap'
 ios-deploy [INFO]: '[100%] Installed package .../[app name].app/'
 ios-deploy [INFO]: 'Device Name: Paul's iPhone 5'
 ios-deploy [INFO]: 'Model Name: iPhone 6 Plus'
 ios-deploy [INFO]: '------ Debug phase ------
Starting debug of iPhone 6 Plus 'Paul's iPhone 5' ([device udid]) connected through USB...'
 ios-deploy [INFO]: 'Device support path: /Users/paulshapiro/Library/Developer/Xcode/iOS DeviceSupport/8.4 (12H143)'
 ios-deploy [INFO]: 'Developer disk image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/8.4 (12H141)/DeveloperDiskImage.dmg'
 ios-deploy [INFO]: '[  0%] Looking up developer disk image'
 ios-deploy [INFO]: '[ 95%] Developer disk image mounted successfully'
 ios-deploy [INFO]: '[100%] Connecting to remote debug server
-------------------------'
 ios-deploy [INFO]: 'Waiting for child [Child: 93759][Parent: 93737]'
 ios-deploy [INFO]: 'Handling device type: 2
Already found device? 1'
 ios-deploy [INFO]: '(lldb) command source -s 1 '/tmp/25AEF32F-7476-4527-900D-B9BA0D0F0BC7/fruitstrap-lldb-prep-cmds-[device udid]''
 ios-deploy [INFO]: 'Device Name: (null)
Model Name: Unknown Device'
 ios-deploy [INFO]: '[....] Using ([device udid]ss).
------ Install phase ------
[  0%] Found ([device udid]ss) connected through WIFI, beginning install'
 ios-deploy [INFO]: '[  5%] Copying .../[app name].app/META-INF/ to device'
 ios-deploy [INFO]: '[  5%] Copying .../[app name].app/META-INF/com.apple.ZipMetadata.plist to device
[  5%] Copying .../[app name].app/_CodeSignature/ to device
[  5%] Copying .../[app name].app/_CodeSignature/CodeResources to device'

......... [copying stuff] .......

 ios-deploy [INFO]: '[  7%] Copying .../[app name].app/embedded.mobileprovision to device'
 ios-deploy [INFO]: '[  8%] Copying .../[app name].app/en.lproj/ to device'
 ios-deploy [INFO]: '[  8%] Copying .../[app name].app/en.lproj/InfoPlist.strings to device

.......... [copying stuff] ........

 ios-deploy [INFO]: '[  9%] Copying .../[app name].app/Frameworks/ to device'

......... [copying stuff] .......

 ios-deploy [INFO]: '[ 13%] Copying .../[app name].app/Images.bundle/ to device'

......... [copying stuff] .......

 ios-deploy [INFO]: '[ 48%] Copying .../[app name].app/Info.plist to device
[ 49%] Copying .../[app name].app/[app name] to device'
 ios-deploy [INFO]: '[ 49%] Copying .../[app name].app/LaunchImage-700-568h@2x.png to device'
 ios-deploy [INFO]: '[ 49%] Copying .../[app name].app/PkgInfo to device'
 ios-deploy [INFO]: '[ 52%] CreatingStagingDirectory'
 ios-deploy [INFO]: '[ 57%] ExtractingPackage
[ 60%] InspectingPackage'
 ios-deploy [INFO]: '[ 60%] TakingInstallLock'
 ios-deploy [INFO]: '[ 65%] PreflightingApplication'
 ios-deploy [INFO]: '[ 65%] InstallingEmbeddedProfile'
 ios-deploy [INFO]: '[ 70%] VerifyingApplication'
 ios-deploy [INFO]: '[ 75%] CreatingContainer'
 ios-deploy [INFO]: '[ 80%] InstallingApplication'
 ios-deploy [INFO]: '[ 85%] PostflightingApplication'
 ios-deploy [INFO]: '[ 90%] SandboxingApplication'
 ios-deploy [INFO]: '[ 95%] GeneratingApplicationMap'
 ios-deploy [INFO]: '[100%] Installed package .../[app name].app/'
 ios-deploy [INFO]: 'Device Name: (null)'
 ios-deploy [INFO]: 'Model Name: Unknown Device'
 ios-deploy [INFO]: '------ Debug phase ------'
 ios-deploy [INFO]: 'Cannot debug ([device udid]ss) over WIFI.'
 ios-deploy task terminated with code 0 and reason 'exit'.

**Comment by paulshapiro** [comment]
@shazron Any way we might be able to expedite the --no-wifi flag? At the moment, this issue is occurring 100% of the time in most of my testing, and it thoroughly prevents ios-deploy from launching the app.

**Comment by tboyce12** [comment]
+1 on this issue.

**Comment by jgog** [comment]
Same here, the app is deployed over Wifi even though USB device is detected. When can we expect a fix for this?

**Comment by jgog** [comment]
Hey @shazron did you get a chance to take a look at this?

**Comment by jcworsley** [comment]
Hey all, just ran into this myself and submitted a fix in a pull request (https://github.com/phonegap/ios-deploy/pull/192) from my fork. Hope it helps someone.

**Comment by markghayden** [comment]
Also appear to be running into this problem.  I can confirm turning off wifi on the device serves as a work-around.

**Comment by shazron** [comment]
Merged #192 for 1.8.3 release (soon).

**Comment by shazron** [comment]
1.8.3 published, give it a go.

**Comment by Coder-256** [comment]
I was having a similar issue, but restarting the device fixed it.
