### ISSUE TITLE
Unable to mount developer disk image

### ISSUE THREAD

**Issue by Zorgatone** [phonegap/ios-deploy#174]
I'm developing an app using ionic/cordova.
After installing an XCode and Command line Tools update from App Store now I can't launch an app using ios-deploy anymore (I rebooted after the update).

I've tried all of these:

```
ionic run --device ios
cordova run --device ios
```

and also:
```
sudo ios-deploy -d -b "/Users/webdev1/Documents/ionic/testgeo/platforms/ios/build/device/Test Geolocalizzazione.app"
```

I also tried to reinstall node (removed io-js), and reinstall cordova, ionic, io-sim and ios-deploy. It didn't work.

The partial output with the error is:
```
100%] Installed package /Users/webdev1/Documents/ionic/testgeo/platforms/ios/build/device/Test Geolocalizzazione.app
------ Debug phase ------
Starting debug of iPhone 6 Plus 'iTom 6 Plus' (7ecd58fefc7f88e4f59e5ad13823ebb01be87e87) connected through USB...
[  0%] Looking up developer disk image
2015-09-18 10:11:49.744 ios-deploy[1809:12031] [ !! ] Unable to mount developer disk image. (e8000033)
```

I can test my application only using XCode for now.
I already checked that XCode has loaded the symbols correctly, I am now trying to update my iPhone 6 Plus from iOS 8.4.1 to iOS 9.0 and see if it works better.
The Deployment Target version is cordova's default: 6.0

My environment is:
```
TR:testgeo tommaso$ sw_vers -productVersion
10.10.5
TR:testgeo tommaso$ ios-deploy -V
1.7.0
TR:testgeo tommaso$ xcodebuild -version
Xcode 7.0
Build version 7A220
TR:testgeo tommaso$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
TR:testgeo tommaso$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
TR:testgeo tommaso$ lldb --version
lldb-340.4.70
```

**Comment by shazron** [comment]
Similar to #171

**Comment by shazron** [comment]
Check out this comment and do the first and second things I mentioned: https://github.com/phonegap/ios-deploy/issues/171#issuecomment-140471523

**Comment by Zorgatone** [comment]
Solved after another update and reboot

**Comment by louisatome** [comment]
I had the same problem after a ios-sdk update from 8.4 to 9.2 and a reboot of my test device fixed it.
Thanks!
