### ISSUE TITLE
No long starts deployed app

### ISSUE THREAD

**Issue by ptarjan** [phonegap/ios-deploy#175]
Using the command:

```
$ ios-deploy -b MyApp.ipa
```

It deploys successfully (as it always has) but no longer starts the app. I recently updated XCode so I'm not sure if that caused it, but something has changed to cause the app to no long start. It happily closes it if the app is already open, but doesn't re-open.

**Comment by shazron** [comment]
just a `-b` will install the app. To start the app as well, you have to use --justlaunch, or --debug. However, using those two flags will not launch an .ipa file, only the .app

**Comment by ptarjan** [comment]
Ok thanks. With those flags it worked.
