### ISSUE TITLE
Auto-detect iPhone 6S architecture

### ISSUE THREAD

**Issue by warrenseine** [phonegap/ios-deploy#177]
Deploying to an iPhone 5 from `ios-deploy` works fine.
Deploying to an iPhone 6S from `ios-deploy` fails (typical `undefined symbols` error). Note that deploying directly from Xcode works.

I can see from the error that `ios-deploy` is trying to build for `armv7`:

    ld: warning: ignoring file ../../libstuff.a, file was built for archive which is not the architecture being linked (armv7): ../../libstuff.a
    Undefined symbols for architecture armv7:
    ...

I think the correct architecture for the iPhone 6S should be `arm64`. Should `ios-deploy` auto-detect that? 

I'm using the command line: `ios-deploy --noninteractive --debug --bundle my.app`. Versions are Xcode 7 and `ios-deploy` 1.7.0 (from npm).

**Comment by shazron** [comment]
ios-deploy is a dumb deploy tool -- your binary must conform to the architecture of your device already. It just takes a binary and tries to deploy it to a device (and doesn't "build" anything). 

This feature is outside the scope of the tool.

**Comment by warrenseine** [comment]
You are right. Sorry for the invalid issue.

It may be some `xcodebuild` parameter issue.
