### ISSUE TITLE
deploy messages die partway through deploy

### ISSUE THREAD

**Issue by ptarjan** [phonegap/ios-deploy#180]
If I do:

```
ionic run ios --device
```

It compiles the app file and starts the deployment, but it dies at about `[30 %]`  and gives me my console back. It clearly is still running in the background because a few seconds later the app opens on my phone.

The main problem is I don't see the lldb console so I can't get messages that the app is printing.

**Comment by shazron** [comment]
I'd like to leave ionic out of it, since there may be other issues with their abstraction. I assume it works with straight ios-deploy? They might be using --justlaunch, so no debugging through lldb.

**Comment by ptarjan** [comment]
Yes, `ios-deploy` works great on its own. If I do:

```
killall lldb; ionic build ios --device; ios-deploy -d -b platforms/ios/build/device/Trimian.app
```

it doesn't die partway and happily opens up lldb.

**Comment by ptarjan** [comment]
I did a bit of debugging and I thought it was this line that was invoking `ios-deploy`

https://github.com/apache/cordova-ios/blob/89eac6c93b93cd1d98e74433d8ee2bdad4438c53/bin/templates/scripts/cordova/lib/run.js#L137

**Comment by ptarjan** [comment]
(Also, I can replace `ionic` with `cordova` and it is the same problem)

**Comment by shazron** [comment]
There it is -- the --justlaunch flag in cordova does not enable the debugger, it just installs, and launches the app. Doesn't seem to be an ios-deploy problem that I can see.

**Comment by ptarjan** [comment]
Ok, I'll push it upstream to `cordova-ios`.
