### ISSUE TITLE
"Unable to mount developer disk image" after using same device on machines with different Xcode versions

### ISSUE THREAD

**Issue by paulshapiro** [phonegap/ios-deploy#181]
Hi,

I noticed some other bug reports referencing the error, "Unable to mount developer disk image". I found that I began to see this error after updating to Xcode 7. My device uses iOS 8.4. When I first got the error under Xcode 7, I followed the possible solution of restarting my device, and ios-deploy began to succeed under Xcode 7. But when I switched to test on another machine which has Xcode 6, with the same device, I got the error again. Restarting the iOS device worked for that machine. But switching back to my original Xcode 7 machine, I got the error again. 

I've been using both 1.8.0 and 1.7.0, and so this issue is happening in 1.8.0 as well.

**Comment by shazron** [comment]
This might be an Xcode issue. I've noticed that if its the first time it encounters an iOS device version it hasn't encountered before, each Xcode installation will try to download the required binaries. You can see this in Xcode -> Devices usually.

**Comment by shazron** [comment]
Please re-open if this is still an issue.
