### ISSUE TITLE
ios-deploy terminates with code 11 in difficult to pinpoint circumstances

### ISSUE THREAD

**Issue by paulshapiro** [phonegap/ios-deploy#182]
This happens fairly frequently - maybe 40% of the time during my testing. The termination code is 11. Basically, the stdout indicates that ios-deploy is waiting for a device to be connected (I have a 10s timeout), and then immediately terminates with a code 11 - without trying to install the app.

Sometimes the error will occur repeatedly as I re-run ios-deploy. Sometimes it seems to go away by itself. Sometimes it goes away after I disconnect and reconnect the device.

**Comment by shazron** [comment]
Pushed 1.8.1 with a fix.

**Comment by paulshapiro** [comment]
Couldn't repro yet with 1.8.1.
