### ISSUE TITLE
ios-deploy 1.8.1 takes extremely long time to actually boot app, and if timeout is below that amount of time, it will kill the app

### ISSUE THREAD

**Issue by paulshapiro** [phonegap/ios-deploy#185]
Device is running iOS 9. Using ios-deploy 1.8.1. I tested multiple different applications.

I'm going like this:

    $ ios-deploy -r -t 30 -b Application.app/ -1 com.bundle_id --verbose -L

 It seems there is some extremely long delay running apps under iOS 9. What I see is :
1. the app installing, then 
2. an "(lldb)     run", then 
3."success (lldb)     safequit", 
4. Then after about 17 seconds, "Process 1481 stopped" and then "Process 1481 detached", and then
5. ios-deploy subsequently terminates with code 0, and the app actually launches.

The 17 second delay itself is a big issue, but without the 30 second timeout, the app gets killed, as the time for the app to launch passes the timeout. I actually had been chasing down crashes in my own code for hours to finally find that it was the timeout, after all.

Reproduction rate is 100% at this point. 

What I'm wondering about is why Xcode is able to launch the same app so quickly, but ios-deploy seems to have some sort of issue. Please let me know if I can provide any more info as this is a big issue on our side. Thanks a bunch.

**Comment by michaelcontento** [comment]
Same here - it would be nice if ios-deploy could operate as fast as xcode :)

**Comment by hackjustu** [comment]
Agree. This delay is pain.

**Comment by softBarbarian** [comment]
@shazron we are experiencing same behaviour. This started to occur after upgrade to cordova `6.0` and ios-deploy to `1.8.4`
Here is my info:
```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: 1.8.4 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2 Build version 7C68 
```

**Comment by westonganger** [comment]
+1

**Comment by WeiLee185** [comment]
+1

**Comment by sencenan** [comment]
+1

**Comment by LucasPekel87** [comment]
+1

**Comment by roblav96** [comment]
+1 wtf mate

**Comment by shazron** [comment]
1.8.6 published -- please test with that and report back. Thanks!
https://github.com/phonegap/ios-deploy/releases/tag/1.8.6

**Comment by roblav96** [comment]
@shazron oh awesome! thanks mate!

**Comment by shazron** [comment]
So does 1.8.6 fix the problem?

**Comment by shazron** [comment]
Closing since I think 1.8.6 fixes this. Re-open if you feel that it is not resolved.

**Comment by asemoon** [comment]
+1
