### ISSUE TITLE
cannot install ios-deploy without --unsafe-perm

### ISSUE THREAD

**Issue by feasibletrash0** [phonegap/ios-deploy#186]
sudo npm install -g ios-deploy

109 warn lifecycle ios-deploy@1.8.2~preinstall: cannot run in wd %s %s (wd=%s) ios-deploy@1.8.2 ./src/check_reqs.js && xcodebuild /usr/local/lib/node_modules/.staging/ios-deploy-fbfd9f76b9a8909271fae167aab47715
133 error Darwin 14.1.0
134 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
135 error node v4.1.2
136 error npm  v3.3.6
137 error path /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy
138 error code ENOENT
139 error errno -2
140 error syscall chmod
141 error enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
141 error enoent This is most likely not a problem with npm itself
141 error enoent and is related to npm not being able to find a file.
142 verbose exit [ -2, true ]

**Comment by lqixv** [comment]
i have the same error.
uninstall nodejs v5.0.0, then install nodejs v4.2.2, then it works.

**Comment by ahmetabdi** [comment]
+1

**Comment by christiansakai** [comment]
+1 using nodejs 4.1.2 has this error too

**Comment by Clark-W-Griswold** [comment]
yay! (+1)

**Comment by jumong** [comment]
+1

**Comment by akapei** [comment]
Per [ios-deploy](https://github.com/phonegap/ios-deploy):

>*If you are not using a node version manager like nvm or n, you may have to do either of these two things below when under El Capitan:*

  >1. Add the --unsafe-perm flag when installing ios-deploy
  >2. Ensure the nobody user has write access to /usr/local/lib/node_modules/ios-deploy/ios-deploy

Adding <code>--unsafe--perm</code> worked for me.

Should look like: <code>sudo npm install -g ios-deploy --unsafe-perm</code>

**Comment by TengfeiQi** [comment]
+1

**Comment by Zorgatone** [comment]
:+1:

**Comment by Zorgatone** [comment]
Please fix support for latest `iOS 9.1` and `OS X El Capitan`

**Comment by ihor-sviziev** [comment]
:+1:

**Comment by airasheed** [comment]
`sudo npm install -g ios-deploy --unsafe-perm` worked for me

**Comment by muvaffak** [comment]
`--unsafe-perm` worked for me, too

**Comment by shazron** [comment]
Please see the README for the --unsafe-perm workaround. This is if you installed node using root (usually from the nodejs website). If you used `n` or `nvm` it will install node to your local user and thus you won't need to use sudo for anything, and you should be able to install without using the flag.

**Comment by landolfo** [comment]
@akapei You made my day. Thank you

**Comment by VGerris** [comment]
I found somewhere that running it without sudo works too and it did for me.
I did not try an actual deploy to a device so not sure it did the trick but the install works fine.
