### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by biniama** [phonegap/ios-deploy#188]
As I read from the documentation, I don't need XCode, right?
Do I need to have Apple Developer subscription?

Please help.

[~]$ sudo npm install -g ios-deploy
/
> ios-deploy@1.8.2 preinstall /usr/local/lib/node_modules/ios-deploy
> ./src/check_reqs.js && xcodebuild

stderr: xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! ios-deploy@1.8.2 preinstall: `./src/check_reqs.js && xcodebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ios-deploy@1.8.2 preinstall script './src/check_reqs.js && xcodebuild'.
npm ERR! This is most likely a problem with the ios-deploy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./src/check_reqs.js && xcodebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ios-deploy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/myname/npm-debug.log
[~]$

**Comment by ideagay** [comment]
I am also block with the problem

**Comment by The18thWarrior** [comment]
I also have this block.

**Comment by cbabos** [comment]
For deploying to store you will still need XCode. As the project description says: 
_Install and debug iPhone apps from the command line, without using Xcode_

So you don't have to run(!) XCode (as application) for these tasks: 
 - compile your project
 - deploy to your own device (which is connected to your mac)

So this isn't a bug, just (maybe) a bit unclear description.

**Comment by shazron** [comment]
Thanks for the reports, everyone. I'll have to test this on a vm with just the Command Line Tools, will let you know

**Comment by pbakondy** [comment]
Same error here.

```
sudo npm install -g ios-deploy

npm WARN lifecycle ios-deploy@1.8.3~preinstall: cannot run in wd %s %s (wd=%s) ios-deploy@1.8.3 ./src/check_reqs.js && xcodebuild /usr/local/lib/node_modules/.staging/ios-deploy-fbfd9f76b9a8909271fae167aab47715
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! path /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

```

Local package install works. Git clone and manual xcodebuild also works.


[npm-debug.log.txt](https://github.com/phonegap/ios-deploy/files/42949/npm-debug.log.txt)

**Comment by Barryrowe** [comment]
Just adding more info.

I had the same issues. My global .npm-packages folder doesn't live in a root-owned location so I was having problems running: 

    /**Failed**/
    npm install -g ios-deploy

I got the prompt that I needed to run with sudo so that El Capitan would allow me to accept the permissions. If I ran that I got the same error as @pbakondy  shows

I then tried running with the --unsafe-perm flag like the docs say:

    /**Failed**/
    npm install -g ios-deploy --unsafe-perm

What the docs DON'T say (and I may submit a PR to fix) is that --unsafe-perm requires a value, so it should be:

    /**Worked for me**/
    npm install -g ios-deploy --unsafe-perm=true

That solved the problem for me.

**Comment by ekoome** [comment]
@Barryrowe solution worked for me as well.

**Comment by shazron** [comment]
```
unsafe-perm
Default: false if running as root, true otherwise
Type: Boolean
Set to true to suppress the UID/GID switching when running package scripts. If set explicitly to false, then installing as a non-root user will fail.
```
@Barryrowe this would imply that you were running as root (since unsafe-perm appeared to be false for you). In any case, documenting it to be explicit 'true' would be best

**Comment by HugoHeneault** [comment]
Thanks for the solution. But why is this happening?

**Comment by Barryrowe** [comment]
@shazron  that's interesting. I was running as a user with Admin privileges, and I wonder if that's now seen as 'root' under El Capitan. 

@HugoHeneault I'm just taking a wild guess that in El Capitan any user with Admin privileges is now seen as "root" by npm since they "removed the root user" in the OS update.

**Comment by 5ohDave** [comment]
You can also add the --allow-root flag to the end of the installation command to make this (and similar) npm installs work

**Comment by askadu** [comment]
Thanks @Barryrowe  its worked for me.

**Comment by biniama** [comment]
@Barryrowe 's solution worked.
`npm install -g ios-deploy --unsafe-perm=true`

**Comment by rudamaia** [comment]
same problem here, tried everything already...

[npm-debug.txt](https://github.com/phonegap/ios-deploy/files/64256/npm-debug.txt)

npm install -g ios-deploy --unsafe-perm=true
/
> ios-deploy@1.8.3 preinstall /usr/local/lib/node_modules/ios-deploy
> ./src/check_reqs.js && xcodebuild

stderr: xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "ios-deploy" "--unsafe-perm=true"
npm ERR! node v0.10.35
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! ios-deploy@1.8.3 preinstall: `./src/check_reqs.js && xcodebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ios-deploy@1.8.3 preinstall script './src/check_reqs.js && xcodebuild'.
npm ERR! This is most likely a problem with the ios-deploy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./src/check_reqs.js && xcodebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ios-deploy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rudamaia/npm-debug.log

**Comment by biniama** [comment]
The error tells you 'requires Xcode'. Do you have XCode installed? If no, you need to install it and open it for the installation to work. You don't have to use it but you need to install it.

**Comment by rudamaia** [comment]
Yes, its installed:
xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by rudamaia** [comment]
Well... somehow the xcode was installed but in App Store it wasnt. Reinstalled by the App Store and it fixed the error! thanks @biniama

**Comment by RobertChristopher** [comment]
@Barryrowe Worked for me, thanks.

**Comment by merebrownie** [comment]
I was having this issue and found that I had installed Xcode, but never actually ran the program. Upon opening the program, additional components were installed and I was able to install ios-deploy successfully.

**Comment by adamjarling** [comment]
@Barryrowe Worked for me also.  Many thanks.

**Comment by geniltodallo** [comment]
sudo npm install -g ios-deploy --no-bin-links
worked for me...

**Comment by yugasun** [comment]
This fixed it for me:

1. Install Xcode
2. Run sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

See this explanation on SO.

**Comment by mskornyakova** [comment]
** ERR **
npm install -g ois-deploy --unsafe-perm=true

** Build Succeeded **
sudo npm install -g ois-deploy --unsafe-perm=true

**Comment by HugoHeneault** [comment]
@mskornyakova ⚠️ You shouldn't run npm with sudo rights. You don't want some scripts you don't know to have administrators rights on your system...
