### ISSUE TITLE
ios-deploy --justlaunch hangs

### ISSUE THREAD

**Issue by hackjustu** [phonegap/ios-deploy#189]
`ios-deploy --justlaunch --debug --bundle my.app` hangs when launching the app. The iOS app did open a new windows but the `viewDidAppear()` method was not called. (We didn't put any custom codes before `viewDidAppear()`.)

We spawned a child process to run the ios-deploy. The ios-deploy and lldb sometimes(not always) didn't exit even though we put the `--justlaunch` flag. The weird thing is the command works fine if it is executed directly on the terminal.

ios-deploy: 1.82
iOS: 8.4
OSX: 10.10

**Updated:**
It might be the same problem here: https://github.com/phonegap/ios-deploy/issues/163 . So what's the difference between running the ios-deploy as a child process and running it directly in the terminal?

**Comment by shazron** [comment]
Honestly I'm not sure. Perhaps a ulimit issue. http://ss64.com/bash/ulimit.html

**Comment by hackjustu** [comment]
@shazron  After a stress test for launching the iOS app for more than 1000 times, we found out that if the `lldb` fails to launch the app in the python `run` method, it will still move forward to the `safequit` method, where it keeps polling the `SBProcess` state and always gets `eStateLaunching`, which traps the process in an infinite loop.

That's the reason why it hangs. I would suggest some enhancement in the `run_command` method, so that it only moves forward only if it gets `success` in the `lldb.SBError()`. I'll submit a pull request later which could better illustrate what I mean.

**Comment by shazron** [comment]
1.8.6 published -- please test with that and report back. Thanks!
https://github.com/phonegap/ios-deploy/releases/tag/1.8.6

**Comment by shazron** [comment]
Closing since I think 1.8.6 fixes this. Re-open if you feel that it is not resolved.
