### ISSUE TITLE
ios-deploy path problem with npm prefix?

### ISSUE THREAD

**Issue by dac09** [phonegap/ios-deploy#191]
Hi, 

Output as requested:
```
$ sw_vers -productVersion
10.10.5

$  ios-deploy -V
1.8.2

$ xcodebuild -version
Xcode 7.1
Build version 7B91b

$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

$ lldb --version
lldb-340.4.110
```

I've not been able to run `cordova run ios --device` or `cordova requirements ios` successfully as it complains ios-deploy is not installed, even though I can use it from command line. I have my global npm modules install to ~/.npm and have ~/.npm/bin in my $PATH.

I did a quick check, and trying to ios-deploy from a bash script always fails (along with `which ios-deploy`). Turns out adding a simlink from /usr/local/bin/ios-deploy -> ~/.npm/bin/ios-deploy seems to have solved this issue. Is there something different happening during the installation procedure? ios-sim and most other tools don't seem affected. Either way I hope this helps someone.

FYI, I'm using https://github.com/tj/n and I set the install directory with an npm config `prefix = "/Users/userOne/.npm" `

**Comment by shazron** [comment]
Definitely not using anything special for installation as you can see from the package's package.json. I've a hunch its more of an npm thing somehow.

**Comment by shazron** [comment]
Resolving this (please reopen if there is more info) since I don't think its an ios-deploy issue (per my last comment)
