### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by siuying** [phonegap/ios-deploy#194]
ios-deploy just crash when I try to download file

```
ios-deploy --download=/Logs --bundle_id the_app --to ./Downloads/Logs
[....] Waiting for iOS device to be connected
[....] Using iPhone 6 Plus 'Halley' (.....).
Segmentation fault: 11
```

```
ios-deploy -l --bundle_id the_app
[....] Waiting for iOS device to be connected
[....] Using (...).
Segmentation fault: 11
```

**Comment by siuying** [comment]
That was the master branch, the 2.x branch will not crash.

**Comment by fxfactorial** [comment]
A segfault with no stack info or even core dump is pretty useless.

**Comment by siuying** [comment]
True, please find a crash log at: http://cl.ly/34290y1Z2X2k

Same crash with install using ``npm install -g ios-deploy`` in a different machine.

**Comment by shazron** [comment]
Thanks!
Pasted it here: https://gist.github.com/shazron/fb950a19e6a715bbbdc4

**Comment by shazron** [comment]
Looks like the macro stringification of the method call is failing I think here:
https://github.com/phonegap/ios-deploy/blob/922f8483a78b1904c020b8c22058de204e4e32ca/src/ios-deploy.c#L198

If it was a C String it would work, but the format string is an Obj-C string here

**Comment by shazron** [comment]
Sorry - red herring, that's not it.

**Comment by shazron** [comment]
Found it - https://github.com/phonegap/ios-deploy/blob/922f8483a78b1904c020b8c22058de204e4e32ca/src/ios-deploy.c#L1269
bundle_id is not an Obj-C string.
