### ISSUE TITLE
npm install always error

### ISSUE THREAD

**Issue by caoliuxue** [phonegap/ios-deploy#195]
No matter I use "sudo npm install -g ios-deploy" or "sudo npm install -g https://github.com/phonegap/ios-deploy.git", I always get the below error:

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "https://github.com/phonegap/ios-deploy.git"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! path /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

can anybody tell me why?Thanks a billion

**Comment by caoliuxue** [comment]
This is the log file, hope it provide some useful info.
[npm-debug.txt](https://github.com/phonegap/ios-deploy/files/59192/npm-debug.txt)

**Comment by kukikiloke** [comment]
you may want to run it with the `--unsafe-perm` flag

**Comment by caoliuxue** [comment]
After commit this issue, I go back to the issue list and found lots of other issues like this and it looks like some guys already got a walk around solution.Just close it
