### ISSUE TITLE
Error 0xe8000007: The argument is invalid. AMDeviceSecureTransferPath ...

### ISSUE THREAD

**Issue by rayshan** [phonegap/ios-deploy#196]
Hello,

We're hitting this error after renaming the app ID, but not the app name, in `config.xml`. We're able to open the project in XCode and deploy to an iPhone there. This is the command we run:

`cordova run ios --device --debug --buildConfig=build.json`

`build.json` has `ios.debug.codeSignIdentitiy` and `ios.debug.provisioningProfile` defined per what's in Keychain and XCode.

This is the end of the log:

```
2015-12-15 17:49:25.845 ios-deploy[97183:14967484] [ !! ] Error 0xe8000007: The argument is invalid. AMDeviceSecureTransferPath(0, device, url, options, transfer_callback, 0)
Error code 253 for command: ios-deploy with args: -d,-b,/Users/rayshan/=Projects=/montage/contour/contour-app/platforms/ios/build/device/Contour App.app
ERROR running one or more of the platforms: Error: /Users/rayshan/=Projects=/montage/contour/contour-app/platforms/ios/cordova/run: Command failed with exit code 2
You may not have the required environment or OS to run this project
```

Additional debug info:
1. sw_vers -productVersion
10.11.2
2. ios-deploy -V
1.8.3
3. xcodebuild -version
Xcode 7.2
Build version 7C68
4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
5. gcc --version
onfigured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
6. lldb --version
lldb-340.4.119

Help please?

**Comment by brianjfox** [comment]
Did you ever find a resolution?  I'm running into this myself.

**Comment by rayshan** [comment]
Not yet. The workaround is open project in XCode and deploy from there, instead of using the Cordova CLI.

**Comment by shazron** [comment]
@rayshan I'm thinking it's because of a space in the app name.

**Comment by brianjfox** [comment]
Not in my case - one word, 10 alpha characters.

> On Jan 4, 2016, at 5:43 PM, Shazron Abdullah <notifications@github.com> wrote:
> 
> @rayshan <https://github.com/rayshan> I'm thinking it's because of a space in the app name.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/phonegap/ios-deploy/issues/196#issuecomment-168865766>.
> 

Thanks,

Brian
--
Brian J. Fox
Founder/CEO
Opus Logica, Inc.
A: 901 Olive St., 93101
O: 76-BAFFLE-76
C: 805.637.8642

**Comment by rayshan** [comment]
Hi @shazron, I don't believe so. We always had the app name as `Contour App` and it worked prior to the `id` change. The `id` was changed from `com.konturlabs.contour-app` to `com.konturlabs.contourapp`.

**Comment by shazron** [comment]
@rayshan trying to repro with a new project (deploy, rename id, then deploy again -- nothing so far). What version of cordova are you on?

**Comment by shazron** [comment]
@rayshan Can't even get to your initial state:
```
$ cordova create "Contour App" com.konturlabs.countour-app "Contour App"
Error: App id contains a reserved word, or is not a valid identifier.
```

**Comment by shazron** [comment]
Still no repro - but then I'm using a wildcard provisioning profile. Now I think I know what is happening (in hindsight) -- of course a provisioning profile is tied to a particular bundle id, so when you renamed it you had to create a new p.p. 

Check that this is the case.

**Comment by rayshan** [comment]
So we didn't create a new provisioning profile, but rather changed the App ID it's tied to. Apple Developer portal allows this:

![screen shot 2016-01-07 at 3 35 16 pm](https://cloud.githubusercontent.com/assets/3760840/12186087/658bef88-b554-11e5-8ca1-1863d10f0b80.png)

And yes my personal certificate and my personal device are selected. We did the same thing of changing App ID for the iOS Distribution provisioning profile. Both profiles resulted in the error mentioned in the first post.

I don't have a cable handy at the moment. Tomorrow I'll try to create a brand new provisioning profile to see if I can deploy to my hardware via CLI.

**Comment by shazron** [comment]
This is definitely an error in either the p.p, cert that signed the app etc and is not an error in ios-deploy itself -- AMDeviceSecureTransferPath always fails if something is not kosher. It could be that Cordova is not getting the combination of settings right because of your bundle-id change since you can deploy using Xcode and its possible that it's a bug in Cordova itself.

If you can build using Xcode and deploy to device, in the Project Navigator, click on the Product group, select the product .app, right-click and 'Show in Finder'. Try to deploy that .app using ios-deploy.

Paste your build log when you built it for device (use --verbose) in a github gist.
