### ISSUE TITLE
Unable to install/update ios-deploy

### ISSUE THREAD

**Issue by gnasit** [phonegap/ios-deploy#198]
i did the following command:
sudo npm install -g ios-deploy and i got the screen shot. Attached is also the log file.
[npm-debug.log.zip](https://github.com/phonegap/ios-deploy/files/75153/npm-debug.log.zip)

![screen shot 2015-12-30 at 2 18 43 pm](https://cloud.githubusercontent.com/assets/16493338/12056856/3ded3f62-af01-11e5-970c-757b0a5e03a2.png)

bash-3.2$ sw_vers -productVersion
10.11.1
bash-3.2$ ios-deploy -V
bash: ios-deploy: command not found
bash-3.2$ xcodebuild -version
Xcode 7.2
Build version 7C68
bash-3.2$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
bash-3.2$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
bash-3.2$ lldb --version
lldb-340.4.119
bash-3.2$ 
[npm-debug.log.zip](https://github.com/phonegap/ios-deploy/files/75156/npm-debug.log.zip)

**Comment by pbakondy** [comment]
see #188

**Comment by shazron** [comment]
Documented under the README under "El Capitan"
