### ISSUE TITLE
Issue installing ios-deploy

### ISSUE THREAD

**Issue by brendenmartin05** [phonegap/ios-deploy#199]
Hi All, 

I am having issues with installing npm install -g ios-sim ios-deploy. 

I am getting the following errors. 

npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "ios-sim" "ios-deploy"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! ios-deploy@1.8.3 preinstall: `./src/check_reqs.js && xcodebuild`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the ios-deploy@1.8.3 preinstall script './src/check_reqs.js && xcodebuild'.
npm ERR! This is most likely a problem with the ios-deploy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./src/check_reqs.js && xcodebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ios-deploy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/brenden/Applications/npm-debug.log 

applications  sw_vers -productVersion
10.11.2
➜  applications  ios-deploy -V
zsh: command not found: ios-deploy
➜  applications  xcodebuild -version
Xcode 7.2
Build version 7C68
➜  applications   xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
➜  applications  gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
➜  applications  lldb --version
lldb-340.4.119

**Comment by shazron** [comment]
See if this "El Capitan" section helps: https://github.com/phonegap/ios-deploy#os-x-1011-el-capitan

**Comment by brendenmartin05** [comment]
Awesome! That works.
