### ISSUE TITLE
NPM doesn't seem to finish creating directories

### ISSUE THREAD

**Issue by mehmetcodes** [phonegap/ios-deploy#202]
Now I've updated npm
npm install npm@latest -g

/Users/tmo/.node/bin/npm -> /Users/tmo/.node/lib/node_modules/npm/bin/npm-cli.js

npm@3.5.2 /Users/tmo/.node/lib/node_modules/npm

And I have different output

npm WARN lifecycle ios-deploy@1.8.3~preinstall: cannot run in wd %s %s (wd=%s) ios-deploy@1.8.3 ./src/check_reqs.js && xcodebuild /Users/tmo/.node/lib/node_modules/.staging/ios-deploy-e026eaf1

npm ERR! Darwin 15.0.0

npm ERR! argv "/usr/local/bin/node" "/Users/tmo/.node/bin/npm" "install" "-g" "ios-deploy"

npm ERR! node v4.2.3

npm ERR! npm  v3.5.2

npm ERR! path /Users/tmo/.node/lib/node_modules/ios-deploy/build/Release/ios-deploy

npm ERR! code ENOENT

npm ERR! errno -2

npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/tmo/.node/lib/node_modules/ios-deploy/build/Release/ios-deploy'

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/tmo/.node/lib/node_modules/ios-deploy/build/Release/ios-deploy'

npm ERR! enoent This is most likely not a problem with npm itself

npm ERR! enoent and is related to npm not being able to find a file.

[CONTRIBUTING.txt](https://github.com/phonegap/ios-deploy/files/78815/CONTRIBUTING.txt)

**Comment by shazron** [comment]
See if the El Capitan section here helps you: https://github.com/phonegap/ios-deploy#os-x-1011-el-capitan

**Comment by shazron** [comment]
Assuming the El Capitan section worked for you. Closing.

**Comment by mehmetcodes** [comment]
It did, thank you!
