### ISSUE TITLE
ERROR while using ionic iOS-deploy

### ISSUE THREAD

**Issue by KPHarsha** [phonegap/ios-deploy#203]
ios-deploy@1.8.4 preinstall: `./src/check_reqs.js && xcodebuild`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the ios-deploy@1.8.4 preinstall script './src/check_reqs.js && xcodebuild'.
npm ERR! This is most likely a problem with the ios-deploy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./src/check_reqs.js && xcodebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ios-deploy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/baryons/myfirstIOS/npm-debug.log

[npmLog.txt](https://github.com/phonegap/ios-deploy/files/82698/npmLog.txt)

**Comment by shazron** [comment]
I don't suppose you read https://github.com/phonegap/ios-deploy/blob/master/CONTRIBUTING.md in that email I instructed you? See "Filing an Issue".

In it, it tells you to check out: https://github.com/phonegap/ios-deploy#os-x-1011-el-capitan

**Comment by KPHarsha** [comment]
Yup.
Thanks for the response.
Will go through the link  & get back.

**Comment by kamok** [comment]
To save some time: 

```
OS X 10.11 El Capitan or greater

If you are not using a node version manager like nvm or n, you may have to do either of these three things below when under El Capitan:

Add the --unsafe-perm=true flag when installing ios-deploy
Add the --allow-root flag when installing ios-deploy
Ensure the nobody user has write access to /usr/local/lib/node_modules/ios-deploy/ios-deploy
```

**Comment by Vatia13** [comment]
sudo npm install -g ios-deploy --unsafe-perm=true --allow-root
