### ISSUE TITLE
iOS 9.3 beta

### ISSUE THREAD

**Issue by Zorgatone** [phonegap/ios-deploy#207]
I installed iOS 9.3 beta and I had to download and use the Xcode beta to install my apps..

Is it possible to run apps on iOS 9.3 with ios-deploy? Can I point that to use Xcode beta instead of Xcode?

**Comment by shazron** [comment]
I don't see why not. Make sure under Xcode -> Devices, select your device and see if it copies the symbols first and/or enable it for development

**Comment by Zorgatone** [comment]
I mean, I know how to use Xcode. I'm asking if you can do the same without
opening Xcode (i.e. Using ios-deploy for iOS 9.3 beta)
>
>
If I use iOS-deploy it won't work (just devices without iOS beta)

**Comment by shazron** [comment]
No one is questioning your Xcode manhood here, calm down.
What I mentioned is essential, if the symbols are not copied, ios-deploy will not work so you have to do that. I think you missed that point, and you need to use Xcode to verify.

ios-deploy doesn't care about what Xcode you use, it just takes a .app and tries to deploy it. One of the pre-reqs is the symbols need to be there (my previous instructions).

**Comment by Zorgatone** [comment]
Yeah I figured what you meant. And yeah I've used this device already and
the symbols are there :)
