### ISSUE TITLE
sudo npm install -g ios-deploy not working/errors

### ISSUE THREAD

**Issue by SarHH** [phonegap/ios-deploy#210]
Hi,

I have OSX Yosemite (version 10.10.5). I have tried to run "sudo npm install -g ios-deploy" multiple times but keep on getting errors. I uninstalled xcode twice and reinstalled it from the app store twice and still getting these same errors below in the terminal. Please help!

![screen shot 2016-02-05 at 3 56 13 am](https://cloud.githubusercontent.com/assets/16751176/12855073/6387223e-cc0b-11e5-9c60-0023c0d86a4f.png)

**Comment by 07Gond** [comment]
I have errors in the installing too. ¿How do you **solved it**?

**Comment by SarHH** [comment]
Hi, I ran "npm install -g ios-deploy --unsafe-perm", not clear why it worked but it did -- build succeeded. (note, I uninstalled and reinstalled xcode 3 times from the app store because there were issues there, I made sure to also open up xcode and make sure everything was installed and create a new project before putting this into the terminal). Hope that helps!
