### ISSUE TITLE
iPhone wrong behaviour after deploying app via ios-deploy

### ISSUE THREAD

**Issue by marmbah** [phonegap/ios-deploy#211]
Hi guys!

In the latest time i have some troubles with ios-deploy. Sometimes the apps weren't tapable after deployment. Also when I put the phone in sleep mode, i am not able to bring it back from this state. Only reset (home button + sleep button) brings the phone back to work. The console output shows no error.

I am using a iPhone 5s (8.0.2) and iPhone 6 (8.0).

Console output:
`[100%] Installed package app/payload/GuiiOS.app
------ Debug phase ------
Starting debug of iPhone 5s (Global/CDMA) 'bethandy071' (cd53cbe0591f70879c913b01ad15fdfc805582dd) connected through USB...
[  0%] Looking up developer disk image
[ 95%] Developer disk image mounted successfully
[100%] Connecting to remote debug server
-------------------------
(lldb) command source -s 0 '/tmp/C7C852AF-9E7F-4DDF-80AB-4E032EDE7661/fruitstrap-lldb-prep-cmds-cd53cbe0591f70879c913b01ad15fdfc805582dd'
Executing commands in '/tmp/C7C852AF-9E7F-4DDF-80AB-4E032EDE7661/fruitstrap-lldb-prep-cmds-cd53cbe0591f70879c913b01ad15fdfc805582dd'.
(lldb)     platform select remote-ios --sysroot '/Users/bahadmin/Library/Developer/Xcode/iOS DeviceSupport/8.0.2 (12A405)/Symbols'
  Platform: remote-ios
 Connected: no
  SDK Path: "/Users/bahadmin/Library/Developer/Xcode/iOS DeviceSupport/8.0.2 (12A405)/Symbols"
(lldb)     target create "/Users/bahadmin/workspace/Deploy - iOS app/MobileAppRegression/tools/scripts/ios-deploy/app/payload/GuiiOS.app"
Current executable set to '/Users/bahadmin/workspace/Deploy - iOS app/MobileAppRegression/tools/scripts/ios-deploy/app/payload/GuiiOS.app' (arm64).
(lldb)     script fruitstrap_device_app="/private/var/mobile/Containers/Bundle/Application/58698D91-B0C1-460F-8D4B-8D89961DC257/GuiiOS.app"
(lldb)     script fruitstrap_connect_url="connect://127.0.0.1:55643"
(lldb)     command script import "/tmp/C7C852AF-9E7F-4DDF-80AB-4E032EDE7661/fruitstrap_cd53cbe0591f70879c913b01ad15fdfc805582dd.py"
(lldb)     command script add -f fruitstrap_cd53cbe0591f70879c913b01ad15fdfc805582dd.connect_command connect
(lldb)     command script add -s asynchronous -f fruitstrap_cd53cbe0591f70879c913b01ad15fdfc805582dd.run_command run
(lldb)     command script add -s asynchronous -f fruitstrap_cd53cbe0591f70879c913b01ad15fdfc805582dd.autoexit_command autoexit
(lldb)     command script add -s asynchronous -f fruitstrap_cd53cbe0591f70879c913b01ad15fdfc805582dd.safequit_command safequit
(lldb)     connect
(lldb)     run
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: SUCCESS`

**Comment by advantiss** [comment]
Vote UP.
The same behavior on iPhone4s(CDMA) when I ran with "-u --justlaunch --verbose"

**Comment by Bouzmine** [comment]
+1

**Comment by shazron** [comment]
There might be issues with ios-deploy and/or lldb not being killed (for some reason).
Try a `killall lldb` then `killall ios-deploy` before testing.

Also, 1.8.6 is published -- please test with that and report back. Thanks!
https://github.com/phonegap/ios-deploy/releases/tag/1.8.6

**Comment by shazron** [comment]
Closing since I think 1.8.6 fixes this. Re-open if you feel that it is not resolved.
