### ISSUE TITLE
App crashing on launch screen due to taking longer than 20 seconds

### ISSUE THREAD

**Issue by hoihoi8** [phonegap/ios-deploy#213]
Hi :) On some of our devices, the app is exiting on launch. It is failing because of the 20 second launch time limit. When opening the app manually I do not get this crash. It appears iOS deploy is pushing the app launch over 20 seconds.

http://stackoverflow.com/questions/26827809/app-rejection-crash-report-says-failed-to-scene-create-in-time-badf00d-what

**Failing devices:**
iPhone 6 with 9.2.1 (13D15)
iPhone 6+ with 8.3 (12F70)
iPhone 6s+ with 9.2 (13C75)
iPhone 5 with 9.1 (13B143)

**Working Devices:**
iPhone 5 with 8.4 (12H143)
iPad Mini 3 with 8.4.1 (12H321)
iPhone 5 with 8.4 (12H143)

OS X El Capitan 10.11.3 (15D21)
XCode Version 7.2.1 (7C1002)

**ios-deploy commands:**
ios-deploy version 1.8.5

echo "uninstall game"
$iosDeployPath --uninstall --noinstall -t 60 --bundle $BuildPath --id $DeviceId
sleep 10
	
echo "install game"
$iosDeployPath -t 60 --bundle $BuildPath --id $DeviceId

echo "start game"
$iosDeployPath --justlaunch --noinstall --bundle $BuildPath --id $DeviceId

**What I think is causing the crash:**
Feb 18 18:00:05 iPhone SpringBoard[58] <Warning>: Forcing crash report of <FBApplicationProcess: 0x1314bd3f0; myApp; pid: 390> (reason: 1, description: com.myApp failed to scene-create after 3.88s (launch took 16.12s of total time limit 20.00s))

**Full output:**
Here is the standard output of the command:
[....] Waiting up to 60 seconds for iOS device to be connected
[....] Using iPhone 6 (GSM) 'iPhone' (c5916c52ff72ab85b3374c8b7c2c6fc103c76361).
------ Debug phase ------
Starting debug of iPhone 6 (GSM) 'iPhone' (c5916c52ff72ab85b3374c8b7c2c6fc103c76361) connected through USB...
[  0%] Looking up developer disk image
[ 95%] Developer disk image mounted successfully
[100%] Connecting to remote debug server

(lldb) command source -s 0 '/tmp/fruitstrap-lldb-prep-cmds-c5916c52ff72ab85b3374c8b7c2c6fc103c76361'
Executing commands in '/tmp/fruitstrap-lldb-prep-cmds-c5916c52ff72ab85b3374c8b7c2c6fc103c76361'.
(lldb)     platform select remote-ios --sysroot '/Users/<name>/Library/Developer/Xcode/iOS DeviceSupport/9.2.1 (13D15)/Symbols'
  Platform: remote-ios
 Connected: no
  SDK Path: "/Users/<name>/Library/Developer/Xcode/iOS DeviceSupport/9.2.1 (13D15)/Symbols"
(lldb)     target create "/Users/<name>/Downloads/myApp.app"
Current executable set to '/Users/<name>/Downloads/myApp.app' (arm64).
(lldb)     script fruitstrap_device_app="/private/var/mobile/Containers/Bundle/Application/F931A747-6900-45B6-9E47-4D5330361A8F/myApp.app"
(lldb)     script fruitstrap_connect_url="connect://127.0.0.1:51642"
(lldb)     command script import "/tmp/fruitstrap_c5916c52ff72ab85b3374c8b7c2c6fc103c76361.py"
(lldb)     command script add -f fruitstrap_c5916c52ff72ab85b3374c8b7c2c6fc103c76361.connect_command connect
(lldb)     command script add -s asynchronous -f fruitstrap_c5916c52ff72ab85b3374c8b7c2c6fc103c76361.run_command run
(lldb)     command script add -s asynchronous -f fruitstrap_c5916c52ff72ab85b3374c8b7c2c6fc103c76361.autoexit_command autoexit
(lldb)     command script add -s asynchronous -f fruitstrap_c5916c52ff72ab85b3374c8b7c2c6fc103c76361.safequit_command safequit
(lldb)     connect
(lldb)     run
success
(lldb)     safequit
Process 292 stopped
Process 292 detached

Here is the standard error of the command (if any):
error: libarclite_iphoneos.a(arclite.o) failed to load objfile for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a

**Device Console Output:**
Feb 18 18:00:00 iPhone com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.51.1
	[389] <Warning>: 1 +0.000000 sec [0185/0b07]: Disabling breakpoints and watchpoints, and detaching from 390.
Feb 18 18:00:00 iPhone com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.51.1
	[389] <Warning>: 2 +0.001264 sec [0185/0b07]: error: ::ptrace (request = PT_THUPDATE, pid = 0x0186, tid = 0x3103, signal = -1) err = Invalid argument (0x00000016)
Feb 18 18:00:00 iPhone com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.51.1
	[389] <Warning>: 3 +0.001264 sec [0185/1b0b]: error: ::read ( -1, 0x16e246a38, 1024 ) => -1 err = Bad file descriptor (0x00000009)
Feb 18 18:00:00 iPhone com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.51.1
	[389] <Warning>: Exiting.
Feb 18 18:00:01 iPhone myApp[390] <Warning>: NIM LOG> Log level(500)
Feb 18 18:00:01 iPhone myApp[390] <Warning>: NIM LOG> Log file path: /var/mobile/Containers/Data/Application/BEBF4C25-A12F-4098-B6A7-B2A33E5981E4/Documents/Nimble.log
Feb 18 18:00:01 iPhone myApp[390] <Warning>: NIM_INFO>NIMBLE> NIMBLE VERSION 1.22.120.1020 (Build 1.22.120.1020)
Feb 18 18:00:01 iPhone myApp[390] <Warning>: NIM_INFO>NIMBLE> BUILD DATE: Oct 20 2015, 12:04:55
Feb 18 18:00:01 iPhone myApp[390] <Warning>: -> registered mono modules 0x102467790
Feb 18 18:00:01 iPhone myApp[390] <Warning>: You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
Feb 18 18:00:05 iPhone SpringBoard[58] <Warning>: Forcing crash report of <FBApplicationProcess: 0x1314bd3f0; myApp; pid: 390> (reason: 1, description: com.myApp failed to scene-create after 3.88s (launch took 16.12s of total time limit 20.00s))
Feb 18 18:00:05 iPhone diagnosticd[83] <Error>: error evaluating process info - pid: 390, punique: 390
Feb 18 18:00:05 iPhone SpringBoard[58] <Warning>: Finished crash reporting.
Feb 18 18:00:05 iPhone SpringBoard[58] <Warning>: BSXPCMessage received error for message: Connection invalid
Feb 18 18:00:05 iPhone SpringBoard[58] <Warning>: BSXPCMessage received error for message: Connection invalid
Feb 18 18:00:05 iPhone SpringBoard[58] <Warning>: HW kbd: Failed to set (null) as keyboard focus
Feb 18 18:00:05 iPhone com.apple.xpc.launchd[1] (UIKitApplication:com.myApp[0x7e68][390]) <Notice>: Service exited due to signal: Killed: 9
Feb 18 18:00:05 iPhone ReportCrash[392] <Warning>: saved type '109_myApp' report (1 of max 25) as /var/mobile/Library/Logs/CrashReporter/myApp_2016-02-18-180005_iPhone.ips
Feb 18 18:00:05 iPhone SpringBoard[58] <Warning>: Application 'UIKitApplication:com.ea.ios.myApp[0x7e68]' exited abnormally via signal.
Feb 18 18:00:05 iPhone UserEventAgent[26] <Warning>: 296103517886: id=com.myApp
pid=390, state=0

**Comment by hoihoi8** [comment]
Just did a test with Yosemite 10.10.3
ios-deploy 1.8.5

**Working devices:**
iPhone 6+ with 8.3 (12F70): Previously crashed on El Capitan

**Failing devices:**
iPhone 5 with 9.1 (13B143): Also crashed on El Capitan

**Comment by shazron** [comment]
Does:
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a` exist on your system? What version of Xcode do you have installed

**Comment by hoihoi8** [comment]
Hello,
Sorry for the delay. The following file exists on my machine:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a

I am running Xcode 7.2.1 (7C1002)

**Comment by hoihoi8** [comment]
[LatestCrash-myApp.txt](https://github.com/phonegap/ios-deploy/files/162332/LatestCrash-myApp.txt)

**Comment by shazron** [comment]
1.8.6 published -- please test with that and report back. Thanks!
https://github.com/phonegap/ios-deploy/releases/tag/1.8.6

**Comment by shazron** [comment]
Closing since I think 1.8.6 fixes this. Re-open if you feel that it is not resolved.
