### ISSUE TITLE
Deployed app starts really slow

### ISSUE THREAD

**Issue by epegzz** [phonegap/ios-deploy#216]
# command
`ios-deploy --bundle build/Build/Products/Debug-iphoneos/test.app -L`

# Expected behavior
The app starts as fast as if i would start it manually on the device or if I would install and run it through xcode. Start screen would show for less than 1 second.

# Actual behavior.
The start screen shows up for 16 seconds.

# System Specs
Build System: Macbook Air, OSX El Capitan.
Deploy device: IPhone 6, iOS 9.2

**sw_vers -productVersion**
`0.11.2`

**ios-deploy -V**
`1.8.5`

**xcodebuild -version**
```code 7.2
Build version 7C68```

**xcode-select --print-path**
`/Applications/Xcode.app/Contents/Developer`

**gcc --version**
```Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix```

**6. lldb --version**
`lldb-340.4.119`

**Comment by hoihoi8** [comment]
This may be related to my issue. #213

**Comment by WeiLee185** [comment]
+1

**Comment by advantiss** [comment]
My app is starting with ios-deploy about 2 minutes, counting from "lldb run", until main screen appears on device. Xcode 7.2.1, SDK 9.2, iphone 4s with iOS 7.1. Application started faster(about 15 second) initially when it had no UI. But after adding single view, startup become about 2 minutes.
Debug run directly from Xcode takes just few seconds.

**Comment by shazron** [comment]
1.8.6 published -- please test with that and report back. Thanks!
https://github.com/phonegap/ios-deploy/releases/tag/1.8.6

**Comment by shazron** [comment]
Closing since I think 1.8.6 fixes this. Re-open if you feel that it is not resolved.

**Comment by advantiss** [comment]
I found out that the same app have installed on iPhone with iOS 9.3 smoothly, like via XCode. But stucks when installing to iPhone 4s with iOS 7.1. Note that only 9.3 SDK is installed in my system.
So, i believe, there is some issue with loading symbols for outdated iOS.

**Comment by shazron** [comment]
That's definitely the problem - it doesn't have the symbols for iOS 7.1 that it can load...

**Comment by advantiss** [comment]
Then why it was installed on iOS 7.1 fast via XCode on same system?

**Comment by luco** [comment]
@shazron Getting the same as @advantiss. ios-deploy takes too long to init the app.
