### ISSUE TITLE
ios-deploy command not found when ran from jenkins

### ISSUE THREAD

**Issue by saratchandrakarumuri** [phonegap/ios-deploy#220]
When running the command 

ios-deploy -L -b application.app

using the execute shell build step from jenkins, getting the following error

ios-deploy: command not found

The same command is working when executed through the terminal manually

# Expected behavior
Should deploy and launch app on the device

# Actual behavior.
Build is marked as failed with the message 

ios-deploy: command not found

# Steps to reproduce the problem
Create a project in jenkins with the "execute shell" build step. Use the command

ios-deploy -L -b application.app

Create a build

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. sw_vers -productVersion : 10.11.2
- [ ] 2. ios-deploy -V : 1.8.5
- [ ] 3. xcodebuild -version : xcode 7.3 Build version 7D175
- [ ] 4. xcode-select --print-path : /Applications/Xcode.app/Contents/Developer
- [ ] 5. gcc --version : Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [ ] 6. lldb --version : lldb-350.0.21.3

I am not sure whether this might help, but here's the log for the command
npm install && npm test

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.9.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'test' ]
2 info using npm@3.7.3
3 info using node@v5.9.1
4 verbose config Skipping project config: /Users/sara8187/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/Users/sara8187/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /Users/sara8187
7 error Darwin 15.2.0
8 error argv "/usr/local/Cellar/node/5.9.1/bin/node" "/usr/local/bin/npm" "test"
9 error node v5.9.1
10 error npm  v3.7.3
11 error path /Users/sara8187/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/Users/sara8187/package.json'
16 error enoent ENOENT: no such file or directory, open '/Users/sara8187/package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -2, true ]

**Comment by shazron** [comment]
This is a problem with pathing in Jenkins, and not an ios-deploy problem. Check your environment.

**Comment by saratchandrakarumuri** [comment]
Can you guide me on how to do that and where should the path pointing to

**Comment by shazron** [comment]
If this is not a ios-deploy problem, I can't really help you, nor do I have the time to dive in. This is a Jenkins and/or your environment issue. You'll have to add where ios-deploy is installed to the path. Do a `which ios-deploy` to find where it is installed.
