### ISSUE TITLE
The Application could not be verified?

### ISSUE THREAD

**Issue by Jwiggiff** [phonegap/ios-deploy#224]
# Expected behaviour
Download app to iPad and run.

# Actual behavior.
When installing at 70% it stop and returns an error: "2016-04-11 18:50:34.062 ios-deploy[2193:1566331] [ !! ] Error 0xe800003a: The application could not be verified. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)"

# Steps to reproduce the problem
1. Plug in iPad
2. type "ios-deploy -W -b <Path to .ipa File>"
3. press enter

# System Specs
Macbook Pro Retina, 13-inch, mid 2014
OS X El Capitan 10.11.4
Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. sw_vers -productVersion
- [ ] 2. ios-deploy -V
- [ ] 3. xcodebuild -version
- [ ] 4. xcode-select --print-path
- [ ] 5. gcc --version
- [ ] 6. lldb --version
1. 10.11.4
2. 1.8.5
3. Xcode 7.3
Build version 7D175
4. /Applications/Xcode.app/Contents/Developer
5. Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
6. lldb-350.0.21.3

**Comment by shazron** [comment]
This is definitely a problem with your code signing. ios-deploy just tries to install it blindly, if it wasn't signed properly you would get this error.

Try deploying (thus signing) your app first using Xcode, then in the Project Navigator, go to the Products folder, and right click on the generated .app. Deploy that signed app using ios-deploy, that should work.
