### ISSUE TITLE
Explain wifi

### ISSUE THREAD

**Issue by fulldecent** [phonegap/ios-deploy#226]
Please explain how the install-over-wifi feature works.

**Comment by macecchi** [comment]
Please. I have come to this project many times and I still couldn't figure it out. :(

**Comment by javierquevedo** [comment]
Is this even possible? Has anyone have been able to do this in any way?

**Comment by shazron** [comment]
It is not possible, they disabled it. We only provide the `--no-wifi` flag so we can ignore wifi connected devices.

**Comment by kirpigiller** [comment]
"they disable it"
Could you please share a link where I can read about this.

**Comment by shazron** [comment]
![screen shot 2017-01-25 at 11 14 05 pm](https://cloud.githubusercontent.com/assets/36107/22322909/042e43d8-e354-11e6-8f60-20021dd732e4.png)

No link.
It's the "Sync this iPhone over WiFi" option in iTunes, which makes iOS devices discoverable but you can't deploy apps to it.

**Comment by kirpigiller** [comment]
I've spent an extra hour add it works.
Sync with this iPhone over Wi-Fi allows to install application via wi-fi...
`$ ios-deploy -i 10348538a1f20a101fba60d5a8d078a3e8298b4e -b ~/Downloads/Payload/blabla.app
[....] Waiting for iOS device to be connected
[....] Using (10348538a1f20a101fba60d5a8d078a3e8298b4ess).
------ Install phase ------
[  0%] Found (10348538a1f20a101fba60d5a8d078a3e8298b4ess) connected through WIFI, beginning install
[  5%] Copying ... to device
...
[100%] Installed package`

But debugging doesn't work.
Do you have any ideas how to enable it?

**Comment by javierquevedo** [comment]
Where did you find the id 10348538a1f20a101fba60d5a8d078a3e8298b4ess? Is that the phone's uuid?

**Comment by javierquevedo** [comment]
I have also been able to install it over the wifi, but it wont launch, even with the ```-L``` or the ```--justlaunch``` flags. Any ideas if this might be possible?

```------ Debug phase ------
Cannot debug (xxxxxxxxxxxxx) over WIFI.```

**Comment by PriyaRaghunatha** [comment]
This thread seems to be more than a year old.. But I'm still unable to launch over Wi-Fi...Any solutions yet?
