### ISSUE TITLE
Defork from ghughes/fruitstrap

### ISSUE THREAD

**Issue by edgarsj** [phonegap/ios-deploy#227]
Hello, 

Would you consider deforking from ghughes/fruitstrap for the project really has many changes, fruitstrap is not maintained anymore and there is no benefit from the link. 

It would also help to create a Homebrew formula, see https://github.com/Homebrew/homebrew-core/pull/1045.

Seems that the proper way to unlink is through GitHub support. 

Thanks,
Edgars

**Comment by shazron** [comment]
I don't see the harm. I like to always credit where it was forked from.
As for homebrew, I think we did go down that path, but I will leave that up to others to do it if they care to (I don't).

**Comment by edgarsj** [comment]
Thanks for the answer. I'm happy to say that homebrew decided to bypass no forks audit rule and now ios-deploy is available through homebrew.
