### ISSUE TITLE
Failed at the ios-deploy@1.8.6 preinstall script './src/scripts/check_reqs.js && xcodebuild

### ISSUE THREAD

**Issue by jchesterisidoro** [phonegap/ios-deploy#229]
# Expected behavior
Successful installation of **ios-deploy**

# Actual behavior.
Failed installation of **ios-deploy**

# Steps to reproduce the problem
run **sudo npm install -g ios-deploy**

# System Specs
Mac Mini Late 2012
Processor: 2.5 GHz Intel Core i5
Memory: 4 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 4000 1024 MB

- [ ] 1. sw_vers -productVersion
10.10.5

- [ ] 2. ios-deploy -V
-bash: ios-deploy: command not found

- [ ] 3. xcodebuild -version
Xcode 7.2
Build version 7C68

- [ ] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

- [ ] 5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

- [ ] 6. lldb --version
lldb-340.4.119

**Comment by Zorgatone** [comment]
I'm having the same problem. Are you using NodeJS 6.x?

**Comment by Zorgatone** [comment]
@jchesterisidoro this solution worked for me on Mac OS X El Capitan: http://stackoverflow.com/questions/34195673/ios-deploy-fail-to-install-on-mac-os-x-el-capitan-10-11

**Comment by jchesterisidoro** [comment]
@Zorgatone Thanks! This command worked for me
npm install -g ios-deploy --unsafe-perm=true
It's weird though that they said it's an issue since El Capitan. My OS is still Yosemite.
