### ISSUE TITLE
Error trying to instal ios-deploy

### ISSUE THREAD

**Issue by EnricoPicci** [phonegap/ios-deploy#230]
I am trying to install ios-deploy on a Mac with ElCaptain v 10.11.4

I run the command
`$ sudo npm install --global --unsafe-perm ios-deploy`

and I get the following error

> ios-deploy@1.8.6 preinstall /usr/local/lib/node_modules/.staging/ios-deploy-298c9491
> ./src/scripts/check_reqs.js && xcodebuild

/usr/local/lib/node_modules/.staging/ios-deploy-298c9491/src/scripts/check_reqs.js:29
		var ver = arr[1];
		             ^

TypeError: Cannot read property '1' of null
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/.staging/ios-deploy-298c9491/src/scripts/check_reqs.js:29:16)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "--unsafe-perm" "ios-deploy"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! ios-deploy@1.8.6 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ios-deploy@1.8.6 preinstall script './src/scripts/check_reqs.js && xcodebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ios-deploy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./src/scripts/check_reqs.js && xcodebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ios-deploy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ios-deploy
npm ERR! There is likely additional logging output above.

**Comment by shazron** [comment]
You didn't fill in the required info in System Specs when you filed the issue. Please fill it in: https://github.com/phonegap/ios-deploy/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by luco** [comment]
+1 here.

sw_vers -productVersion 10.11
--
Xcode 7.3
Build version 7D175
--
xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
--
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
--
lldb-350.0.21.3

**Comment by shazron** [comment]
@luco I don't think you have the same issue. Please read the README.md: https://github.com/phonegap/ios-deploy/blob/master/README.md#os-x-1011-el-capitan

**Comment by luco** [comment]
@shazron 

Already tried with that.
Still getting this:

```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy" "--unsafe-perm=true" "--allow-root"
npm ERR! node v5.0.0
npm ERR! npm  v3.5.3
npm ERR! path /usr/local/bin/ios-deploy
npm ERR! code EEXIST

npm ERR! Refusing to delete /usr/local/bin/ios-deploy: ../lib/node_modules/ios-deploy/ios-deploy symlink target is not controlled by npm /usr/local
npm ERR! File exists: /usr/local/bin/ios-deploy
npm ERR! Move it away, and try again.
```

**Comment by shazron** [comment]
Either `npm uninstall -g ios-deploy` or just force removing it. Also try using `sudo`, maybe you used that last time so you do not have permissions. Not sure.

**Comment by luco** [comment]
@shazron Removed and installed again. Uninstalled with `sudo` and tried to install with `sudo`. Got this:

```
npm WARN lifecycle ios-deploy@1.8.6~preinstall: cannot run in wd %s %s (wd=%s) ios-deploy@1.8.6 ./src/scripts/check_reqs.js && xcodebuild /usr/local/lib/node_modules/.staging/ios-deploy-298c9491
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v5.0.0
npm ERR! npm  v3.5.3
npm ERR! path /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lucasveiga/Desktop/npm-debug.log
```

**Comment by garrettmac** [comment]
install from brew `brew install ios-deploy`

**Comment by shazron** [comment]
note that the brew ios-deploy is maintained by someone else.
