### ISSUE TITLE
Cordova IOS app is not launching real device & Working fine in simulator

### ISSUE THREAD

**Issue by Jpsankaran** [phonegap/ios-deploy#234]
I have publish one cordova ios app into itunes.It was working before app version 1.1.

But now i made some changes in my app and published again into itunes,publish was successful & installed.Then app is not launching(showing splash screen & quit immediately & no error message).But sample version is working fine in ios simulator.

Any one pls tell me why my cordova ios app is not launching?

**Comment by shazron** [comment]
When you filed an issue, it provided a template for stuff you need to fill in. You have failed to do so. Please do so or else this issue will be closed for lack of information.

**Comment by joeblew99** [comment]
@shazron 

i got the same thing perhaps. i am using cordova with ios-deploy
"cordova run ios" is when the error below occurs.
its looking in the wrong place of the cordova dir folders it seems..

full steps to reproduce.

my env:
x-MacBook-Pro:hello apple$ node -v
v6.3.1
x-MacBook-Pro:hello apple$ npm -v
3.10.3



````
sudo npm install -g cordova
cordova create hello com.example.hello HelloWorld
cordova platform add ios --save
cordova build ios
#cordova emulate ios
cordova run ios


** BUILD SUCCEEDED **

[....] Waiting up to 1 seconds for iOS device to be connected
[....] Found iPhone 4S 'Joe's iPhone' (a87d5cc04bb7ff6b549e058de76e40b32ee655ef) connected through USB.
2016-09-06 10:42:11.537 ios-deploy[38843:337462] [ !! ] Can't access app path '/Users/apple/workspace/go/src/bitbucket.org/gedw99/md/try/cordova/hello/platforms/ios/build/device/HelloWorld.app' : No such file or directory
Error: Error code 253 for command: ios-deploy with args: --justlaunch,--no-wifi,-d,-b,/Users/apple/workspace/go/src/bitbucket.org/gedw99/md/try/cordova/hello/platforms/ios/build/device/HelloWorld.app
x-MacBook-Pro:hello apple$

**Comment by shazron** [comment]
@joeblew99 seems like something different than the original poster. Looks like the app wasn't built for the device. Try a `cordova build --device` to see if that works first.

**Comment by simonmacfadyen** [comment]
My issue turned out to be the 'Deployment Target' set in the Xcode Project. It was set to iOS 7.0, and setting it to 10.1 (Current latest version) allowed me to depoy.

**Comment by greyboxsoftware** [comment]
My issue was to unlock my phone prior to running the cordova run ios command because the phone was denying access.
