### ISSUE TITLE
Can't start an app with just bundle_id

### ISSUE THREAD

**Issue by codeskyblue** [phonegap/ios-deploy#236]
## Actions 
```
ios-deploy --bundle_id com.example.game --justlaunch
```
# Expected behavior

App started.

# Actual behavior.

Not started, but got this output

```
2016-06-16 21:40:20.410 ios-deploy[16304:177853] [ !! ] One of -[b|c|o|l|w|D|R|e|9] is required to proceed!
```
# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. sw_vers -productVersion
- [ ] 2. ios-deploy -V

    1.8.6

- [ ] 3. xcodebuild -version

    ```
    Xcode 7.3
    Build version 7D175
    ```
- [ ] 4. xcode-select --print-path
- [ ] 5. gcc --version
- [ ] 6. lldb --version

**Comment by shazron** [comment]
`--bundle_id` is only valid for --list and --upload, as stated in the README.md
You can deploy an app and start it, but not just launch an app already on device.

**Comment by codeskyblue** [comment]
but use idevicedebug I can do this, why ios-deploy cannot do it?

**Comment by shazron** [comment]
This feature is not a priority for us at all, code contributions to add this feature are welcome. As it stands, this bug is invalid because we never supported the feature. Thanks for reporting it.
