### ISSUE TITLE
iOS 10 support

### ISSUE THREAD

**Issue by mark777t** [phonegap/ios-deploy#239]
Are there any plans or estimations for ios10 - Xcode 8 support?

Actual result:
Application installed but failed to start on the device with ios10.

Expected Result:
Install and start on device should work on ios10 and xcode 8.

**Comment by skicson** [comment]
FYI - on iOS 10 (beta 2) we were seeing some bad behaviors on our PhoneGap app - windows not refreshing, poor performance, etc.   After looking at the logs, we saw complaints about the frame-src not including gap://ready in the Content-Security-Policy.  We added gap://ready to frame-src and also added child-src * gap://ready and things seem to work okay now.

**Comment by skicson** [comment]
More details - iOS 10 (beta 3) seems to have addressed previous issues without need for gap://ready fix described above.

**Comment by wir0x** [comment]
@skicson you had problems with icon o images in your app? 
Look this: [http://stackoverflow.com/questions/38254073/ios-10-gmsmapview-showing-my-location-icon-with-white-background](url)
I have the same problem with my app in iOS 10, you know something about that?

**Comment by shortnoticeapp** [comment]
@wir0x i have the same issue

**Comment by shazron** [comment]
@mark777t any change with iOS 10 beta 4?

**Comment by wir0x** [comment]
@shazron in the last iOS 10beta was solved this issue, my app don't have this problem. 👍 😄

**Comment by jeromejesse** [comment]
On iOS GM I need to add gap://ready in the Content-Security-Policy.

And I have an issue with ios-deploy:

`Traceback (most recent call last):
  File "/tmp/7158F017-0F27-4322-9A09-70A41992DB98/fruitstrap_a115ebed5a965b92e409a535727e5e85c85453e2.py", line 36, in run_command
    lldb.target.Launch(lldb.SBLaunchInfo(shlex.split(args[1] and args[1] or '')), error)
IndexError: list index out of range`

**Comment by shazron** [comment]
@jeromejesse see #240

**Comment by jeromejesse** [comment]
Thank you for the release. It's solve the issue ;)
