### ISSUE TITLE
error in deployment

### ISSUE THREAD

**Issue by durexdijo** [phonegap/ios-deploy#242]
I tried installing building and running my app and i get this error.. what could be the reason and how can i build and deploy this on my device?  cordova run ios --device is the command i used

jus-MacBook-Pro:app tujukoll$ cordova run ios --device
Building project: /Users/tujukoll/Desktop/app/platforms/ios/Talazo.xcodeproj
	Configuration: Debug
	Platform: device
Build settings from command line:
    CONFIGURATION_BUILD_DIR = /Users/tujukoll/Desktop/app/platforms/ios/build/device
    SHARED_PRECOMPS_DIR = /Users/tujukoll/Desktop/app/platforms/ios/build/sharedpch

Build settings from configuration file '/Users/tujukoll/Desktop/app/platforms/ios/cordova/build-debug.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    IPHONEOS_DEPLOYMENT_TARGET = 8.0
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h
    TARGETED_DEVICE_FAMILY = 1,2

=== BUILD TARGET CordovaLib OF PROJECT CordovaLib WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET Talazo OF PROJECT Talazo WITH CONFIGURATION Debug ===

Check dependencies
Signing for Talazo requires a development team. Select a development team in the Target Editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/tujukoll/Desktop/app/platforms/ios/cordova/build-debug.xcconfig,-project,Talazo.xcodeproj,-target,Talazo,-configuration,Debug,-destination,platform=iOS,build,CONFIGURATION_BUILD_DIR=/Users/tujukoll/Desktop/app/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/tujukoll/Desktop/app/platforms/ios/build/sharedpch
Otujus-MacBook-Pro:app tujukoll$

**Comment by shazron** [comment]
This is not an ios-deploy error. You need to code-sign your app. How to do so is out of scope for this tool. `Code signing is required for product type 'Application' in SDK 'iOS 10.0'`
