### ISSUE TITLE
error installing ios-deploy

### ISSUE THREAD

**Issue by steven-rg-holdings** [phonegap/ios-deploy#246]
sudo npm install -g ios-deploy

# Expected behavior
Expected to install with out warnings or errors 

# Actual behavior.

> ios-deploy@1.8.6 preinstall /usr/local/lib/node_modules/ios-deploy
> ./src/scripts/check_reqs.js && xcodebuild

env: node: No such file or directory
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! ios-deploy@1.8.6 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ios-deploy@1.8.6 preinstall script './src/scripts/check_reqs.js && xcodebuild'.
npm ERR! This is most likely a problem with the ios-deploy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./src/scripts/check_reqs.js && xcodebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ios-deploy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ios-deploy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/stevenmarks/npm-debug.log

# Steps to reproduce the problem

# System Specs

 sudo ionic info

Your system information:

Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.1 Build version 7B91b 

[npm-debug.txt](https://github.com/phonegap/ios-deploy/files/411986/npm-debug.txt)

**Comment by shazron** [comment]
Read the README. It was actually pointed out in the issue template (the boilerplate that you see when you file an issue) in the section "MUST READ BEFORE YOU FILE".

**Comment by steven-rg-holdings** [comment]
thanks …worked now !!
