### ISSUE TITLE
Apple TV support patch

### ISSUE THREAD

**Issue by gusc** [phonegap/ios-deploy#248]
I wanted to contribute a small patch for Apple TV support.

[ios-deploy-1.8.6-apple-tv.diff.zip](https://github.com/phonegap/ios-deploy/files/458899/ios-deploy-1.8.6-apple-tv.diff.zip)

This patch inludes Apple TV 4th gen internal name resolution and a proper platform path resolution when installing the developer disk image.

**Comment by shazron** [comment]
Thanks! How different is this from #228?

**Comment by gusc** [comment]
I think #228 is way better solution, mine is just a dirty patch I threw together to make it work at all.

Only thing that #228 is missing is 4th gen Apple TV device name from `get_device_hardware_name()`, see my patch for that (i.e. `GET_FRIENDLY_MODEL_NAME(model, "J42dAP", "Apple TV 4G")`)
