### ISSUE TITLE
Application not signing with Xcode 8 and iOS 10.

### ISSUE THREAD

**Issue by vj-raghavan** [phonegap/ios-deploy#249]
# Expected behavior

Use phone gap plugin in IntelliJ to build a Cordova project and deploy it to the connected iPhone. 
The app should be signed with the developer certificate included in Xcode.

Command which the plugin runs - 
/usr/local/bin/cordova run ios --device

Note: 
Before updates to Xcode from 7.3.1 to 8 - this worked fine. Updated my phone to iOS 10 and Xcode 8.

# Actual behavior.

Cordova build fails with the following error - 

=== BUILD TARGET WMS Notifications OF PROJECT WMS Notifications WITH CONFIGURATION Debug ===

Check dependencies
Signing for "WMS Notifications" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
# Steps to reproduce the problem
1. Cordova project.
2. iOS version 10.
3. Xcode SDK 8
4. run cordova run ios --device

- [x] 1. sw_vers -productVersion - 10.11.6
- [x] 2. ios-deploy -V - 1.8.6
- [x] 3. xcodebuild -version - Xcode 8.0
Build version 8A218a
- [x] 4. xcode-select --print-path - /Applications/Xcode.app/Contents/Developer
- [x] 5. gcc --version - Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [x] 6. lldb --version --- lldb-360.1.50

PS : Thanks for the awesome plugin. Only started using this fervently a while back and find it an amazing time saver. Cheers.

**Comment by shazron** [comment]
Sorry, this is not an ios-deploy problem, but an Xcode Development Cert issue. ios-deploy is a dumb binary that just deploys signed binaries to a device, it's up to you to provide a signed binary. Please refer to the Xcode docs. This is not a Cordova issue either nor is this a Cordova issue tracker.
