### ISSUE TITLE
Feature Request: Update the game without deleting data

### ISSUE THREAD

**Issue by hoihoi8** [phonegap/ios-deploy#254]
I was evaluating other iOS installers, and ideviceinstaller has the ability to update an app with it's installer without deleting data.

It would be nice if there was a flag that allowed this in iOS deploy. Our automation would like to avoid fresh installs each time, to avoid the system Notification dialogs that occur in iOS 9.0+.

Thanks for the great tool :)

**Comment by rLadia** [comment]
The default installation method doesn't delete any user data. Is that not what you mean? `ios-deploy --bundle /path/to/bundle`

**Comment by shazron** [comment]
Concurring with @rLadia  -- it shouldn't delete any data. If this is still an issue, please re-open
