### ISSUE TITLE
A few bugs in finding the Xcode/Platform path

### ISSUE THREAD

**Issue by gusc** [phonegap/ios-deploy#255]
1. https://github.com/phonegap/ios-deploy/blob/1.x/src/ios-deploy/ios-deploy.m#L272 the path string has "&" but probably should have "/"
2. I tested a little bit and it seems that all those backslashes are irrelevant in https://github.com/phonegap/ios-deploy/blob/1.x/src/ios-deploy/ios-deploy.m#L474 and further. copy_xcode_dev_path() will return a path without backslashes if directory name contains spaces in it anyway.

**Comment by black-square** [comment]
@gusc  Coul you check please if the issues are still present after: 85a8fe10fc5b07d52eaddc2d47c38d4999c24a09?

**Comment by gusc** [comment]
It looks like the main problem (with the &) has been fixed and the backslashes are gone too, but I'll give it a more thorough look on monday

**Comment by shazron** [comment]
I'm going to close this for now for 1.9.1, if it's not satisfactory we can slate it for 1.9.2
