### ISSUE TITLE
Test on Mac OSX 10.12 Sierra. Runs perfectly fine

### ISSUE THREAD

**Issue by javierquevedo** [phonegap/ios-deploy#260]
# Expected behavior
Runs on 10.12

# Actual behavior.
Runs perfectly fine on 10.12

# Steps to reproduce the problem
There are no problems

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. sw_vers -productVersion
10.12
- [ ] 2. ios-deploy -V
2.0.0
- [ ] 3. xcodebuild -version
Xcode 8.0
Build version 8A218a
- [ ] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
- [ ] 5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [ ] 6. lldb --version
lldb-360.1.50

**Comment by sonrebmax** [comment]
how to install ios-deploy 2.0.0 ?

**Comment by javierquevedo** [comment]
I sent a merge request with the updated readme.md
