### ISSUE TITLE
Not able to install.

### ISSUE THREAD

**Issue by gbrigens** [phonegap/ios-deploy#262]
Am installing ios-deploy but ma getting this issue, what am I doing wrong thanks.

npm WARN lifecycle ios-deploy@1.9.0~preinstall: cannot run in wd %s %s (wd=%s) ios-deploy@1.9.0 ./src/scripts/check_reqs.js && xcodebuild /Users/gbrigens/.npm-global/lib/node_modules/.staging/ios-deploy-c183c939
npm ERR! Darwin 16.0.0
npm ERR! argv "/opt/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! path /Users/gbrigens/.npm-global/lib/node_modules/ios-deploy/build/Release/ios-deploy
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/gbrigens/.npm-global/lib/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/gbrigens/.npm-global/lib/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gbrigens/npm-debug.log

**Comment by shazron** [comment]
Check out the README regarding the El Capitan section, and re-install using the flags specified.

**Comment by gbrigens** [comment]
Thanks so much, I was able to install it using El Capitan flags.

**Comment by tommydudehead** [comment]
@shazron could you elaborate on what readme and where I might find it? Also having this issue since upgrading the Mac. Such a pain. Thanks :)

**Comment by MrHzAkI** [comment]
Use this : npm install -g ios-deploy --unsafe-perm=true

**Comment by lionelquellery** [comment]
Thanks a lot @MrHzAkI !
