### ISSUE TITLE
Is it possible to deploy and re-run without exiting lldb

### ISSUE THREAD

**Issue by johnofcamas** [phonegap/ios-deploy#263]
An issue with lldb is that when I make a change to the code, and want to re-run iOS-deploy, I have to exit lldb back out to the shell which causes me to lose all my breakpoints.

Is it possible to somehow re-deploy the app and re-launch without exiting lldb?

**Comment by shazron** [comment]
No, there is no facility for this, nor will there likely be unfortunately. ios-deploy launches a temporary python file that it writes with a lot of parameters to launch everything it needs (https://github.com/phonegap/ios-deploy/blob/b9e80afa0f6e818c960cef4fbc8fd2ced6409088/src/ios-deploy/ios-deploy.m#L29-L40)
