### ISSUE TITLE
uid must be an unsigned int

### ISSUE THREAD

**Issue by pentool** [phonegap/ios-deploy#268]
1. Open Terminal
2. sudo install -g ios-deploy
3. error: uid must be an unsigned int

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. sw_vers -productVersion
OS X 10.11.6

- [ ] 2. ios-deploy -V
command not found (...obviously...)

- [ ] 3. xcodebuild -version
Xcode 7.3.1 b7D1014

- [ ] 4. xcode-select --print-path
/Applications/Xcode 7.3.1.app/Contents/Developer

- [ ] 5. gcc --version
Configured with: --prefix=/Applications/Xcode 7.3.1.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode 7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

- [ ] 6. lldb --version
lldb-350.0.21.9

**Comment by shazron** [comment]
Just checking, is your Step number 2 missing something, like `npm`?

**Comment by pentool** [comment]
Thanks for checking in. Don't remember what was the issue (not npm related) but it has been solved since.
