### ISSUE TITLE
Visual studio build on mac iOS 10.12.1 , getting Warning that i am on OS X 10.11 El Captitan. 

### ISSUE THREAD

**Issue by micho777** [phonegap/ios-deploy#272]
the issue is that am not being able to build from Visual Studio into the Mac, i was able to do that before.

# Expected behavior
build app from Visual studio build on iOS device 

# Actual behavior.
getting error:
 Failed to build app for buildNumber 513: ios-deploy was not found. Please download, build and install version 1.9.0 or greater from https://github.com/phonegap/ios-deploy into your path, or do 'npm install -g ios-deploy'

1>MSBUILD : cordova-build error : Error: Remote build error from the build server Build failed with error ios-deploy was not found. Please download, build and install version 1.9.0 or greater from https://github.com/phonegap/ios-deploy into your path, or do 'npm install -g ios-deploy' - 1
1>         Error Remote build error from the build server Build failed with error ios-deploy was not found. Please download, build and install version 1.9.0 or greater from https://github.com/phonegap/ios-deploy into your path, or do 'npm install -g ios-deploy' - {1}

# Steps to reproduce the problem
build from visual studio on iOS

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. sw_vers -productVersion
10.12.1
- [ ] 2. ios-deploy -V
ios-deploy: command not found
- [ ] 3. xcodebuild -version
xcode 8.1 build 8B62
- [ ] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
- [ ] 5. gcc --version
Apple LLVM version 8.0.0 (clang-800.0.42.1) 
Target: x86_64-apple-darwin16.1.0
Thread model: posix 
- [ ] 6. lldb --version
lldb-360.1.65

tried installing ios-deploy with : sudp npm install --global --unsafe-perm=true ios-deploy
and still after ** BUILD SUCCEEDED ** 
on ios-deploy -v am getting ios-deploy: command not found

![screen shot 2016-12-05 at 4 28 12 pm](https://cloud.githubusercontent.com/assets/3685974/20888949/be442936-bb09-11e6-91da-93e095f1fc55.png)

**Comment by shazron** [comment]
Related: #274. I updated the README and script warning (El Capitan or Greater)

**Comment by git00** [comment]
@shazron, I see the new warning.  However, if you don't use the option (--unsafe-perm=true) the failure never shows onscreen or in npm-debug.log.  I finally came to the Github repository and found out about the error fix that way.  Is there any way to get the warning pushed into the "npm-debug.log" or into the npm console output?  Below is my npm console output when I ran without the proper option.  Also note that "--unsafe-perm" without the "=true" seems to be fine as well.

```
sudo npm install -g ios-deploy
npm WARN lifecycle ios-deploy@1.9.1~preinstall: cannot run in wd %s %s (wd=%s) ios-deploy@1.9.1 ./src/scripts/check_reqs.js && xcodebuild /usr/local/lib/node_modules/.staging/ios-deploy-298c9491
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! path /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

**Comment by shazron** [comment]
> However, if you don't use the option (--unsafe-perm=true) the failure never shows onscreen or in npm-debug.log

afraid not, this is unfortunately something npm controls and is a known issue when under certain OSes
