### ISSUE TITLE
Facing issue while installing iOS-deploy

### ISSUE THREAD

**Issue by theguru12** [phonegap/ios-deploy#274]
Command executed as follows: `$ npm install -g ios-deploy`

# Expected behaviour
Should install the iOS-deploy module

# Actual behavior.
Getting error as follows:
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! ios-deploy@1.9.0 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ios-deploy@1.9.0 preinstall script './src/scripts/check_reqs.js && xcodebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ios-deploy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./src/scripts/check_reqs.js && xcodebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ios-deploy

[ios-deploy_issue-txt.txt](https://github.com/phonegap/ios-deploy/files/639009/ios-deploy_issue-txt.txt)
 Steps to reproduce the problem

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. sw_vers -productVersion 
10.11.6

- [ ] 2. ios-deploy -V
-bash: ios-deploy: command not found

- [ ] 3. xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

- [ ] 4. xcode-select --print-path
/Library/Developer/CommandLineTools

- [ ] 5. gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

- [ ] 6. lldb --version
lldb-350.0.21.9

**Comment by theguru12** [comment]
Ok. Thanks. I'll check .

**Comment by wh33ler** [comment]
same issue here. Dev certificate installed

**Comment by cclass** [comment]
@theguru12 having the same issue, any luck resolving it?

**Comment by joectchan** [comment]
The above did not solve this problem for me but this one did https://github.com/nodejs/node-gyp/issues/569

**Comment by TomYiCL** [comment]
same issue here,but my system is macOS Sierra,the flag --unsafe-perm=true didn't work.how can i do?

**Comment by luojxxx** [comment]
Similar problem although with mine it says:
```

npm WARN lifecycle ios-deploy@1.9.0~preinstall: cannot run in wd %s %s (wd=%s) ios-deploy@1.9.0 ./src/scripts/check_reqs.js && xcodebuild /usr/local/lib/node_modules/.staging/ios-deploy-298c9491
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.5
npm ERR! path /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cloudlife/GitHub/Testphonegap/npm-debug.log
```

**Comment by shazron** [comment]
ios-deploy needs Xcode since it needs to use some private frameworks. I'll update the README.
@luojxxx I assume you tried the flags as specified in the README? (since the error looks like a permission error)
