### ISSUE TITLE
I can`t import the documents file with iOS 10.2

### ISSUE THREAD

**Issue by anywayfly** [phonegap/ios-deploy#278]
## MUST READ BEFORE YOU FILE (DELETE THIS SECTION BEFORE FILING)

Include the **command line arguments** you used for ios-deploy.

Don't forget to check out the [El Capitan](https://github.com/phonegap/ios-deploy/blob/master/README.md#os-x-1011-el-capitan) section of the [README](https://github.com/phonegap/ios-deploy/blob/master/README.md) before filing this issue.

# Expected behavior

# Actual behavior.

# Steps to reproduce the problem

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. sw_vers -productVersion
- [ ] 2. ios-deploy -V
- [ ] 3. xcodebuild -version
- [ ] 4. xcode-select --print-path
- [ ] 5. gcc --version
- [ ] 6. lldb --version

**Comment by anywayfly** [comment]
sw_vers -productVersion
10.11.5
ios-deploy -V
1.9.0
 xcodebuild -version
Xcode 8.1
Build version 8B62

xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
 gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

 lldb --version
lldb-360.1.65

**Comment by shazron** [comment]
Thanks for the System Specs but you neglected to fill out the proper bug report sections. This issue will be closed if there are no additional details.
