### ISSUE TITLE
Does ios-deploy install the provisioning profile on device?

### ISSUE THREAD

**Issue by hackjutsu** [phonegap/ios-deploy#286]
This is a general question about how ios-deploy works rather than an issue.

If the app is built with a new provisioning profile, is ios-deploy able to install the profile bundled inside the app automatically before installing the app? 

Or do we need to do it manually by launching the app from Xcode, which forces installation of the new profile?

**Comment by shazron** [comment]
The .app should have an embedded.mobileprovision in it when built and packaged. This is what is used.
