### ISSUE TITLE
stack trace during npm install

### ISSUE THREAD

**Issue by Krandelbord** [phonegap/ios-deploy#290]
When i try to install iso-deploy by running:
nam install -g iso-deploy i got the following stack trace:
95 verbose stack Error: ios-deploy@1.9.1 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
95 verbose stack Exit status 134
95 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)

[npm-debug.log.zip](https://github.com/phonegap/ios-deploy/files/981581/npm-debug.log.zip)
95 verbose stack     at emitTwo (events.js:87:13)
95 verbose stack     at EventEmitter.emit (events.js:172:7)
95 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
95 verbose stack     at emitTwo (events.js:87:13)
95 verbose stack     at ChildProcess.emit (events.js:172:7)
95 verbose stack     at maybeClose (internal/child_process.js:827:16)
95 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
96 verbose pkgid ios-deploy@1.9.1

# System Specs
System Version: OS X 10.11.6 (15G1421)
Xcode 7.3 Build version 7D175
nam version 2.14.20
gcc Apple LLVM version 7.3.0 (clang-703.0.29)
lldb-350.0.21.3

**Comment by shazron** [comment]
Check out the README.md https://github.com/phonegap/ios-deploy#os-x-1011-el-capitan-or-greater
