### ISSUE TITLE
Is there a way to deploy, and run the remote debug server, then connect via lldb PYTHON ?

### ISSUE THREAD

**Issue by johnofcamas** [phonegap/ios-deploy#294]
I am writing a python debugger and I want to be able to deploy/run the app and connect via PYTHON's lldb api: ConnectRemote

Is that even possible?  Thoughts?

**Comment by shazron** [comment]
This is out of scope for this module.
You can try modifying the script here and re-build the app: https://github.com/phonegap/ios-deploy/blob/master/src/scripts/lldb.py
