### ISSUE TITLE
Could not find bundle id on a Cordova app

### ISSUE THREAD

**Issue by claudiosvcc** [phonegap/ios-deploy#295]
While I was using appium, I've faced an issue with the ios-deploy execution. I've tried the command manually and could repro the error:
`ios-deploy --id 53d295c0d6c20a308295979aa212eef23153e69b --uninstall --bundle /var/folders/68/zd7l2hzs2h11y4jdwpgslktr0000gn/T/2017521-24200-1rswgpu.e2ex/appium-app.app`

During the appium test, this is used to remove the installed app. In this case app is not installed so it's expected to return false.

However, it says:
"Unable to get bundle id from user command or package /var/folders/68/zd7l2hzs2h11y4jdwpgslktr0000gn/T/2017521-24200-1rswgpu.e2ex/appium-app.app".

If instead of sending the bundle path I send the bundle_id option it works fine.

As clear as the error message looks like, I can see there's an info.plist with the bundle Id in app. Not sure if that can be related, but this is a Cordova v6.5.0 app. The app installs correctly with ideviceinstaller and through iTunes.

# Expected behavior
return false, once the app isn't installed.

# Actual behavior.
returns "Unable to get bundle id from user command or package /var/folders/68/zd7l2hzs2h11y4jdwpgslktr0000gn/T/2017521-24200-1rswgpu.e2ex/appium-app.app".

# Steps to reproduce the problem
Create a cordova 6.5.0 app and try to run ios-deploy --bundle /path/app.app

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. system_profiler SPSoftwareDataType
      System Version: macOS 10.12.5 (16F73)
      Kernel Version: Darwin 16.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Test Mac mini
      User Name: testaccount (testaccount)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 19:37
- [ ] 2. ios-deploy -V
      1.8.7
      (tried before with v 1.9.0 with same results)
- [ ] 3. xcodebuild -version
      Xcode 8.3.3
      Build version 8E3004b
- [ ] 4. xcode-select --print-path
      /Applications/Xcode.app/Contents/Developer
- [ ] 5. gcc --version
     Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
     Apple LLVM version 8.1.0 (clang-802.0.42)
     Target: x86_64-apple-darwin16.6.0
     Thread model: posix
     InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [ ] 6. lldb --version
     lldb-370.0.42
       Swift-3.1

**Comment by shazron** [comment]
The expected usage of uninstall is shown in the README:
```
// Uninstall an app
ios-deploy --uninstall_only --bundle_id my.bundle.id
```
