### ISSUE TITLE
Assertion failed: (AMDeviceIsPaired(device)), function handle_device, file /usr/local/lib/node_modules/.staging/ios-deploy-298c9491/src/ios-deploy/ios-deploy.m, line 1594. Abort trap: 6

### ISSUE THREAD

**Issue by jesseNavdy** [phonegap/ios-deploy#298]
**command line arguments**
ios-deploy --bundle Downloads/IPAs/myApplication.ipa

# Expected behavior
should have installed the ipa

# Actual behavior.
Assertion failed error

# Steps to reproduce the problem
1. plug device in via USB
2. run the command

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.5 (16F73)
      Kernel Version: Darwin 16.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Jesse’s MacBook Pro
      User Name: Jesse Hernandez (jhernandez)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 6 minutes

- [ ] 2. ios-deploy -V
1.9.1

- [ ] 3. xcodebuild -version
Xcode 8.3.3
Build version 8E3004b

- [ ] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

- [ ] 5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

- [ ] 6. lldb --version
lldb-370.0.42
  Swift-3.1

**Comment by jesseNavdy** [comment]
User Error.  I did not allow access on the phone. Closing as Not a Bug

**Comment by allys00** [comment]
Your phone does not trust the computer.

**Comment by dheeraj2dj** [comment]
@jesseNavdy Can you let me know how you allowed the access? Because I remember allowing this, but still failing. 
P.S: Using Flutter
