### ISSUE TITLE
ios-deploy doesn't handle NSLog

### ISSUE THREAD

**Issue by black-square** [phonegap/ios-deploy#301]
I have this code (Unity project):
```
    NSLog(@"Test MSG: NSLog\n");
    fprintf(stderr, "Test MSG: stderr\n");
    fprintf(stdout, "Test MSG: stdout\n");
    const char *msg = "Test MSG: STDERR_FILENO\n";
    const size_t len = strlen(msg);
    write(STDERR_FILENO, msg, len);
```
and  ios-deploy prints all these lines except the first one. When I run the game from XCode I see all the lines.

We really need to support NSLog as it's the most common way to use logging on iOS

**Comment by shazron** [comment]
It's probably the new unified logging system, need to use os_log in the newer macOS/iOS:
https://developer.apple.com/documentation/os/logging#overview
`os_log`

**Comment by shazron** [comment]
Some Xcode env var mentioned here: https://stackoverflow.com/questions/37886600/ios-10-doesnt-print-nslogs

**Comment by black-square** [comment]
Yeah, that's a good catch. Also, I found this: 

> Starting in Fall 2016 OSes, NSLog messages only get mirrored to stderr if the `OS_ACTIVITY_DT_MODE` environment variable is set. 

https://stackoverflow.com/a/39581193
So, we might just need to define`OS_ACTIVITY_DT_MODE` and we will be good
