### ISSUE TITLE
ios-deploy installs but does not launch (its using wifi)

### ISSUE THREAD

**Issue by Brian-Kaplan** [phonegap/ios-deploy#302]
# Expected behavior
My command installs and launched the app to a physical connected device

# Actual behavior
App is installed but not launched

# Steps to reproduce the problem
  ```
ios-deploy --justlaunch --bundle myApp.app --id $DEVICE_ID
``` 
 the bundle and device id are fine, there's no issues there. I know this because If I use the --no-wifi flag the app is installed and launched. I'm using react-native and for some reason the --no-wifi flag will reject connections from my device to my computer. I need my device to be able to connect to the computer so it can download the JS bundle from the react-native packager.

I tried using your -p command and set it to 8081 which is the port my packager is listening on. It doesn't work. maybe the syntax is wrong?

```
-p 8081
```

# System Specs

- [x] 1. system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.3 (16D32)
      Kernel Version: Darwin 16.4.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: C02S422KG8WL
      User Name: Brian Kaplan (brian.kaplan)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 23:36
- [x] 2. ios-deploy -V
        ` 1.91`
- [x] 3. xcodebuild -version
Xcode 8.3.3
Build version 8E3004b
- [x] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
- [x] 5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [x] 6. lldb --version
lldb-370.0.42
  Swift-3.1

**Comment by Brian-Kaplan** [comment]
Looks like im able to connect to the packager with the --no-wifi flag now... must have been a fluke earlier. I will be using this flag since it is able to install and launch. Not using the flag, as described in  this issue will still not start the app after installing.

**Comment by shazron** [comment]
I took a look at the code for setting the port, seems sound (as is the flag):
https://github.com/phonegap/ios-deploy/blob/b6ee2233353b8f818b38c90eca446089c8ecd6b7/src/ios-deploy/ios-deploy.m#L34 

(didn't have a chance to debug to be 100% sure)

 Yeah the --no-wifi flag was precisely implemented to fix this problem. I don't know why it is trying to connect to wifi (although in Xcode 9 it is an option).
