### ISSUE TITLE
Ios-deploy install fails 

### ISSUE THREAD

**Issue by RobertArissen** [phonegap/ios-deploy#308]
Hello, 

# Expected behavior
Install ios-deploy global via NPM

# Actual behavior.
Ios-deploy not installed and get the error:

Ld build/Release/ios-deploy normal x86_64
    cd /usr/local/lib/node_modules/ios-deploy
    export MACOSX_DEPLOYMENT_TARGET=10.8
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -L/usr/local/lib/node_modules/ios-deploy/build/Release -F/usr/local/lib/node_modules/ios-deploy/build/Release -filelist /usr/local/lib/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy.build/Objects-normal/x86_64/ios-deploy.LinkFileList -mmacosx-version-min=10.8 -Xlinker -object_path_lto -Xlinker /usr/local/lib/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy.build/Objects-normal/x86_64/ios-deploy_lto.o -fobjc-arc -fobjc-link-runtime -framework MobileDevice -F/System/Library/PrivateFrameworks -framework Foundation -framework CoreFoundation -Xlinker -dependency_info -Xlinker /usr/local/lib/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy.build/Objects-normal/x86_64/ios-deploy_dependency_info.dat -o /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy
ld: framework not found MobileDevice
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/Release/ios-deploy normal x86_64
(1 failure)
npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! ios-deploy@1.9.1 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 65
npm ERR! 
npm ERR! Failed at the ios-deploy@1.9.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

# Steps to reproduce the problem
I only run the command:  npm install -g ios-deploy

# System Specs

- [ ] 1. system_profiler SPSoftwareDataType
  System Software Overview:
      System Version: macOS 10.12.6 (16G29)
      Kernel Version: Darwin 16.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2:52

- [ ] 2. ios-deploy -V
-

- [ ] 3. xcodebuild -version
Xcode 9.0
Build version 9M202q

- [ ] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

- [ ] 5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.34.1)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

- [ ] 6. lldb --version
lldb-900.0.41
  Swift-4.0

**Comment by shazron** [comment]
Hello, when you filed a new issue, you deleted the template of requirements needed for filing a bug report. Please do that, there is not enough information. Without it, this issue will be closed.

**Comment by RobertArissen** [comment]
Updated

**Comment by shazron** [comment]
This is the root of the problem:
`ld: framework not found MobileDevice` and you are using Xcode 9. It may be missing in Xcode 9. I will investigate later.

**Comment by DomT4** [comment]
It seems to have vanished from Xcode 9, but curiously is in the Command-Line Tools package Apple also distributes and after installing that it becomes available at the usual:
```
/System/Library/PrivateFrameworks/MobileDevice.framework/MobileDevice
```

Build still fails though.

**Comment by shazron** [comment]
It's probably looking for it at:
`$XCODE/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/PrivateFrameworks/MobileDevice.framework/`

where $XCODE is:
`xcode-select -p`

**Comment by shazron** [comment]
However, the linker does look for it at the location you found, see: https://github.com/phonegap/ios-deploy/blob/35c2c55fd15c3d20921941b44e3fd41b890f4253/ios-deploy.xcodeproj/project.pbxproj#L377-L380

**Comment by shazron** [comment]
Similar report in #311

**Comment by DomT4** [comment]
Apple is aware of the issue. Last update was 3 days ago, an acknowledgement that they are looking into it with the information provided.

**Comment by DomT4** [comment]
Apparently if `PrivateFramework` linking remains broken through to GM we're stuck with it. Apple took 10+ days to decide they had no interest in fixing the bug 😓. So `ios-deploy` might be permanently screwed with Xcode 9+ unless the Xcode `clang` is accidentally fixed.

<img width="1188" alt="screen shot 2017-08-25 at 18 55 05" src="https://user-images.githubusercontent.com/6998367/29726286-064509e4-89c7-11e7-9d58-ef4d7e8bda5e.png">

**Comment by antonioribeiro** [comment]
Trying to fix 

![image](https://user-images.githubusercontent.com/3182864/29805245-ee118948-8c5e-11e7-8bab-a381937593c2.png)

For which updating header paths was not helping, I decided to install ios-deploy and now I'm getting the very same error and cordova build also gives me a

```
Error: ios-deploy was not found. Please download, build and install version 1.9.0 or greater from https://github.com/phonegap/ios-deploy into your path, or do 'npm install -g ios-deploy'
```

Thank you, Apple.

**Comment by DomT4** [comment]
Intentionally or not, this is apparently fixed in the Xcode GM. `clang -Wall -framework MobileDevice -F/System/Library/PrivateFrameworks test.c` now delivers success & the expected linkage.

**Comment by shazron** [comment]
That's great. We'll wait and see if it's permanent, the workaround should still work for now

**Comment by tommybananas** [comment]
@shazron what is the workaround?

**Comment by shazron** [comment]
@tommybananas  see #314

**Comment by bjanuario** [comment]
If you are under Sierra you need to add the flag --unsafe-perm=true
`sudo npm install -g ios-deploy --unsafe-perm=true`

**Comment by tresdev** [comment]
@bjanuario this fixed the issue for me

**Comment by pyqui** [comment]
@bjanuario Oh yeah!!! It works!

**Comment by himalayaahuja** [comment]
@bjanuario  It installs the package successfully yes, but again when I create a cordova ios build it throws the same error , saying ---------------
Unhandled promise rejection (rejection id: 1): ios-deploy was not found. Please download, build and install version 1.9.2 or greater from https://github.com/phonegap/ios-deploy into your path, or do 'npm install -g ios-deploy'

**Comment by pabloca88** [comment]
@bjanuario solved my issue.. great Job!

**Comment by mshyrokiy** [comment]
"sudo npm install -g ios-deploy --unsafe-perm=true" doesn't work for me
macOS 10.13.6
xcode Version 10.0 beta 3 (10L201y)

Is there any other way to get "ios-deploy" installed?

**Comment by ziwei3749** [comment]
@sgalvagno this way make it work
