### ISSUE TITLE
How to remove ios-deploy ?

### ISSUE THREAD

**Issue by PierBover** [phonegap/ios-deploy#312]
I added a cordova plugin which prompted me to install `ios-deploy` with `npm i -g ios-deploy`.

I did that but then it broke `cordova build ios`. Then I did `npm r -g ios-deploy` which uninstalled it but now when building I get the error:

```
Error: ios-deploy was not found. Please download, build and install version 1.9.0 or greater from https://github.com/phonegap/ios-deploy into your path, or do 'npm install -g ios-deploy'
```

There is no reference about `ios-deploy` on the config file.

So how can I completely remove `ios-deploy`?

**Comment by shazron** [comment]
This looks like a Cordova issue, not ios-deploy?
Try unplugging your device before build or use `cordova build --emulator`. It will always build to device as well if you have a device connected.

**Comment by PierBover** [comment]
Thanks @shazron 

The plugin in question was `cordova-plugin-wkwebview-engine`. I installed it again afterwards, and again it required me to install `ios-deploy` which I don't want to use.

**Comment by shazron** [comment]
My comment still stands -- it will only use ios-deploy if you have a device connected. Use the `--emulator` flag to skip device install
