### ISSUE TITLE
Error when installing on iOS 11 device

### ISSUE THREAD

**Issue by efa85** [phonegap/ios-deploy#317]
I am getting an error when trying to install and launch an app with this command. It was working before I updated my device from iOS 10 to 11:
`ios-deploy --id <MY_DEVICE_ID> --bundle <PATH_TO_MY_APP_FILE> --justlaunch`
The app doesn't get installed and I get the following error:
`2017-09-20 14:21:01.596 ios-deploy[31450:5812598] [ !! ] Error 0xe8000067: There was an internal API error. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)`

I am using the new Xcode 9 (not beta anymore) as well as non-beta iOS 11 (build 15A372).
My device is an iPad mini 2.

# System Specs

- 1. system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.6 (16G29)
      Kernel Version: Darwin 16.7.0
      Boot Volume: XXX
      Boot Mode: Normal
      Computer Name: XXX
      User Name: XXX
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 4 days 10:56
- 2. ios-deploy -V
2.0.0
- 3. xcodebuild -version
Xcode 9.0
Build version 9A235
- 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
- 5. gcc --version
onfigured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- 6. lldb --version
lldb-900.0.45
  Swift-4.0

**Comment by surajpindoria** [comment]
Hi @efa85,

I just tried this and I am able to deploy the app to my device with the same flags you have used. Are you able to install your app if you do this through Xcode?

**Comment by shazron** [comment]
AMDeviceSecureInstallApplication errors are usually code-signing and/or provisioning profile issues. Your app must be properly signed etc, ios-deploy does not do this for you

**Comment by efa85** [comment]
@surajpindoria, yes, I can run the app through Xcode.

**Comment by efa85** [comment]
Finally I got it to work. The problem was that I was not building the .app for all archs...
Closing the issue.

**Comment by rspq** [comment]
For what it's worth I also hit this same error and it turned out to be a missing .entitlements file. Maybe entitlements are mandatory on iOS 11.

**Comment by MrMicrowaveOven** [comment]
I'm having this exact same issue.  Can you elaborate on how you resolved this?

**Comment by LinusU** [comment]
@efa85 I'm having the same issue as well. I can run the app by pressing play in Xcode, but I cannot do `xcodebuild` + `ios-deploy`

**Comment by LinusU** [comment]
The problem was that the app didn't get built for the architecture of my phone (iPhone 8 -> `arm64`).

Passing `-arch arm64` to `xcodebuild` fixed the problem
