### ISSUE TITLE
Clean exit from a device run

### ISSUE THREAD

**Issue by deanq** [phonegap/ios-deploy#38]
Whenever I deploy to my ios device via `cordova run ios` or other commands, I would always end up quitting by ctrl+c, look for ios-deploy process running, and then kill it. There has to be a cleaner way to do this.

**Comment by venkatpolisetti** [comment]
$ionic run ios --device

Just installed latest ios-deploy after upgrading my iPhone 6 to IOS 8.2. I still have to use killall as suggested by @schmunk42 above.

When I do Ctrl+c, it simply exists to the command prompt. If I do exit then, it is logging me out of my terminal session.

What am I missing here?

**Comment by joshhunt** [comment]
@shazron so iso-deploy now supports the --justlaunch arg to not connect lldb, but cordova run iOS doesn't yet support passing this through. Is that correct?

**Comment by senthilmanick** [comment]
Hi Josh, 
--justlaunch does use lldb but quits cleanly after launching the app. 
if --justlaunch is not provided, lldb stays connected to the running app. If you kill lldb (or ios-deploy), then the app will also stop running on the device. 
HTH 
----- Original Message -----

**Comment by shazron** [comment]
@joshhunt I don't think so, but you can try providing the args after a "--"
```
cordova run ios -- --justlaunch
```

(this info was from a `cordova help run` call)

**Comment by raldred** [comment]
@shazron this does not work.
The run command still hangs with ios-deploy left running even after a ctrl+c

**Comment by shazron** [comment]
@raldred can you file an issue to Cordova? issues.cordova.io - we're preparing a new release I'd like to investigate this

**Comment by raldred** [comment]
Thanks @shazron I get a bit overwhelmed with JIRA so hopefully I've reported it correctly.
https://issues.apache.org/jira/browse/CB-9609
