### ISSUE TITLE
Problems installing with npm (Xcode 6)

### ISSUE THREAD

**Issue by tobiassteenweg** [phonegap/ios-deploy#40]
sudo npm install -g ios-deploy
npm http GET https://registry.npmjs.org/ios-deploy
npm http 304 https://registry.npmjs.org/ios-deploy

> ios-deploy@1.0.8 preinstall /usr/local/lib/node_modules/ios-deploy
> make ios-deploy

rm -rf _.app demo ios-deploy
gcc -ObjC -g -o ios-deploy -framework Foundation -framework CoreFoundation -framework MobileDevice -F/System/Library/PrivateFrameworks ios-deploy.c
cc1: error: argument to '-O' should be a non-negative integer, 'g', 's' or 'fast'
make: *_\* [ios-deploy] Error 1
npm ERR! ios-deploy@1.0.8 preinstall: `make ios-deploy`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ios-deploy@1.0.8 preinstall script.
npm ERR! This is most likely a problem with the ios-deploy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make ios-deploy
npm ERR! You can get their info via:
npm ERR!     npm owner ls ios-deploy
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! cwd /Users/tobias
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/tobias/npm-debug.log
npm ERR! not ok code 0

Can anyone help ? I habe XCode 6 beta installed - Is this causing this issue ?

**Comment by streetkid** [comment]
I'm still receiving this error with 1.3.2 - xcode 6.1.1

npm ERR! ios-deploy@1.3.2 preinstall: `make ios-deploy`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ios-deploy@1.3.2 preinstall script 'make ios-deploy'.

**Comment by shazron** [comment]
@streetkid report your settings from here: https://github.com/phonegap/ios-deploy/blob/master/CONTRIBUTING.md

**Comment by streetkid** [comment]
Hi, I've worked around it by upgrading to Yosemite. I wasn't able to correctly install gcc.
Not sure if that was the cause of the failed ios-deploy install. Thanks

**Comment by kitefishlabs** [comment]
I had this same issue @1.3.2, xcode 6.1.1, Yosemite. FWIW, I used this workaround (see comment by magusd on 8/14):

https://github.com/npm/npm/issues/5890

**Comment by shazron** [comment]
Thanks @kitefishlabs 

Direct link to comment: https://github.com/npm/npm/issues/5890#issuecomment-52412001

Seems the fix is to use clang instead of gcc.
