### ISSUE TITLE
Is there a way to write/upload a file to OSX filesystem?

### ISSUE THREAD

**Issue by juj** [phonegap/ios-deploy#41]
In my unit tests that I automate with ios-deploy, I'm looking for a way to generate a file on the iOS, and have it somehow stored on the OSX filesystem e.g. in the working directory where I launched ios-deploy from. Is something like that possible?

If not, I could always spawn up a HTTP server on the host, and have the iOS device HTTP upload the file there, but that's somewhat heavyweight. It would be nice if there was some way to achieve this with ios-deploy.

On Android I have the application write a file to the Android filesystem `/sdcard/` directory, and then use `adb pull` to retrive that file to the OSX file system after the application has finished running. Would it be possible to do something like this with ios-deploy?

**Comment by luser** [comment]
This seems to have been fixed in d86b0cad0de79c6a7debe0d6cd0b02f7a05ac053, which added --download.
