### ISSUE TITLE
Assertion failed AMDeviceSecureTransferPath (app name has non-ASCII characters)

### ISSUE THREAD

**Issue by asengmany** [phonegap/ios-deploy#56]
Hi,

I already tried to run my app on device with ios-deploy and it worked but now I have this error.

Assertion failed: (AMDeviceSecureTransferPath(0, device, url, options, transfer_callback, 0)==0), function handle_device, file ios-deploy.c, line 1269.
Abort trap: 6

I already clean the project using "xcodebuild clean" but no result.

I try to run my app on an Ipod touch 5g and an iPad, I got the same error

Any idea?

**Comment by ilyakar** [comment]
Hi. How close are you guys to fixing this issue? My app name is Cityfé and I also get the following error: Assertion failed: (AMDeviceSecureTransferPath(0, device, url, options, transfer_callback, 0)==0), function handle_device, file ios-deploy.c, line 1550.

**Comment by matrunchyk** [comment]
Hi. The same issue:
> 2015-06-15 19:03:19.848 ios-deploy[6111:1106188] [ !! ] Error 0xe8000008: ◊esˇ AMDeviceSecureTransferPath(0, device, url, options, transfer_callback, 0)

This is my environment:

**$ sw_vers**
ProductName:	Mac OS X
ProductVersion:	10.10.3
BuildVersion:	14D136

**$ ios-deploy -V**
1.7.0

**$ xcodebuild -version**
Xcode 7.0
Build version 7A120f

**$ xcode-select --print-path**
/Applications/Xcode-beta.app/Contents/Developer/

**$ gcc --version**
Configured with: --prefix=/Applications/Xcode-beta.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.53)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

**$ lldb --version**
lldb-340.4.44

**Comment by matrunchyk** [comment]
@molinadavid @shazron Oh yeah, thank you guys! I renamed my Ukrainian name to English name and it worked! Yay!

**Comment by sergeychernyshev** [comment]
Hitting same problem - name of my app is in cyrillics and I get AMDeviceSecureTransferPath error. XCode works fine.

**Comment by pluswave** [comment]
same issue on my env. 


localhost:~ $ sw_vers -productVersion
10.10.4
localhost:~ $ ios-deploy -V
1.7.0
localhost:~ $ xcodebuild -version
Xcode 6.4
Build version 6E35b
localhost:~ $ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
localhost:~ $ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix
localhost:~ $  lldb --version
lldb-330.0.48

**Comment by jackytse** [comment]
localhost:~ $ sw_vers -productVersion
10.10.5
localhost:~ $ ios-deploy -V
1.7.0
localhost:~ $ xcodebuild -version
Xcode 6.4
Build version 6E35b
localhost:~ $ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
localhost:~ $ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
localhost:~ $ lldb --version
lldb-330.0.48

the same error.
