### ISSUE TITLE
Args not passed.

### ISSUE THREAD

**Issue by sbankhead** [phonegap/ios-deploy#7]
So I was noticing that it seems like the arguments were not being passed through after the changes to use lldb.  Was there a fix planned for this.

Also noticed in testing that we were having issues launching apps on older iphone4's running 6.1.3 OS.  Very inconsistent, sometimes the app would launch and hang immediately.  Anyone else seeing the same issues?

**Comment by shazron** [comment]
Is this still a problem? Re-open if so.
