### ISSUE TITLE
[ !! ] Unable to mount developer disk image. (e8000033)

### ISSUE THREAD

**Issue by companje** [phonegap/ios-deploy#73]
Hi there,

After installing OSX Yosemite and Xcode 6.1 the debugger won't start. I already re-installed phonegap and ios-deploy and also tried to start from scratch with a HelloWorld (`phonegap create wouter2`) project.

I hope you can help.

Here's a part of the log:

```
.....
[100%] Installed package /Users/rick/Sites/wouter2/platforms/ios/build/device/HelloWorld.app
------ Debug phase ------
Starting debug of Unknown Device 'iPhone van Rick Companje' (7277d8d3db401932a4ccc60621ab7335ef5131d2) connected through USB...
Device support path: /Users/rick/Library/Developer/Xcode/iOS DeviceSupport/8.0.2 (12A405)
Developer disk image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/8.1 (12B411)/DeveloperDiskImage.dmg
[  0%] Looking up developer disk image
[ !! ] Unable to mount developer disk image. (e8000033)
```

I run the following versions:

```
sw_vers -productVersion
10.10

ios-deploy -V
1.2.0

xcodebuild -version
Xcode 6.1
Build version 6A1052d

xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix

lldb --version
lldb-320.4.152
```

**Comment by fifafu** [comment]
I'm having the same issue again with iOS 8.3, XCode 6.3.1 and ios-deploy 1.5.0. Does anybody also see this?

**Comment by atarinerd80** [comment]
I'm also having this issue with iOS 8.3 and XCode 6.3.1. Just upgraded iPad and XCode today, and can't get the app to deploy with Cordova

**Comment by shazron** [comment]
Hmm. @atarinerd80 I just created a new project and deployed using ios-deploy 1.5.0, cordova-cli 5.0.0 and Xcode 6.3.1 installed. What are the exact issues you are encountering?

@fifafu do you still have the problem, anything new you can add?

**Comment by haxpor** [comment]
@fifafu @atarinerd80 I have the same issue with iOS 8.4, and XCode 8.4. Turn out shutting down your phone and start it over can fix the problem. See https://github.com/phonegap/ios-deploy/issues/155.

**Comment by ibc** [comment]
Same here:
* ios-deplay 1.7.0
* cordova-cli 5.0.0
* Xcode 6.4 (6E35b)

This just happens since I updated Xcode.

**Comment by andrevabo** [comment]
Same issue with iOS 8.4.

* ios-deploy 1.7.0
* cordova-cli 5.0.0
* Xcode 6.3.2 (6D2105)

Restarting the phone didn't help.

**Comment by shazron** [comment]
Thanks for all the info! Phew :)

**Comment by ram54288** [comment]
Facing this issue with iOS 8.4 device and XCode 6.4

**Comment by markshep** [comment]
I had this with Xcode 6.4 and an iPad running iOS 8.3.  Rebooting the iPad fixed it.

**Comment by AlexandreRozier** [comment]
Xcode 8
IOS10

I had this issue and rebooting the device made the image mount. Hope this will help !

**Comment by kai-sarawut** [comment]
@AlexandreRozier you helped me out!

**Comment by MatissAndersons** [comment]
It's 2019 and still the best advice is to restart the device. Thanks @AlexandreRozier! 😄

**Comment by BARNZ** [comment]
2021 and had the same issue today with the upgrade to ios 14.4. Thanks @AlexandreRozier
