### ISSUE TITLE
ios-deploy does not exit when the app quits with noninteractive flag

### ISSUE THREAD

**Issue by doris1234** [phonegap/ios-deploy#82]
With the noninteractive flag, ios-deploy does not exit when the app quits. When I manually quit the app on the phone, I do see 'Process 227 stopped' in the output from ios-deploy and some other output, but ios-deploy does not actually exit.

$ ./ios-deploy -I -d --bundle /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app
[....] Waiting for iOS device to be connected
[....] Using (null) (f37ebb7f52306c583959a946efe8e08a1169319b).
------ Install phase ------
[  0%] Found (null) connected through USB, beginning install
[  5%] Copying /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app/META-INF/ to device
[  6%] Copying /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app/META-INF/com.apple.ZipMetadata.plist to device
[  8%] Copying /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app/_CodeSignature/ to device
[  9%] Copying /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app/_CodeSignature/CodeResources to device
[ 12%] Copying /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app/Base.lproj/ to device
[ 14%] Copying /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app/Base.lproj/LaunchScreen.nib to device
[ 16%] Copying /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app/Base.lproj/Main.storyboardc/ to device
[ 17%] Copying /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app/Base.lproj/Main.storyboardc/Info.plist to device
[ 19%] Copying /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app/Base.lproj/Main.storyboardc/UIViewController-vXZ-lx-hvc.nib to device
[ 21%] Copying /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app/Base.lproj/Main.storyboardc/vXZ-lx-hvc-view-kh9-bI-dsS.nib to device
[ 23%] Copying /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app/embedded.mobileprovision to device
[ 27%] Copying /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app/Info.plist to device
[ 29%] Copying /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app/PkgInfo to device
[ 31%] Copying /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app/MyApp to device
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
[ 75%] CreatingContainer
[ 80%] InstallingApplication
[ 85%] PostflightingApplication
[ 90%] SandboxingApplication
[ 95%] GeneratingApplicationMap
[100%] Installed package /Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app
------ Debug phase ------
Starting debug of (null) connected through USB...
[  0%] Looking up developer disk image
[ 95%] Developer disk image mounted successfully
[100%] Connecting to remote debug server
-------------------------
(lldb) command source -s 0 '/tmp/fruitstrap-lldb-prep-cmds-f37ebb7f52306c583959a946efe8e08a1169319b'
Executing commands in '/private/tmp/fruitstrap-lldb-prep-cmds-f37ebb7f52306c583959a946efe8e08a1169319b'.
(lldb)     platform select remote-ios --sysroot '/Users/dor/Library/Developer/Xcode/iOS DeviceSupport/8.1 (12B411)/Symbols'
  Platform: remote-ios
 Connected: no
  SDK Path: "/Users/dor/Library/Developer/Xcode/iOS DeviceSupport/8.1 (12B411)/Symbols"
(lldb)     target create "/Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app"
Current executable set to '/Users/dor/Library/Developer/Xcode/DerivedData/MyApp-anvjyburnjylergffvnjzwcfdidd/Build/Products/Debug-iphoneos/MyApp.app' (armv7).
(lldb)     script fruitstrap_device_app="/private/var/mobile/Containers/Bundle/Application/213F8167-DD91-49D4-A9F8-69F342E9E770/MyApp.app"
(lldb)     script fruitstrap_connect_url="connect://127.0.0.1:12345"
(lldb)     command script import "/tmp/fruitstrap_f37ebb7f52306c583959a946efe8e08a1169319b.py"
(lldb)     command script add -f fruitstrap_f37ebb7f52306c583959a946efe8e08a1169319b.connect_command connect
(lldb)     command script add -s asynchronous -f fruitstrap_f37ebb7f52306c583959a946efe8e08a1169319b.run_command run
(lldb)     command script add -s asynchronous -f fruitstrap_f37ebb7f52306c583959a946efe8e08a1169319b.autoexit_command autoexit
(lldb)     command script add -s asynchronous -f fruitstrap_f37ebb7f52306c583959a946efe8e08a1169319b.safequit_command safequit
(lldb)     connect
Process 0 connected
(lldb)     run
Process 227 stopped
success
(lldb)     autoexit
Process 227 stopped
* thread #1: tid = 0x2370, 0x371144f0 libsystem_kernel.dylib`mach_msg_trap + 20, queue = 'com.apple.main-thread', stop reason = signal SIGKILL
    frame #0: 0x371144f0 libsystem_kernel.dylib`mach_msg_trap + 20
libsystem_kernel.dylib`mach_msg_trap + 20:
-> 0x371144f0:  pop    {r4, r5, r6, r8}
   0x371144f4:  bx     lr

libsystem_kernel.dylib`mach_msg_overwrite_trap:
   0x371144f8:  mov    r12, sp
   0x371144fc:  push   {r4, r5, r6, r8}

**Comment by alk3ovation** [comment]
I'm seeing the behavior described above and I'm on version 1.3.2. I'm running ios-deploy from Terminal on mac. I have XCode 6.1.1 installed. The app launches fine but if I manually kill the app on the device, the terminal window prints:

Process 128 stopped
* thread #1: tid = 0x0694, 0x3be89a50 libsystem_kernel.dylib`mach_msg_trap + 20, queue = 'com.apple.main-thread', stop reason = signal SIGKILL
    frame #0: 0x3be89a50 libsystem_kernel.dylib`mach_msg_trap + 20
libsystem_kernel.dylib`mach_msg_trap + 20:
-> 0x3be89a50:  pop    {r4, r5, r6, r8}
   0x3be89a54:  bx     lr

libsystem_kernel.dylib`mach_msg_overwrite_trap:
   0x3be89a58:  mov    r12, sp
   0x3be89a5c:  push   {r4, r5, r6, r8}

But the terminal just hangs there after that and doesn't do anything. I would expect the ios-deploy process to end and go back to a prompt.

**Comment by nihalsid** [comment]
@alk3ovation @shazron  I am facing the same problem, any workaround to this? I'm on version 1.3.2

**Comment by alk3ovation** [comment]
I actually found that our game wasn't exiting cleanly and was stuck waiting on a thread. Since there's no watchdog when connected to the debugger, it was never killed and just sat there waiting.

**Comment by shazron** [comment]
@nihalsid the latest is version 1.5.0, try that.
