### ISSUE TITLE
EXC_BAD_ACCESS (SIGSEGV) KERN_INVALID_ADDRESS at 0x0000000000000000

### ISSUE THREAD

**Issue by Marshall-L-D** [phonegap/ios-deploy#90]
Using Cordova 4.0.0.  Attempting to run "cordova run ios" on a simple project.  Runs fine in simulator and runs okay if I open the project in XCODE and run on iPad2.  Let me know if you need more information or have suggestions.

Thanks.

>sw_vers -productVersion
10.9.5

>ios-deploy -V
1.3.2

>xcodebuild -version
Xcode 6.1.1
Build version 6A2008a

>xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

>gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

>lldb --version
lldb-320.4.156

>ios-deploy command line (near as I can tell, I am just running "cordova run ios")
myData/testpg/hello/platforms/ios/cordova/run: line 116:  3449 Segmentation fault: 11  ios-deploy -d -b "$DEVICE_APP_PATH"

Path:            /usr/local/lib/node_modules/ios-deploy/ios-deploy
Identifier:      ios-deploy
Version:         0
Code Type:       X86-64 (Native)
Parent Process:  bash [3611]
Responsible:     Terminal [571]
User ID:         501

Date/Time:       2014-12-10 17:43:56.610 -0500
OS Version:      Mac OS X 10.9.5 (13F34)
Report Version:  11
Anonymous UUID:  86EC5125-9DC6-A3F2-CA43-0CF53228903E

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000000

VM Regions Near 0:
--> 
    __TEXT                 0000000102e60000-0000000102e6b000 [   44K] r-x/rwx SM=COW  /usr/local/lib/node_modules/ios-deploy/ios-deploy

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fff8ea96a1f CFStringGetLength + 15
1   com.apple.CoreFoundation      	0x00007fff8eaa9c18 CFStringCompare + 24
2   ios-deploy                    	0x0000000102e618d0 get_device_hardware_name + 80
3   ios-deploy                    	0x0000000102e6230a get_device_full_name + 106
4   ios-deploy                    	0x0000000102e66503 handle_device + 51
5   ios-deploy                    	0x0000000102e670e9 device_callback + 105
6   com.apple.mobiledevice        	0x0000000102efa3a9 _AMDDeviceAttachedCallbackv3 + 157
7   com.apple.mobiledevice        	0x0000000102e8715c _USBMuxCustomRunLoopSourcePerformCallback + 1416
8   com.apple.CoreFoundation      	0x00007fff8eb035b1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
9   com.apple.CoreFoundation      	0x00007fff8eaf4c62 __CFRunLoopDoSources0 + 242
10  com.apple.CoreFoundation      	0x00007fff8eaf43ef __CFRunLoopRun + 831
11  com.apple.CoreFoundation      	0x00007fff8eaf3e75 CFRunLoopRunSpecific + 309
12  com.apple.CoreFoundation      	0x00007fff8eba9811 CFRunLoopRun + 97
13  ios-deploy                    	0x0000000102e67799 main + 1193
14  libdyld.dylib                 	0x00007fff955255fd start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff93e42e6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8c298f08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff8c29bfb9 start_wqthread + 13

Thread 2:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib        	0x00007fff93e43662 kevent64 + 10
1   libdispatch.dylib             	0x00007fff8af32421 _dispatch_mgr_invoke + 239
2   libdispatch.dylib             	0x00007fff8af32136 _dispatch_mgr_thread + 52

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff93e42e6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8c298f08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff8c29bfb9 start_wqthread + 13

Thread 4:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	0x00007fff93e429aa __select + 10
1   com.apple.CoreFoundation      	0x00007fff8eb40a03 __CFSocketManager + 867
2   libsystem_pthread.dylib       	0x00007fff8c297899 _pthread_body + 138
3   libsystem_pthread.dylib       	0x00007fff8c29772a _pthread_start + 137
4   libsystem_pthread.dylib       	0x00007fff8c29bfc9 thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000010
  rdi: 0x0000000000000000  rsi: 0x0000000102e6b690  rbp: 0x00007fff5cd9e600  rsp: 0x00007fff5cd9e5f0
   r8: 0x0000000000000040   r9: 0x00007fff5cd9e300  r10: 0x000000001d1b7a23  r11: 0x00000000a8394ff0
  r12: 0x00007f98c2d103c0  r13: 0x00007fff5cd9ea50  r14: 0x0000000000000010  r15: 0x0000000102e6b690
  rip: 0x00007fff8ea96a1f  rfl: 0x0000000000010246  cr2: 0x0000000000000000
  
Logical CPU:     4
Error Code:      0x00000004
Trap Number:     14

Binary Images:
       0x102e60000 -        0x102e6afff +ios-deploy (0) <831E864D-CD79-3964-B637-729DBAA95050> /usr/local/bin/ios-deploy
       0x102e79000 -        0x102f91fff  com.apple.mobiledevice (757.1.5.0.2 - 757.1.5.0.2) <364C6894-934B-3844-A77F-7DFEC21F8AEE> /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
    0x7fff618a6000 -     0x7fff618d9817  dyld (239.4) <7AD43B9B-5CEA-3C7E-9836-A06909F9CA56> /usr/lib/dyld
    0x7fff8ae27000 -     0x7fff8ae3eff7  com.apple.CFOpenDirectory (10.9 - 173.90.1) <7BC0194E-1B40-3FCA-ACD2-235CE5D65DFA> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fff8af2f000 -     0x7fff8af49fff  libdispatch.dylib (339.92.1) <C4E4A18D-3C3B-3C9C-8709-A4270D998DE7> /usr/lib/system/libdispatch.dylib
    0x7fff8af4c000 -     0x7fff8af5dff7  libsystem_asl.dylib (217.1.4) <655FB343-52CF-3E2F-B14D-BEBF5AAEF94D> /usr/lib/system/libsystem_asl.dylib
    0x7fff8af5e000 -     0x7fff8afacff9  libstdc++.6.dylib (60) <0241E6A4-1368-33BE-950B-D0A175C41F54> /usr/lib/libstdc++.6.dylib
    0x7fff8b0b5000 -     0x7fff8b0eaffc  com.apple.LDAPFramework (2.4.28 - 194.5) <4ADD0595-25B9-3F09-897E-3FB790AD2C5A> /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP
    0x7fff8b3ee000 -     0x7fff8b407ff7  com.apple.Kerberos (3.0 - 1) <F108AFEB-198A-3BAF-BCA5-9DFCE55EFF92> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
    0x7fff8b4f2000 -     0x7fff8b4f2fff  com.apple.Accelerate (1.9 - Accelerate 1.9) <509BB27A-AE62-366D-86D8-0B06D217CF56> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff8b637000 -     0x7fff8b6e7ff7  libvMisc.dylib (423.32) <049C0735-1808-39B9-943F-76CB8021744F> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
    0x7fff8baf3000 -     0x7fff8bb7eff7  libCoreStorage.dylib (380.70.2) <BD993BC8-ED54-3DC1-B28B-3B6AC77E8E5C> /usr/lib/libCoreStorage.dylib
    0x7fff8bb7f000 -     0x7fff8bbb3fff  libssl.0.9.8.dylib (52) <51C844FF-D7CD-3525-9ABB-84B8DD11D5E4> /usr/lib/libssl.0.9.8.dylib
    0x7fff8bc52000 -     0x7fff8bc6efff  libresolv.9.dylib (54) <11C2C826-F1C6-39C6-B4E8-6E0C41D4FA95> /usr/lib/libresolv.9.dylib
    0x7fff8bc6f000 -     0x7fff8bc70ff7  libSystem.B.dylib (1197.1.1) <70B235FC-BCED-367B-BA6C-67C299BAE7D9> /usr/lib/libSystem.B.dylib
    0x7fff8bf38000 -     0x7fff8bf61ff7  libc++abi.dylib (49.1) <21A807D3-6732-3455-B77F-743E9F916DF0> /usr/lib/libc++abi.dylib
    0x7fff8bf63000 -     0x7fff8bfc8ffb  com.apple.Heimdal (4.0 - 2.0) <F34D6627-9F80-3823-8B57-DB629307DF87> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
    0x7fff8c028000 -     0x7fff8c043ff7  libsystem_malloc.dylib (23.10.1) <A695B4E4-38E9-332E-A772-29D31E3F1385> /usr/lib/system/libsystem_malloc.dylib
    0x7fff8c0fe000 -     0x7fff8c150fff  libc++.1.dylib (120) <4F68DFC5-2077-39A8-A449-CAC5FDEE7BDE> /usr/lib/libc++.1.dylib
    0x7fff8c19b000 -     0x7fff8c1b6ff7  libCRFSuite.dylib (34) <FFAE75FA-C54E-398B-AA97-18164CD9789D> /usr/lib/libCRFSuite.dylib
    0x7fff8c1b7000 -     0x7fff8c240ff7  libsystem_c.dylib (997.90.3) <6FD3A400-4BB2-3B95-B90C-BE6E9D0D78FA> /usr/lib/system/libsystem_c.dylib
    0x7fff8c241000 -     0x7fff8c24cff7  com.apple.NetAuth (5.0 - 5.0) <C811E662-9EC3-3B74-808A-A75D624F326B> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fff8c24d000 -     0x7fff8c27efff  com.apple.MediaKit (15 - 709) <23E33409-5C39-3F93-9E73-2B0E9EE8883E> /System/Library/PrivateFrameworks/MediaKit.framework/Versions/A/MediaKit
    0x7fff8c296000 -     0x7fff8c29dff7  libsystem_pthread.dylib (53.1.4) <AB498556-B555-310E-9041-F67EC9E00E2C> /usr/lib/system/libsystem_pthread.dylib
    0x7fff8c29e000 -     0x7fff8c29effd  libOpenScriptingUtil.dylib (157) <19F0E769-0989-3062-9AFB-8976E90E9759> /usr/lib/libOpenScriptingUtil.dylib
    0x7fff8c29f000 -     0x7fff8c2a4fff  com.apple.DiskArbitration (2.6 - 2.6) <A4165553-770E-3D27-B217-01FC1F852B87> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff8c386000 -     0x7fff8c388ffb  libutil.dylib (34) <DAC4A6CF-A1BB-3874-9569-A919316D30E8> /usr/lib/libutil.dylib
    0x7fff8c389000 -     0x7fff8c38eff7  libunwind.dylib (35.3) <78DCC358-2FC1-302E-B395-0155B47CB547> /usr/lib/system/libunwind.dylib
    0x7fff8c394000 -     0x7fff8c47bff7  libxml2.2.dylib (26) <A1DADD11-89E5-3DE4-8802-07186225967F> /usr/lib/libxml2.2.dylib
    0x7fff8c544000 -     0x7fff8c6dfff8  com.apple.CFNetwork (673.5 - 673.5) <EF4DA617-D442-327A-9575-A75111A0A742> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff8c6e0000 -     0x7fff8c6e6ff7  libsystem_platform.dylib (24.90.1) <3C3D3DA8-32B9-3243-98EC-D89B9A1670B3> /usr/lib/system/libsystem_platform.dylib
    0x7fff8dc61000 -     0x7fff8dc62fff  libsystem_sandbox.dylib (278.11.1) <0D0B13EA-6B7A-3AC8-BE60-B548543BEB77> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff8dc81000 -     0x7fff8dc81ff7  libkeymgr.dylib (28) <3AA8D85D-CF00-3BD3-A5A0-E28E1A32A6D8> /usr/lib/system/libkeymgr.dylib
    0x7fff8dd84000 -     0x7fff8dd86ff7  libquarantine.dylib (71) <7A1A2BCB-C03D-3A25-BFA4-3E569B2D2C38> /usr/lib/system/libquarantine.dylib
    0x7fff8dd87000 -     0x7fff8dd89ff3  libsystem_configuration.dylib (596.15) <4998CB6A-9D54-390A-9F57-5D1AC53C135C> /usr/lib/system/libsystem_configuration.dylib
    0x7fff8de79000 -     0x7fff8e0ddffd  com.apple.security (7.0 - 55471.14.21) <B3C61C91-E9D6-3A3C-99CF-665D54D13C34> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff8e127000 -     0x7fff8e127fff  com.apple.Accelerate.vecLib (3.9 - vecLib 3.9) <F8D0CC77-98AC-3B58-9FE6-0C25421827B6> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    0x7fff8e128000 -     0x7fff8e129ff7  libsystem_blocks.dylib (63) <FB856CD1-2AEA-3907-8E9B-1E54B6827F82> /usr/lib/system/libsystem_blocks.dylib
    0x7fff8e12a000 -     0x7fff8e134ff7  com.apple.bsd.ServiceManagement (2.0 - 2.0) <2D27B498-BB9C-3D88-B05A-76908A8A26F3> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff8e2dd000 -     0x7fff8e36dff7  com.apple.Metadata (10.7.0 - 800.28) <04D510EA-1169-392F-9702-EE7EB00882E6> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fff8e3d7000 -     0x7fff8e3dbff7  libheimdal-asn1.dylib (323.92.1) <CAE21FFF-5763-399C-B7C5-EEBFFEEF2242> /usr/lib/libheimdal-asn1.dylib
    0x7fff8e40c000 -     0x7fff8e40dfff  com.apple.TrustEvaluationAgent (2.0 - 25) <334A82F4-4AE4-3719-A511-86D0B0723E2B> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
    0x7fff8e40e000 -     0x7fff8e415fff  com.apple.NetFS (6.0 - 4.0) <8E26C099-CE9D-3819-91A2-64EA929C6137> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
    0x7fff8e41f000 -     0x7fff8e496fff  com.apple.CoreServices.OSServices (600.4 - 600.4) <5A44F0B5-4A24-3875-ADE4-5B47D6C7E251> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fff8e73a000 -     0x7fff8e743ffd  com.apple.CommonAuth (4.0 - 2.0) <32BA436F-6319-3A0B-B5D2-2EB75FF36B5B> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
    0x7fff8ea84000 -     0x7fff8ec69fff  com.apple.CoreFoundation (6.9 - 855.17) <729BD6DA-1F63-3E72-A148-26F21EBF52BB> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff8ec6a000 -     0x7fff8ec71ff8  liblaunch.dylib (842.92.1) <A40A0C7B-3216-39B4-8AE0-B5D3BAF1DA8A> /usr/lib/system/liblaunch.dylib
    0x7fff8edaf000 -     0x7fff8edbafff  libkxld.dylib (2422.115.4) <3C678B75-F7C5-3DBB-8DBD-48483AD54D5C> /usr/lib/system/libkxld.dylib
    0x7fff8f01d000 -     0x7fff8f027fff  libcommonCrypto.dylib (60049) <8C4F0CA0-389C-3EDC-B155-E62DD2187E1D> /usr/lib/system/libcommonCrypto.dylib
    0x7fff8f028000 -     0x7fff8f083ffb  com.apple.AE (665.5 - 665.5) <BBA230F9-144C-3CAB-A77A-0621719244CD> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fff8f084000 -     0x7fff8f0d5ff7  com.apple.audio.CoreAudio (4.2.1 - 4.2.1) <BE13E840-FB45-3BC2-BCF5-031629754FD5> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff8f129000 -     0x7fff8f133ff7  libcsfde.dylib (380.70.2) <3ACB87D7-A81C-3C45-B648-AD27F1B9D841> /usr/lib/libcsfde.dylib
    0x7fff8f134000 -     0x7fff8f1a1fff  com.apple.SearchKit (1.4.0 - 1.4.0) <B9B8D510-A27E-36B0-93E9-17146D9E9045> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fff8f5d7000 -     0x7fff8f5defff  libcompiler_rt.dylib (35) <4CD916B2-1B17-362A-B403-EF24A1DAC141> /usr/lib/system/libcompiler_rt.dylib
    0x7fff8f624000 -     0x7fff8f628ff7  libsystem_stats.dylib (93.90.3) <C588E082-D94B-3510-9F9A-7AD83B3402DE> /usr/lib/system/libsystem_stats.dylib
    0x7fff8f68e000 -     0x7fff8f69fff7  libz.1.dylib (53) <42E0C8C6-CA38-3CA4-8619-D24ED5DD492E> /usr/lib/libz.1.dylib
    0x7fff8f6b8000 -     0x7fff8f6bfffb  libcopyfile.dylib (103.92.1) <CF29DFF6-0589-3590-834C-82E2316612E8> /usr/lib/system/libcopyfile.dylib
    0x7fff8f824000 -     0x7fff8f8eeff7  com.apple.LaunchServices (572.28 - 572.28) <FC72C089-A069-3374-B80A-E041AF149F24> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fff8fbd7000 -     0x7fff8fbfeffb  libsystem_info.dylib (449.1.3) <7D41A156-D285-3849-A2C3-C04ADE797D98> /usr/lib/system/libsystem_info.dylib
    0x7fff8fc91000 -     0x7fff8fe49ffb  libicucore.A.dylib (511.35) <6F097DA7-147C-32A1-93D2-728A64CF0DC2> /usr/lib/libicucore.A.dylib
    0x7fff8fee6000 -     0x7fff8fee7fff  libunc.dylib (28) <62682455-1862-36FE-8A04-7A6B91256438> /usr/lib/system/libunc.dylib
    0x7fff9029e000 -     0x7fff9040cff7  libBLAS.dylib (1094.5) <DE93A590-5FA5-32A2-A16C-5D7D7361769F> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    0x7fff9040d000 -     0x7fff9040ffff  com.apple.EFILogin (2.0 - 2) <8D651894-B7AD-3F23-9B93-472EEA3D292F> /System/Library/PrivateFrameworks/EFILogin.framework/Versions/A/EFILogin
    0x7fff90f14000 -     0x7fff90f40fff  com.apple.CoreServicesInternal (184.9 - 184.9) <4DEA54F9-81D6-3EDB-AA3C-1F9C497B3379> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7fff90ff0000 -     0x7fff91000ffb  libsasl2.2.dylib (170) <C8E25710-68B6-368A-BF3E-48EC7273177B> /usr/lib/libsasl2.2.dylib
    0x7fff91005000 -     0x7fff91053fff  libcorecrypto.dylib (161.1) <F3973C28-14B6-3006-BB2B-00DD7F09ABC7> /usr/lib/system/libcorecrypto.dylib
    0x7fff91054000 -     0x7fff910c0fff  com.apple.framework.IOKit (2.0.1 - 907.100.13) <057FDBA3-56D6-3903-8C0B-849214BF1985> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff910c3000 -     0x7fff911adfff  libsqlite3.dylib (158) <00269BF9-43BE-39E0-9C85-24585B9923C8> /usr/lib/libsqlite3.dylib
    0x7fff91d3c000 -     0x7fff91d3dffb  libremovefile.dylib (33) <3543F917-928E-3DB2-A2F4-7AB73B4970EF> /usr/lib/system/libremovefile.dylib
    0x7fff91eb2000 -     0x7fff91f83ff1  com.apple.DiskImagesFramework (10.9 - 371.1) <DCCAADEC-35D5-3968-8B39-358ACC56ADC4> /System/Library/PrivateFrameworks/DiskImages.framework/Versions/A/DiskImages
    0x7fff91f99000 -     0x7fff91fc2fff  com.apple.DictionaryServices (1.2 - 208) <A539A058-BA57-35EE-AA08-D0B0E835127D> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fff91fc3000 -     0x7fff91fc8fff  libmacho.dylib (845) <1D2910DF-C036-3A82-A3FD-44FF73B5FF9B> /usr/lib/system/libmacho.dylib
    0x7fff91fc9000 -     0x7fff9200efff  libcurl.4.dylib (78.94.1) <88F27F9B-052E-3375-938D-2603E90D8AD5> /usr/lib/libcurl.4.dylib
    0x7fff92099000 -     0x7fff9209dfff  libpam.2.dylib (20) <B93CE8F5-DAA8-30A1-B1F6-F890509513CB> /usr/lib/libpam.2.dylib
    0x7fff9209e000 -     0x7fff920a7ffb  libsystem_notify.dylib (121.20.1) <9B34B4FE-F5AD-3F09-A5F0-46AFF3571323> /usr/lib/system/libsystem_notify.dylib
    0x7fff92414000 -     0x7fff92443ff9  com.apple.GSS (4.0 - 2.0) <44E914BE-B0D0-3E05-9451-CA9E539AFA52> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
    0x7fff92444000 -     0x7fff92451ff0  libbz2.1.0.dylib (29) <0B98AC35-B138-349C-8063-2B987A75D24C> /usr/lib/libbz2.1.0.dylib
    0x7fff92856000 -     0x7fff9290eff7  com.apple.DiscRecording (8.0 - 8000.4.6) <CDAAAD04-A1D0-3C67-ABCC-EFC9E8D44E7E> /System/Library/Frameworks/DiscRecording.framework/Versions/A/DiscRecording
    0x7fff9290f000 -     0x7fff9290ffff  com.apple.CoreServices (59 - 59) <7A697B5E-F179-30DF-93F2-8B503CEEEFD5> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff92918000 -     0x7fff92920fff  libsystem_dnssd.dylib (522.92.1) <3F8C6A07-3046-3E88-858F-D9CEFC43A405> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff92ee8000 -     0x7fff92ef8fff  libbsm.0.dylib (33) <2CAC00A2-1352-302A-88FA-C567D4D69179> /usr/lib/libbsm.0.dylib
    0x7fff92ef9000 -     0x7fff92f1dfff  libxpc.dylib (300.90.2) <AB40CD57-F454-3FD4-B415-63B3C0D5C624> /usr/lib/system/libxpc.dylib
    0x7fff930f8000 -     0x7fff930f9fff  liblangid.dylib (117) <9546E641-F730-3AB0-B3CD-E0E2FDD173D9> /usr/lib/liblangid.dylib
    0x7fff930fa000 -     0x7fff93129fd2  libsystem_m.dylib (3047.16) <B7F0E2E4-2777-33FC-A787-D6430B630D54> /usr/lib/system/libsystem_m.dylib
    0x7fff93a3c000 -     0x7fff93d3cff7  com.apple.Foundation (6.9 - 1056.16) <24349208-3603-3F5D-95CC-B379616FBEF8> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff93d41000 -     0x7fff93e1dfff  libcrypto.0.9.8.dylib (52) <ED7F3865-10D4-346B-8C9C-D968EB3B5D35> /usr/lib/libcrypto.0.9.8.dylib
    0x7fff93e1f000 -     0x7fff93e2cff7  libxar.1.dylib (202) <5572AA71-E98D-3FE1-9402-BB4A84E0E71E> /usr/lib/libxar.1.dylib
    0x7fff93e2d000 -     0x7fff93e49ff7  libsystem_kernel.dylib (2422.115.4) <9EDE872E-2A9E-3A78-8E1D-AB790794A098> /usr/lib/system/libsystem_kernel.dylib
    0x7fff93e4a000 -     0x7fff9422bffe  libLAPACK.dylib (1094.5) <7E7A9B8D-1638-3914-BAE0-663B69865986> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    0x7fff944b3000 -     0x7fff94607ff3  com.apple.audio.toolbox.AudioToolbox (1.10 - 1.10) <69B273E8-5A8E-3FC7-B807-C16B657662FE> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff946a9000 -     0x7fff946d0ff7  libsystem_network.dylib (241.3) <8B1E1F1D-A5CC-3BAE-8B1E-ABC84337A364> /usr/lib/system/libsystem_network.dylib
    0x7fff946d1000 -     0x7fff946d7fff  com.apple.AOSNotification (1.7.0 - 760.3) <7901B867-60F7-3645-BB3E-18C51A6FBCC6> /System/Library/PrivateFrameworks/AOSNotification.framework/Versions/A/AOSNotification
    0x7fff946fa000 -     0x7fff9475dffb  com.apple.SystemConfiguration (1.13.1 - 1.13.1) <339A2A90-DA25-33AF-88E5-2FB38A758FEE> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff94b92000 -     0x7fff94b9effb  com.apple.AppleFSCompression (56.92.1 - 1.0) <066255FD-DBD1-3041-8DDA-7AFC41C9096D> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
    0x7fff94e60000 -     0x7fff94ed3fff  com.apple.securityfoundation (6.0 - 55122.3) <0FDC8F53-104C-3938-A852-5B33C30BAAD5> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
    0x7fff95515000 -     0x7fff95521ff7  com.apple.OpenDirectory (10.9 - 173.90.1) <F08601E8-F7E8-3222-AD05-6A26003779CF> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
    0x7fff95522000 -     0x7fff95525ff7  libdyld.dylib (239.4) <41077DD7-F909-3B8A-863E-72AE304EDE13> /usr/lib/system/libdyld.dylib
    0x7fff9583b000 -     0x7fff95b25fff  com.apple.CoreServices.CarbonCore (1077.17 - 1077.17) <3A2E92FD-DEE2-3D45-9619-11500801A61C> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff95d78000 -     0x7fff95d7cff7  libcache.dylib (62) <BDC1E65B-72A1-3DA3-A57C-B23159CAAD0B> /usr/lib/system/libcache.dylib
    0x7fff95dc4000 -     0x7fff95decffb  libxslt.1.dylib (13) <C9794936-633C-3F0C-9E71-30190B9B41C1> /usr/lib/libxslt.1.dylib
    0x7fff95ded000 -     0x7fff95e51fff  com.apple.datadetectorscore (5.0 - 354.5) <C9FAB401-3FE2-3221-B60C-E4F1841CA5F1> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fff95f1c000 -     0x7fff961f0fc7  com.apple.vImage (7.0 - 7.0) <D241DBFA-AC49-31E2-893D-EAAC31890C90> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
    0x7fff96232000 -     0x7fff963dff27  libobjc.A.dylib (551.1) <AD7FD984-271E-30F4-A361-6B20319EC73B> /usr/lib/libobjc.A.dylib
    0x7fff97121000 -     0x7fff97122ff7  libDiagnosticMessagesClient.dylib (100) <4CDB0F7B-C0AF-3424-BC39-495696F0DB1E> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff9713d000 -     0x7fff97178fff  com.apple.bom (14.0 - 193.1) <EF24A562-6D3C-379E-8B9B-FAE0E4A0EF7C> /System/Library/PrivateFrameworks/Bom.framework/Versions/A/Bom
    0x7fff97179000 -     0x7fff971bbff7  libauto.dylib (185.5) <F45C36E8-B606-3886-B5B1-B6745E757CA8> /usr/lib/libauto.dylib
    0x7fff971bc000 -     0x7fff971bffff  com.apple.TCC (1.0 - 1) <32A075D9-47FD-3E71-95BC-BFB0D583F41C> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
    0x7fff975b2000 -     0x7fff9767dfff  libvDSP.dylib (423.32) <3BF732BE-DDE0-38EB-8C54-E4E3C64F77A7> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 10154
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=110.2M resident=119.0M(108%) swapped_out_or_unallocated=16777216.0T(15966248370176%)
Writable regions: Total=89.8M written=288K(0%) resident=2292K(2%) swapped_out=0K(0%) unallocated=87.5M(98%)
 
REGION TYPE                      VIRTUAL
===========                      =======
Dispatch continuations             16.0M
Kernel Alloc Once                     4K
MALLOC                             63.2M
MALLOC (admin)                       16K
MALLOC_LARGE (reserved)            1024K        reserved VM address space (unallocated)
STACK GUARD                        56.0M
Stack                              9372K
VM_ALLOCATE                          32K
__DATA                             4168K
__LINKEDIT                         66.4M
__TEXT                             43.8M
__UNICODE                           544K
shared memory                         4K
===========                      =======
TOTAL                             260.2M
TOTAL, minus reserved VM space    259.2M
 

Model: iMac12,2, BootROM IM121.0047.B1F, 4 processors, Intel Core i7, 3.4 GHz, 8 GB, SMC 1.72f2
Graphics: AMD Radeon HD 6970M, AMD Radeon HD 6970M, PCIe, 1024 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533643465238432D48392020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533643465238432D48392020
AirPort: spairport_wireless_card_type_airport_extreme (0x168C, 0x9A), Atheros 9380: 4.0.74.0-P2P
Bluetooth: Version 4.2.7f3 14616, 3 services, 23 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: Hitachi HDS723020BLA642, 2 TB
Serial ATA Device: OPTIARC DVD RW AD-5690H
USB Device: FaceTime HD Camera (Built-in)
USB Device: Hub
USB Device: iPad
USB Device: Microsoft Natural Keyboard Elite
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Hub
USB Device: INIC-1610P
USB Device: Internal Memory Card Reader
USB Device: IR Receiver
Thunderbolt Bus: iMac, Apple Inc., 25.1

**Comment by softBarbarian** [comment]
my ios-sim quits when running cordova run ios. With identical error in stacktrace and terminal output.
The issue started after upgrading my pone's ios from 8.1 to 8.1.2
iPhone 6 +, model: MGAL2LL/A
 cordova -v
4.1.2
ios-deploy -V
1.3.2

**Comment by softBarbarian** [comment]
do not remember if i mentioned by i am running Mac OS X 10.10.1

**Comment by softBarbarian** [comment]
I also noticed this in console output:
```
No device is connected, trying Simulator.
```

and then app start in iOS-simulator

system info:
```
OS: Mac OS X Yosemite
Node Version: v0.10.26
Cordova CLI: 3.5.0-0.2.7
Ionic Version: 1.0.0-beta.13
Ionic CLI Version: 1.3.0
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 2.0.1 
iOS-deploy: 1.3.1
```
