### ISSUE TITLE
Segmentation fault: 11  (core dumped) ios-deploy -d -b "$DEVICE_APP_PATH"

### ISSUE THREAD

**Issue by si458** [phonegap/ios-deploy#91]
Hi,
Every so often I get this error while using cordova or phonegap while using the command 
' cordova run --device ios '

/platforms/ios/cordova/run: line 116: 21476 Segmentation fault: 11  (core dumped) ios-deploy -d -b "$DEVICE_APP_PATH"

normally to fix this issue I just simply restart my laptop and away it goes again perfectly fine?

any ideas?

Simon

**Comment by andrest** [comment]
+1

**Comment by earslap** [comment]
I found this issue thread while looking for a solution myself. FWIW in my case, this exact same error was caused by a stray ios-deploy process. So running a:

    pkill ios-deploy

fixed the issue.

**Comment by softBarbarian** [comment]
`pkill iOS-deploy` does not fix the issue for me

**Comment by softBarbarian** [comment]
@shazron any eta on 1.4.0?

**Comment by earslap** [comment]
@softBarbarian just to make sure, did you try it with the correct capitalization? ie. not iOS-deploy but ios-deploy

**Comment by softBarbarian** [comment]
I am using cordova 4.2.0 to execute this script. So I do not specify the case. 

However, I am able to get it working by restarting the device!

**Comment by earslap** [comment]
Sorry I meant providing the correct case for killing the stray ios-deploy process (if it exists!) to get back on track (as a workaround) without dealing with restarts and all.

So Instead of

    pkill iOS-deploy

it should be:

    pkill ios-deploy

**Comment by davisford** [comment]
Hi, I'm building an [ionic app](http://ionicframework.com), and I'm seeing the same issue.  `pkill ios-deploy` is not fixing the issue for me

```sh
$ps aux | grep ios-deploy
davis            4256   0.0  0.0  2432772    672 s001  S+   12:04PM   0:00.00 grep ios-deploy
davis            4120   0.0  0.0  2519580    424 s001  S    12:01PM   0:00.00 ios-deploy -d -b /Users/davis/git/pos-mobile/platforms/ios/build/device/MyApp.app
$pkill ios-deploy
$ps aux | grep ios-deploy
davis            4272   0.0  0.0  2432772    672 s001  S+   12:05PM   0:00.00 grep ios-deploy

```

Here's a list of my global installs:

```sh
$npm ls -g --depth=0
/Users/davis/.nvm/v0.10.33/lib
├── bower@1.3.12
├── cordova@4.2.0
├── grunt-cli@0.1.13
├── gulp@3.8.11
├── ionic@1.3.10
├── ios-deploy@1.3.2
├── ios-sim@3.1.1
├── jshint@2.6.0
├── nodemon@1.3.7
├── npm@2.5.1
├── pm2@0.12.5
└── shelljs@0.3.0
```

Debug output when it fails:

```sh
etc...
(lldb)     script fruitstrap_connect_url="connect://127.0.0.1:12345"
(lldb)     command script import "/tmp/fruitstrap_ed0d16217360bc80107209aebca508bf6ac0fd19.py"
(lldb)     command script add -f fruitstrap_ed0d16217360bc80107209aebca508bf6ac0fd19.connect_command connect
(lldb)     command script add -s asynchronous -f fruitstrap_ed0d16217360bc80107209aebca508bf6ac0fd19.run_command run
(lldb)     command script add -s asynchronous -f fruitstrap_ed0d16217360bc80107209aebca508bf6ac0fd19.autoexit_command autoexit
(lldb)     command script add -s asynchronous -f fruitstrap_ed0d16217360bc80107209aebca508bf6ac0fd19.safequit_command safequit
(lldb)     connect
/Users/davis/git/pos-mobile/platforms/ios/cordova/run: line 116:  4067 Segmentation fault: 11  ios-deploy -d -b "$DEVICE_APP_PATH"
```

Is there any other workaround?

**Comment by JerrySievert** [comment]
+1 - any updates?

**Comment by tougher** [comment]
Any solution to this at all? I've tried installing 1.2.0 and `pkill ios-deploy` to no avail. Is iOS 8.1.3 to blame?

**Comment by tougher** [comment]
Actually mine is crashing at https://github.com/phonegap/ios-deploy/blob/33f6a83e1d94df5cf5041e9e16394409c4f63656/ios-deploy.c#L696 with a `EXC_BAD_ACCESS` from `CFDictionaryGetValue`.

The app gets installed on the device (I've tried several), always with this result:
```
[100%] Installed package app.ipa
------ Debug phase ------
Starting debug of iPhone 4S '.... iPhone' (...) connected through USB...
[  0%] Looking up developer disk image
[ 95%] Developer disk image mounted successfully
Segmentation fault: 11
```
Full crash log: https://gist.github.com/tougher/cc72b2f7c274b82121a3

**Comment by shazron** [comment]
see above commit
