### ISSUE TITLE
AMDeviceInstallApplication failed: 0xE8000051: Unknown error

### ISSUE THREAD

**Issue by TimRudy** [phonegap/ios-deploy#93]
I get error at Inspect Package phase (it seems):
  [ 49%] Copying ... to device
  [ 52%] CreatingStagingDirectory
  [ 57%] ExtractingPackage
  [ 60%] InspectingPackage
  AMDeviceInstallApplication failed: 0xE8000051: Unknown error.

Any variant of the commandline, doesn't seem to matter:
  ios-deploy --bundle myappbundle
  sudo ios-deploy --bundle myappbundle
  ios-deploy --uninstall --bundle myappbundle

where myappbundle does not have any non-Latin characters or any funny stuff! ;-)

- Xcode is able to deploy and run the app fine
- This works fine: cordova run —device
- This works fine: cordova run --emu
- Xcode is not running - lldb not running - Did Product Clean in Xcode and removed Derived artifacts, rebuilt, power cycled Mac and phone
- Finally one more thing: When using cordova as above, I get a popup "Do you want ‘ios-deploy’ to accept incoming network connections? This can be changed in firewall settings..." - Does not affect cordova run command - I tried "Allow" and I also tried "Deny"

Mac: 10.10.1
Xcode 6.1.1, Build version 6A2008a
cordova --version: 4.1.2
iPhone 5S running 8.1
ios-deploy --version: 1.3.2

Thanks!

**Comment by fatfatson** [comment]
same!!!!!!!

**Comment by shazron** [comment]
Firstly, is the signed .app package deployable using Xcode? Try that first, you might have not signed it properly.

**Comment by arpi0003** [comment]
I'm having the same issue :arrow_up:

**Comment by Fatme** [comment]
I had the same issue. The problem was that I didn't setup correctly my certificates and provisions. Also ensure that the device is included in provision.

**Comment by arpi0003** [comment]
@Fatme I'm building my IPA file with Shenzhen and I'm providing my distribution signing identity and correct provisioning profile, but something is still wrong with my setup.  I created an IPA through Xcode and that one installs via ios-deploy just fine, so nothing wrong with ios-deploy, just my IPA created through Shenzhen.  I'll keep digging, but doesn't appear to be an issue with ios-deploy

**Comment by shazron** [comment]
Re-open if this is still an issue.

**Comment by TimRudy** [comment]
The error 0xE8000051 is unique and I thought that someone could look where it is thrown in the code and offer that information - It's not very good for ios-deploy to say "Unknown error" and yet in my case and other people's cases Xcode has signed the app properly, and it is deployable. Could you take a quick look where 0xE8000051 comes from or what it is in decimal etc.?

**Comment by cbabos** [comment]
For me the problem was that the app was installed on the iPad from the Store, but I've tried to install it on the device from my computer. After I've deleted the Store-version from the device, I could install it from my computer with no problem at all

**Comment by TimRudy** [comment]
Your error was "0xE8000051"? I don't have my setup any more and can't reproduce, but this latest case suggests: This is possibly due to re-signing or re-naming your app. In which case the important thing is to delete existing artifact on phone. For Android that would be:


An existing package by the same name with a conflicting signature is already installed


But for iOS there is a huge litany of problems and I guess ios-deploy could never be enough of an Oracle to report error successfully. Bundle ID, signing, missing Entitlements, iOS bug regarding provisioning profiles, difference in missing images between iOS versions... See: http://stackoverflow.com/questions/25733299/ios-8-cant-install-enterprise-app?


Hope this helps.


~~Tim
________________________________
