### ISSUE TITLE
had ios-deploy working but not working or installing after yosemite upgrade

### ISSUE THREAD

**Issue by dreadstar** [phonegap/ios-deploy#97]
Hello,
as the subject says i had installed phonegap ios-deploy and ios-sim and was able to successfully call 
phonegap run i

after  upgrading to Yosemite, 
phonegap add ios
responds with:
 [warning] phonegap.js support will soon be removed.
 [warning] please replace 'phonegap.js' references with 'cordova.js'
[phonegap] adding phonegap.js to the ios platform
[phonegap] executing 'cordova run ios'...
Running command: /Users/tthomas/priceistruth-app3/platforms/ios/cordova/run 

Error: ios-deploy was not found. Please download, build and install version 1.2.0 or greater from https://github.com/phonegap/ios-deploy into your path. Or 'npm install -g ios-deploy' using node.js: http://nodejs.org/

Error: /Users/tthomas/priceistruth-app3/platforms/ios/cordova/run: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)

and
sudo npm install -g ios-deploy
responds with:
```
> ios-deploy@1.3.2 preinstall /usr/local/lib/node_modules/ios-deploy
> make ios-deploy

rm -rf *.app demo ios-deploy
gcc -ObjC -g -o ios-deploy -framework Foundation -framework CoreFoundation -framework MobileDevice -F/System/Library/PrivateFrameworks ios-deploy.c
couldn't understand kern.osversion `14.0.0'
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:55,
                 from /System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:12,
                 from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:80,
                 from ios-deploy.c:4:
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262: error: expected ',' or '}' before '__attribute__'
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414: error: expected ',' or '}' before '__attribute__'
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:119,
                 from ios-deploy.c:4:
/System/Library/Frameworks/Foundation.framework/Headers/NSUserActivity.h:55: error: expected a property attribute before 'weak'
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:171,
                 from ios-deploy.c:4:
/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:16: error: expected ',' or '}' before '__attribute__'
Makefile:19: recipe for target 'ios-deploy' failed
make: *** [ios-deploy] Error 1
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v0.10.29
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! ios-deploy@1.3.2 preinstall: `make ios-deploy`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ios-deploy@1.3.2 preinstall script 'make ios-deploy'.
npm ERR! This is most likely a problem with the ios-deploy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make ios-deploy
npm ERR! You can get their info via:
npm ERR!     npm owner ls ios-deploy
npm ERR! There is likely additional logging output above.


from npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'ios-deploy' ]
2 info using npm@2.1.18
3 info using node@v0.10.29
4 silly cache add args [ 'ios-deploy', null ]
5 verbose cache add spec ios-deploy
6 silly cache add parsed spec { raw: 'ios-deploy',
6 silly cache add   scope: null,
6 silly cache add   name: 'ios-deploy',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed ios-deploy@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'ios-deploy', range: '*', hasData: false }
11 silly mapToRegistry name ios-deploy
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/ios-deploy
15 verbose addNameRange registry:https://registry.npmjs.org/ios-deploy not in flight; fetching
16 verbose request uri https://registry.npmjs.org/ios-deploy
17 verbose request no auth needed
18 info attempt registry request try #1 at 19:02:59
19 verbose request id ff868615abcacdd5
20 verbose etag "4BVZDI35PTW2AJYEDUWWI7RKO"
21 http request GET https://registry.npmjs.org/ios-deploy
22 http 304 https://registry.npmjs.org/ios-deploy
23 silly get cb [ 304,
23 silly get   { date: 'Mon, 12 Jan 2015 00:02:59 GMT',
23 silly get     server: 'Apache',
23 silly get     via: '1.1 varnish',
23 silly get     'last-modified': 'Mon, 12 Jan 2015 00:03:00 GMT',
23 silly get     'cache-control': 'max-age=60',
23 silly get     etag: '"4BVZDI35PTW2AJYEDUWWI7RKO"',
23 silly get     age: '0',
23 silly get     'x-served-by': 'cache-atl6234-ATL',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1421020979.907698,VS0,VE107',
23 silly get     vary: 'Accept',
23 silly get     'content-length': '0',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose etag https://registry.npmjs.org/ios-deploy from cache
25 silly addNameRange number 2 { name: 'ios-deploy', range: '*', hasData: true }
26 silly addNameRange versions [ 'ios-deploy',
26 silly addNameRange   [ '1.0.1',
26 silly addNameRange     '1.0.2',
26 silly addNameRange     '1.0.3',
26 silly addNameRange     '1.0.4',
26 silly addNameRange     '1.0.5',
26 silly addNameRange     '1.0.6',
26 silly addNameRange     '1.0.7',
26 silly addNameRange     '1.0.8',
26 silly addNameRange     '1.0.9',
26 silly addNameRange     '1.1.0',
26 silly addNameRange     '1.2.0',
26 silly addNameRange     '1.3.0',
26 silly addNameRange     '1.3.1',
26 silly addNameRange     '1.3.2' ] ]
27 verbose addNamed ios-deploy@1.3.2
28 silly addNamed semver.valid 1.3.2
29 silly addNamed semver.validRange 1.3.2
30 silly cache afterAdd ios-deploy@1.3.2
31 verbose afterAdd /Users/tthomas/.npm/ios-deploy/1.3.2/package/package.json not in flight; writing
32 verbose afterAdd /Users/tthomas/.npm/ios-deploy/1.3.2/package/package.json written
33 silly install resolved [ { name: 'ios-deploy',
33 silly install resolved     version: '1.3.2',
33 silly install resolved     description: 'launch iOS apps iOS devices from the command line (Xcode 6)',
33 silly install resolved     main: 'ios-deploy',
33 silly install resolved     scripts: { preinstall: 'make ios-deploy' },
33 silly install resolved     bin: { 'ios-deploy': './ios-deploy' },
33 silly install resolved     repository: { type: 'git', url: 'https://github.com/phonegap/ios-deploy' },
33 silly install resolved     keywords: [ 'ios-deploy', 'deploy to iOS device' ],
33 silly install resolved     author: { name: 'Greg Hughes' },
33 silly install resolved     license: 'GPLv3',
33 silly install resolved     gitHead: '33f6a83e1d94df5cf5041e9e16394409c4f63656',
33 silly install resolved     bugs: { url: 'https://github.com/phonegap/ios-deploy/issues' },
33 silly install resolved     homepage: 'https://github.com/phonegap/ios-deploy',
33 silly install resolved     _id: 'ios-deploy@1.3.2',
33 silly install resolved     _shasum: '6ffbbe287cec383198fc977ac6336e150ef2f5bc',
33 silly install resolved     _from: 'ios-deploy@*',
33 silly install resolved     _npmVersion: '1.4.14',
33 silly install resolved     _npmUser: { name: 'shazron', email: 'shazron@gmail.com' },
33 silly install resolved     maintainers: [ [Object] ],
33 silly install resolved     dist:
33 silly install resolved      { shasum: '6ffbbe287cec383198fc977ac6336e150ef2f5bc',
33 silly install resolved        tarball: 'http://registry.npmjs.org/ios-deploy/-/ios-deploy-1.3.2.tgz' },
33 silly install resolved     directories: {},
33 silly install resolved     _resolved: 'https://registry.npmjs.org/ios-deploy/-/ios-deploy-1.3.2.tgz',
33 silly install resolved     readme: 'ERROR: No README data found!' } ]
34 info install ios-deploy@1.3.2 into /usr/local/lib
35 info installOne ios-deploy@1.3.2
36 verbose installOne of ios-deploy to /usr/local/lib not in flight; installing
37 verbose lock using /Users/tthomas/.npm/_locks/ios-deploy-198957223cd98201.lock for /usr/local/lib/node_modules/ios-deploy
38 silly install write writing ios-deploy 1.3.2 to /usr/local/lib/node_modules/ios-deploy
39 silly cache addNamed cb ios-deploy@1.3.2
40 verbose unbuild lib/node_modules/ios-deploy
41 verbose gentlyRm vacuuming /usr/local/lib/node_modules/ios-deploy
42 verbose tar unpack /Users/tthomas/.npm/ios-deploy/1.3.2/package.tgz
43 verbose tar unpacking to /usr/local/lib/node_modules/ios-deploy
44 verbose gentlyRm vacuuming /usr/local/lib/node_modules/ios-deploy
45 silly gunzTarPerm modes [ '755', '644' ]
46 silly gunzTarPerm extractEntry package.json
47 silly gunzTarPerm extractEntry .npmignore
48 silly gunzTarPerm extractEntry README.md
49 silly gunzTarPerm extractEntry LICENSE
50 silly gunzTarPerm extractEntry resources/buildbox/build.sh
51 silly gunzTarPerm extractEntry Makefile
52 silly gunzTarPerm extractEntry CONTRIBUTING.md
53 silly gunzTarPerm extractEntry Entitlements.plist
54 silly gunzTarPerm extractEntry ResourceRules.plist
55 silly gunzTarPerm extractEntry demo.c
56 silly gunzTarPerm extractEntry ios-deploy.c
57 silly gunzTarPerm extractEntry Info.plist
58 silly gunzTarPerm extractEntry MobileDevice.h
59 info preinstall ios-deploy@1.3.2
60 verbose unsafe-perm in lifecycle false
61 info ios-deploy@1.3.2 Failed to exec preinstall script
62 verbose unlock done using /Users/tthomas/.npm/_locks/ios-deploy-198957223cd98201.lock for /usr/local/lib/node_modules/ios-deploy
63 verbose stack Error: ios-deploy@1.3.2 preinstall: `make ios-deploy`
63 verbose stack Exit status 2
63 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
63 verbose stack     at EventEmitter.emit (events.js:98:17)
63 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
63 verbose stack     at ChildProcess.emit (events.js:98:17)
63 verbose stack     at maybeClose (child_process.js:755:16)
63 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:822:5)
64 verbose pkgid ios-deploy@1.3.2
65 verbose cwd /Users/tthomas/priceistruth-app3
66 error Darwin 14.0.0
67 error argv "node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
68 error node v0.10.29
69 error npm  v2.1.18
70 error code ELIFECYCLE
71 error ios-deploy@1.3.2 preinstall: `make ios-deploy`
71 error Exit status 2
72 error Failed at the ios-deploy@1.3.2 preinstall script 'make ios-deploy'.
72 error This is most likely a problem with the ios-deploy package,
72 error not with npm itself.
72 error Tell the author that this fails on your system:
72 error     make ios-deploy
72 error You can get their info via:
72 error     npm owner ls ios-deploy
72 error There is likely additional logging output above.
73 verbose exit [ 1, true ]
74 verbose unbuild lib/node_modules/ios-deploy
75 info preuninstall ios-deploy@1.3.2
76 info uninstall ios-deploy@1.3.2
77 verbose unbuild rmStuff ios-deploy@1.3.2 from /usr/local/lib/node_modules
78 verbose gentlyRm verifying that /usr/local is managed by npm
79 silly isManaged /usr/local is not inside /usr/local/lib/node_modules
80 silly isManaged /usr/local is not inside /usr/local/lib/node_modules
81 silly isManaged /usr/local/bin is inside /usr/local
82 silly gentlyRm /usr/local is managed by npm
83 silly gentlyRm /usr/local/bin/ios-deploy is under /usr/local
84 verbose gentlyRm vacuuming /usr/local/bin/ios-deploy up to /usr/local
85 info postuninstall ios-deploy@1.3.2
86 verbose gentlyRm vacuuming /usr/local/lib/node_modules/ios-deploy
87 silly gentlyRm purging /usr/local/lib/node_modules/ios-deploy
88 silly gentlyRm quitting because other entries in /usr/local/lib/node_modules
 ```

your help is greatly appreciated.

Thank you,
Tyrone

**Comment by shazron** [comment]
Provide the info required in https://github.com/phonegap/ios-deploy/blob/master/CONTRIBUTING.md

**Comment by dreadstar** [comment]
apologies for the delayed response.  i ran the commands:
 sw_vers -productVersion
10.10.2

ios-deploy -V
-bash: ios-deploy: command not found

xcodebuild -version
Xcode 6.1.1
Build version 6A2008a

xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

gcc --version
couldn't understand kern.osversion `14.1.0'
i686-apple-darwin13-gcc-apple-4.2.1 (GCC) 4.2.1 (Apple Inc. build 5666) (dot 3) (MacPorts apple-gcc42 5666.3_13)
Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

lldb --version
lldb-320.4.156



i am going to look into the missing ios-deploy and the couldn't understand kern.osversion `14.1.0'
error. the Ios-deploy missing is strange because I thought i had already installed, but it may have been before upgrade to Mavericks. But i wanted to at least reply so the issue can remain open a little longer.
Thanks,
Tyrone

**Comment by shazron** [comment]
Try http://stackoverflow.com/a/26609483

**Comment by dreadstar** [comment]
i tried to reinstall ios-depoy with
sudo npm install -g ios-deploy
Password:
-
> ios-deploy@1.4.0 preinstall /usr/local/lib/node_modules/ios-deploy
> make ios-deploy

rm -rf *.app demo ios-deploy
gcc -ObjC -g -o ios-deploy -framework Foundation -framework CoreFoundation -framework MobileDevice -F/System/Library/PrivateFrameworks ios-deploy.c
couldn't understand kern.osversion `14.1.0'
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:55,
                 from /System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:12,
                 from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:80,
                 from ios-deploy.c:4:
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262: error: expected ',' or '}' before '__attribute__'
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414: error: expected ',' or '}' before '__attribute__'
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:119,
                 from ios-deploy.c:4:
/System/Library/Frameworks/Foundation.framework/Headers/NSUserActivity.h:55: error: expected a property attribute before 'weak'
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:171,
                 from ios-deploy.c:4:
/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:16: error: expected ',' or '}' before '__attribute__'
Makefile:19: recipe for target 'ios-deploy' failed
make: *** [ios-deploy] Error 1
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v0.10.29
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! ios-deploy@1.4.0 preinstall: `make ios-deploy`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ios-deploy@1.4.0 preinstall script 'make ios-deploy'.
npm ERR! This is most likely a problem with the ios-deploy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make ios-deploy
npm ERR! You can get their info via:
npm ERR!     npm owner ls ios-deploy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:




++++++++++++++++++++++++++++++++++++
the output of the npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'ios-deploy' ]
2 info using npm@2.3.0
3 info using node@v0.10.29
4 silly cache add args [ 'ios-deploy', null ]
5 verbose cache add spec ios-deploy
6 silly cache add parsed spec { raw: 'ios-deploy',
6 silly cache add   scope: null,
6 silly cache add   name: 'ios-deploy',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed ios-deploy@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'ios-deploy', range: '*', hasData: false }
11 silly mapToRegistry name ios-deploy
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/ios-deploy
15 verbose addNameRange registry:https://registry.npmjs.org/ios-deploy not in flight; fetching
16 verbose request uri https://registry.npmjs.org/ios-deploy
17 verbose request no auth needed
18 info attempt registry request try #1 at 21:07:10
19 verbose request id 251461fdc0cb9f1f
20 verbose etag "41G68TKKYGSN5OACY2XQABNID"
21 http request GET https://registry.npmjs.org/ios-deploy
22 http 304 https://registry.npmjs.org/ios-deploy
23 silly get cb [ 304,
23 silly get   { date: 'Sat, 07 Mar 2015 02:07:11 GMT',
23 silly get     server: 'Apache',
23 silly get     via: '1.1 varnish',
23 silly get     'last-modified': 'Sat, 07 Mar 2015 02:07:11 GMT',
23 silly get     'cache-control': 'max-age=60',
23 silly get     etag: '"41G68TKKYGSN5OACY2XQABNID"',
23 silly get     age: '50',
23 silly get     'x-served-by': 'cache-iad2136-IAD',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1425694031.548827,VS0,VE0',
23 silly get     vary: 'Accept',
23 silly get     'content-length': '0',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose etag https://registry.npmjs.org/ios-deploy from cache
25 silly addNameRange number 2 { name: 'ios-deploy', range: '*', hasData: true }
26 silly addNameRange versions [ 'ios-deploy',
26 silly addNameRange   [ '1.0.1',
26 silly addNameRange     '1.0.2',
26 silly addNameRange     '1.0.3',
26 silly addNameRange     '1.0.4',
26 silly addNameRange     '1.0.5',
26 silly addNameRange     '1.0.6',
26 silly addNameRange     '1.0.7',
26 silly addNameRange     '1.0.8',
26 silly addNameRange     '1.0.9',
26 silly addNameRange     '1.1.0',
26 silly addNameRange     '1.2.0',
26 silly addNameRange     '1.3.0',
26 silly addNameRange     '1.3.1',
26 silly addNameRange     '1.3.2',
26 silly addNameRange     '1.4.0' ] ]
27 verbose addNamed ios-deploy@1.4.0
28 silly addNamed semver.valid 1.4.0
29 silly addNamed semver.validRange 1.4.0
30 silly mapToRegistry name ios-deploy
31 silly mapToRegistry using default registry
32 silly mapToRegistry registry https://registry.npmjs.org/
33 silly mapToRegistry uri https://registry.npmjs.org/ios-deploy
34 verbose addRemoteTarball https://registry.npmjs.org/ios-deploy/-/ios-deploy-1.4.0.tgz not in flight; adding
35 verbose addRemoteTarball [ 'https://registry.npmjs.org/ios-deploy/-/ios-deploy-1.4.0.tgz',
35 verbose addRemoteTarball   '94599f8082711af072bee1b67f01d10a34c168ef' ]
36 info retry fetch attempt 1 at 21:07:11
37 info attempt registry request try #1 at 21:07:11
38 http fetch GET https://registry.npmjs.org/ios-deploy/-/ios-deploy-1.4.0.tgz
39 http fetch 200 https://registry.npmjs.org/ios-deploy/-/ios-deploy-1.4.0.tgz
40 silly fetchAndShaCheck shasum 94599f8082711af072bee1b67f01d10a34c168ef
41 verbose addTmpTarball /tmp/npm-56129-f0da7115/registry.npmjs.org/ios-deploy/-/ios-deploy-1.4.0.tgz not in flight; adding
42 verbose addTmpTarball already have metadata; skipping unpack for ios-deploy@1.4.0
43 silly cache afterAdd ios-deploy@1.4.0
44 verbose afterAdd /Users/tthomas/.npm/ios-deploy/1.4.0/package/package.json not in flight; writing
45 verbose afterAdd /Users/tthomas/.npm/ios-deploy/1.4.0/package/package.json written
46 silly install resolved [ { name: 'ios-deploy',
46 silly install resolved     version: '1.4.0',
46 silly install resolved     description: 'launch iOS apps iOS devices from the command line (Xcode 6)',
46 silly install resolved     main: 'ios-deploy',
46 silly install resolved     scripts: { preinstall: 'make ios-deploy' },
46 silly install resolved     bin: { 'ios-deploy': './ios-deploy' },
46 silly install resolved     repository: { type: 'git', url: 'https://github.com/phonegap/ios-deploy' },
46 silly install resolved     keywords: [ 'ios-deploy', 'deploy to iOS device' ],
46 silly install resolved     author: { name: 'Greg Hughes' },
46 silly install resolved     license: 'GPLv3',
46 silly install resolved     gitHead: '56abf4e92e390350a79999df277eb6a8cc067a31',
46 silly install resolved     bugs: { url: 'https://github.com/phonegap/ios-deploy/issues' },
46 silly install resolved     homepage: 'https://github.com/phonegap/ios-deploy',
46 silly install resolved     _id: 'ios-deploy@1.4.0',
46 silly install resolved     _shasum: '94599f8082711af072bee1b67f01d10a34c168ef',
46 silly install resolved     _from: 'ios-deploy@*',
46 silly install resolved     _npmVersion: '1.4.21',
46 silly install resolved     _npmUser: { name: 'shazron', email: 'shazron@gmail.com' },
46 silly install resolved     maintainers: [ [Object], [Object], [Object] ],
46 silly install resolved     dist:
46 silly install resolved      { shasum: '94599f8082711af072bee1b67f01d10a34c168ef',
46 silly install resolved        tarball: 'http://registry.npmjs.org/ios-deploy/-/ios-deploy-1.4.0.tgz' },
46 silly install resolved     directories: {},
46 silly install resolved     _resolved: 'https://registry.npmjs.org/ios-deploy/-/ios-deploy-1.4.0.tgz' } ]
47 info install ios-deploy@1.4.0 into /usr/local/lib
48 info installOne ios-deploy@1.4.0
49 verbose installOne of ios-deploy to /usr/local/lib not in flight; installing
50 verbose lock using /Users/tthomas/.npm/_locks/ios-deploy-198957223cd98201.lock for /usr/local/lib/node_modules/ios-deploy
51 silly install write writing ios-deploy 1.4.0 to /usr/local/lib/node_modules/ios-deploy
52 silly cache addNamed cb ios-deploy@1.4.0
53 verbose unbuild lib/node_modules/ios-deploy
54 verbose gentlyRm vacuuming /usr/local/lib/node_modules/ios-deploy
55 verbose tar unpack /Users/tthomas/.npm/ios-deploy/1.4.0/package.tgz
56 verbose tar unpacking to /usr/local/lib/node_modules/ios-deploy
57 verbose gentlyRm vacuuming /usr/local/lib/node_modules/ios-deploy
58 silly gunzTarPerm modes [ '755', '644' ]
59 silly gunzTarPerm extractEntry package.json
60 silly gunzTarPerm extractEntry .npmignore
61 silly gunzTarPerm extractEntry README.md
62 silly gunzTarPerm extractEntry LICENSE
63 silly gunzTarPerm extractEntry resources/buildbox/build.sh
64 silly gunzTarPerm extractEntry Makefile
65 silly gunzTarPerm extractEntry CONTRIBUTING.md
66 silly gunzTarPerm extractEntry Entitlements.plist
67 silly gunzTarPerm extractEntry ResourceRules.plist
68 silly gunzTarPerm extractEntry demo.c
69 silly gunzTarPerm extractEntry ios-deploy.c
70 silly gunzTarPerm extractEntry Info.plist
71 silly gunzTarPerm extractEntry MobileDevice.h
72 info preinstall ios-deploy@1.4.0
73 verbose unsafe-perm in lifecycle false
74 info ios-deploy@1.4.0 Failed to exec preinstall script
75 verbose unlock done using /Users/tthomas/.npm/_locks/ios-deploy-198957223cd98201.lock for /usr/local/lib/node_modules/ios-deploy
76 verbose stack Error: ios-deploy@1.4.0 preinstall: `make ios-deploy`
76 verbose stack Exit status 2
76 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
76 verbose stack     at EventEmitter.emit (events.js:98:17)
76 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
76 verbose stack     at ChildProcess.emit (events.js:98:17)
76 verbose stack     at maybeClose (child_process.js:755:16)
76 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:822:5)
77 verbose pkgid ios-deploy@1.4.0
78 verbose cwd /Users/tthomas/priceistruth-app3
79 error Darwin 14.1.0
80 error argv "node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
81 error node v0.10.29
82 error npm  v2.3.0
83 error code ELIFECYCLE
84 error ios-deploy@1.4.0 preinstall: `make ios-deploy`
84 error Exit status 2
85 error Failed at the ios-deploy@1.4.0 preinstall script 'make ios-deploy'.
85 error This is most likely a problem with the ios-deploy package,
85 error not with npm itself.
85 error Tell the author that this fails on your system:
85 error     make ios-deploy
85 error You can get their info via:
85 error     npm owner ls ios-deploy
85 error There is likely additional logging output above.
86 verbose exit [ 1, true ]
87 verbose unbuild lib/node_modules/ios-deploy
88 info preuninstall ios-deploy@1.4.0
89 info uninstall ios-deploy@1.4.0
90 verbose unbuild rmStuff ios-deploy@1.4.0 from /usr/local/lib/node_modules
91 verbose gentlyRm verifying that /usr/local is managed by npm
92 silly isManaged /usr/local is not inside /usr/local/lib/node_modules
93 silly isManaged /usr/local is not inside /usr/local/lib/node_modules
94 silly isManaged /usr/local/bin is inside /usr/local
95 silly gentlyRm /usr/local is managed by npm
96 silly gentlyRm /usr/local/bin/ios-deploy is under /usr/local
97 verbose gentlyRm vacuuming /usr/local/bin/ios-deploy up to /usr/local
98 info postuninstall ios-deploy@1.4.0
99 verbose gentlyRm vacuuming /usr/local/lib/node_modules/ios-deploy
100 silly gentlyRm purging /usr/local/lib/node_modules/ios-deploy
101 silly gentlyRm quitting because other entries in /usr/local/lib/node_modules

**Comment by shazron** [comment]
Did you see my comment before this? Try that.

**Comment by dreadstar** [comment]
i tried the recommendation and got this:
xcode-select --install 
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

i believe i had previously reinstalled xcode after upgrading to Mavericks.

**Comment by shazron** [comment]
In that same link I posted, in other answers in the SO post, they have your same error -- you have a non-standard gcc, so upgrade it. This is a tools error, not an ios-deploy one ultimately.

**Comment by dreadstar** [comment]
The solution ended being a variation instead of

cd /usr/local/bin
ln -s /Applications//Xcode.app/Contents/Developer/usr/bin/gcc gcc

i used
 down vote
	

This solve my problem: I link gcc with /Applications//Xcode.app/Contents/Developer/usr/bin/gcc

cd /opt/local/bin
sudo rm ./gcc
sudo ln -s /Applications/Xcode.app/Contents/Developer/usr/bin/gcc gcc

it then seemed that ios-deploy installed successfully with 
sudo npm install -g ios-deploy

output:
> ios-deploy@1.4.0 preinstall /usr/local/lib/node_modules/ios-deploy
> make ios-deploy

rm -rf *.app demo ios-deploy
gcc -ObjC -g -o ios-deploy -framework Foundation -framework CoreFoundation -framework MobileDevice -F/System/Library/PrivateFrameworks ios-deploy.c
/usr/local/bin/ios-deploy -> /usr/local/lib/node_modules/ios-deploy/ios-deploy
ios-deploy@1.4.0 /usr/local/lib/node_modules/ios-deploy

Thank you for your help.
