### ISSUE TITLE
Uninstalling an application

### ISSUE THREAD

**Issue by thekushpatel** [phonegap/ios-deploy#99]
I want to be able to uninstall an application after I have installed it.  The docs say not to use the -r flag with the -m flag, however this seems to uninstall the application.  Is there a reason I shouldn't uninstall the application this way?  Does it leave the phone in a bad state?  Or does it not completely uninstall?

**Comment by shazron** [comment]
Uninstall flag should only work on its own, and will always uninstall the application regardless
